### ISSUE TITLE
unauthenticated access to sensitive pages

### ISSUE THREAD

**Issue by 0xc4sper0** [projectdiscovery/nuclei-templates#10021]
Allows attackers to gain unauthenticated access to odoo CMS databases page 

### Template for?
odoo CMS

template :

```
id: OdooCMS

info:
    name: unauthenticated access to sensitive pages
    author: c4sper0
    description: |
     "Allows attackers to gain unauthenticated access to odoo CMS databases sensitive pages"
    severity: high
    tags: odoo,cms,database

requests:
  - raw:
      - |
        GET /web/database/selector HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
        - type: word
          part: body
          words:
            - "Create Database"
        - type: status
          status:
            - 200

```
### Details:

<img width="567" alt="1" src="https://github.com/projectdiscovery/nuclei-templates/assets/110319650/13e5f2ec-b844-4a7d-8895-115a0e9a0bd8">
<img width="542" alt="2" src="https://github.com/projectdiscovery/nuclei-templates/assets/110319650/e5a176a4-b696-4e86-bd51-17cbbcfe534e">

**Comment by 0xc4sper0** [comment]
Guys.. I'm really sorry

It appears to be a duplicate template.
I scanned a target and the path was not detected in the tool before downloading the template above.

It's weird

**Comment by ehsandeep** [comment]
closing as duplicate => `http/exposed-panels/openerp-database.yaml`
