### ISSUE TITLE
time-based-sqli.yaml not working

### ISSUE THREAD

**Issue by SecDev0ps** [projectdiscovery/nuclei-templates#10067]
I don't think it's working. I'm getting a lot of alerts, but none of them seem to do anything.

![image](https://github.com/projectdiscovery/nuclei-templates/assets/83069165/ef2fe8b7-2cb5-4a06-8c46-7e12bc57bd76)

**Comment by SecDev0ps** [comment]
![image](https://github.com/projectdiscovery/nuclei-templates/assets/83069165/a6fb19b2-6fc1-41e3-bf6a-45ff74973373)

sqlmap showing that it's just lagging and I am fully agree with that

**Comment by mastercho** [comment]
If you check our conversation at https://github.com/projectdiscovery/nuclei-templates/pull/9695#event-13167669254 you will see why is that :)
