### ISSUE TITLE
minecraft-enum

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/nuclei-templates#10091]
### Template file: minecraft-enum

Can we finally fix this? From hitting  every port as minecraft server? Also @DhiyaneshGeek  please confirm is really fixed before approve PR's, we see you approve lot of PR's with issues but when come to ordinary users like us you hold PR for months...

**Comment by DhiyaneshGeek** [comment]
Hi @mastercho 

we have raised PR #10092 , kindly confirm if you still facing the false positive 

Thanks

**Comment by mastercho** [comment]
Issue is not solved and still reports for false positive!
