### ISSUE TITLE
idemia-biometrics-default-login FP

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/nuclei-templates#10126]
### Template file:
https://github.com/projectdiscovery/nuclei-templates/blob/885b0f30ef7da94993b1429bdcad24d893462756/http/default-logins/idemia/idemia-biometrics-default-login.yaml#L2

### Anything else:
![MobaXterm_9OZSMtOPLP](https://github.com/projectdiscovery/nuclei-templates/assets/10222100/949d62b6-3841-4e57-800b-d6ad0008fe43)

**Comment by ritikchaddha** [comment]
Hello @mastercho, Thank you for raising this issue and for your contribution to this project. Your efforts are greatly appreciated. Cheers!
