### ISSUE TITLE
Too many false positive on beanstalk-service.yaml

### ISSUE THREAD

**Issue by theMiddleBlue** [projectdiscovery/nuclei-templates#10310]
The following template seems to lead to many false positive on POP3 and IMAP services. It basically matches every "OK" in response.

Moreover, am I wrong or it doesn't follow the "Using multiple matchers" policy?

https://github.com/projectdiscovery/nuclei-templates/blob/51194f2d14fb1fedbd139050084ee1536b3ae6c2/network/enumeration/beanstalk-service.yaml#L25-L29

Thank you!

**Comment by pussycat0x** [comment]
Hi @theMiddleBlue ,
Thank you for bringing this issue to our attention. It has now been resolved.
