### ISSUE TITLE
tongda-arbitrary-login.yaml

### ISSUE THREAD

**Issue by Phoenix1112** [projectdiscovery/nuclei-templates#10390]
2. There seems to be an error in the dsl. It shows false positive result on my target.This is exactly the only part the code can't read. ```!contains(body_2,"<title>用户未登录</title>")```

This could probably be due to the exclamation mark. ```!contains```

```
          - 'status_code_1 == 200 && contains(header_1, "Set-Cookie") && contains(header_1,"PHPSESSID")'
          - 'status_code_2 == 200 && !contains(body_2,"<title>用户未登录</title>")  && contains(body_2,"loginUser")'
```

**Comment by pussycat0x** [comment]
Hi @Phoenix1112,  Thanks for bringing this issue to my attention. Could you please share the debug data? I've tested it on my end and everything seems to be working fine.

**Comment by ritikchaddha** [comment]
Hello @Phoenix1112, thank you for bringing this issue to our attention. We've fixed the template with an additional request to check for the vulnerable target first.
