### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SMILESHx** [projectdiscovery/nuclei-templates#10471]
xcluded 1 headless template[s] (disabled as default), use -headless option to run headless templates.
[INF] Current nuclei version: v3.2.9 (outdated)
[INF] Current nuclei-templates version: v9.9.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] Targets loaded for current scan: 264990
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan

how to fix this

**Comment by fisehara** [comment]
@SMILESHx Can you please provide how you call nuclei and if you use a `config.yml` share it's content.

The behavior that you see is, that nuclei has no template loaded to execute.

**Comment by DhiyaneshGeek** [comment]
Hi @fisehara 

kindly use -headless while running headless template

hope this helps

feel free to re-open the issue , if you still facing the issue

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!
