### ISSUE TITLE
exposed-gitignore & mercurial-hgignore FP

### ISSUE THREAD

**Issue by iuliu8899** [projectdiscovery/nuclei-templates#10503]
### Template file:
http/exposures/configs/mercurial-hgignore.yaml
http/exposures/configs/exposed-gitignore.yaml

### Command to reproduce:

response matched
```
<Response xmlns="http://www.huawei.com/switchcenter">
  <errNo>4</errNo>
  <description>Request Not Support</description>
</Response>
```

https://218.107.38.142:8443

fofa query: "switchcenter"

**Comment by princechaddha** [comment]
Hello, the response time for this issue was longer than usual because the team was traveling for DEFCON. The team will respond to this issue shortly. Thank you for your contribution

**Comment by DhiyaneshGeek** [comment]
Hi @iuliu8899 

i have fixed the false positive caused with a negative matcher and updated the template accordingly and raised PR for the same #10651 

Let me know if these changes works !

Thanks for flagging this issue , appreciate it ..
