### ISSUE TITLE
[Bug] Added more matcher, request, etc to fix https://github.com/projectdiscovery/nuclei/issues/5546

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei-templates#10590]
Issue: https://github.com/projectdiscovery/nuclei/issues/5546

Many javascript templates use hard-coded ports. And according to one dev said to add some matchers etc to avoid false positives

**Comment by pussycat0x** [comment]
Hi @daffainfo   can you Try this updated Template? it's working fine from my end https://github.com/projectdiscovery/nuclei-templates/pull/10655/

**Comment by daffainfo** [comment]
Do not close this issue yet, are you guys already fix`redis-require-auth`?

**Comment by DhiyaneshGeek** [comment]
Hi @daffainfo 

we observed only x11-unauth-access-intrusive was false positive and fixed the template and closed the issue

thanks for re-opening and letting us know about the issue
