### ISSUE TITLE
[Bug] 'condtion' in use rather than 'condition'

### ISSUE THREAD

**Issue by nrathaus** [projectdiscovery/nuclei-templates#1063]
Hi,

I am not sure if this was intentional to write it spelled incorrectly, but the spelling is wrong for the word 'condition' in the templates

**Comment by ehsandeep** [comment]
@nrathaus updated here https://github.com/projectdiscovery/nuclei-templates/commit/06945d56a8c0e69416d6c228417dbd879cfa2381, definitely not intentional, appreciate your attention on this.
