### ISSUE TITLE
[Bug]  line 10: cannot unmarshal !!seq into string

### ISSUE THREAD

**Issue by savushkin-yauheni** [projectdiscovery/nuclei-templates#1074]
Hi team!

**Describe the bug**
After adding reference a lot of templates throw err:
`line 10: cannot unmarshal !!seq into string` 
i think it's about spaces or something like that. 

e.x. https://github.com/projectdiscovery/nuclei-templates/commit/0a1c4057a35414bfc44f419b6a44541043befcd6

Maybe you can use some linters on templates ?

Thanks.

**Comment by ehsandeep** [comment]
thank you for reporting this @savushkin-yauheni, should be fixed with https://github.com/projectdiscovery/nuclei-templates/pull/1075
