### ISSUE TITLE
[Bug] workflow Error, no templates were found.

### ISSUE THREAD

**Issue by savushkin-yauheni** [projectdiscovery/nuclei-templates#1077]
Hi team

**Nuclei version**
2.3.0

**Nuclei template version**
{"templates-directory":"/root/nuclei-templates","current-version":"8.1.4","last-checked":"2021-03-12T09:36:56.246411342Z"}

**Describe the bug**
I think workflows are broken. I can't launch anyone. 

**Commands to reproduce**
nuclei  -target https://google.com -t workflows/wordpress-workflow.yaml

Thanks.

**Comment by ehsandeep** [comment]
@savushkin-yauheni this is intended change, now workflows can be executed using `w` or `workflows` flag, details updated here https://nuclei.projectdiscovery.io/nuclei/get-started/#running-nuclei
