### ISSUE TITLE
Form based issue templates

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei-templates#10851]
To ease the triage process and collect information in formatted manner, we can improve the Github issue templates using form similar to [nuclei](https://github.com/projectdiscovery/nuclei/issues/new?assignees=&labels=Type%3A+Bug&projects=&template=bug-report.yml&title=%5BBUG%5D+...)

Templates to convert:

- [x] False Negative
- [x] False Positive
- [x] Template Request
- [x] Template Contribution

**Comment by dwisiswant0** [comment]
I think the `Feature request` issue template could be left out & follow the same format as the `Issue report` template. I haven't come across any specific cases where the `Feature request` template would be necessary for the context of this repo. Wdyt?

**Comment by dwisiswant0** [comment]
Looks like we can remove the `Feature request` template since we already have the "Share idea / feature [...]" option that redirects users to the discussion page. There's also a chance we might drop the `Issue report` template as well?
