### ISSUE TITLE
[BUG] Could not parsing `wordpress-wp-mail-logging` template

### ISSUE THREAD

**Issue by EmptyZeroRain** [projectdiscovery/nuclei-templates#10908]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

When I run nucleus. It prompts to update the nucleus templates. When I run nucleus again after the update is complete, it prompts [WRN] Found 2 templates with runtime error (use - validate flag for further examination)

### Expected Behavior

When I use nucleus validate, an error message appears [ERR] Error occurred parsing template nuclei-templates/http/technologies/wordpress/plugins/wp-mail-logging.yaml: could not compile request: could not parse payloads: the helpers/wordpress/plugins/wp-mail-logging.txt file for payload last_version does not exist or does not contain enough elements
[FTL] Could not validate templates: errors occurred during template validation

### Steps To Reproduce

nuclei -validate

### Relevant log output

```shell
[WRN] Could not parse workflow template nuclei-templates/http/technologies/wordpress/plugins/wp-mail-logging.yaml: could not compile request: could not parse payloads: the helpers/wordpress/plugins/wp-mail-logging.txt file for payload last_version does not exist or does not contain enough elements
[WRN] Could not parse workflow template nuclei-templates/http/technologies/wordpress/plugins/extendify.yaml: could not compile request: could not parse payloads: the helpers/wordpress/plugins/extendify.txt file for payload last_version does not exist or does not contain enough elements
[ERR] Error occurred parsing template nuclei-templates/http/technologies/wordpress/plugins/wp-mail-logging.yaml: could not compile request: could not parse payloads: the helpers/wordpress/plugins/wp-mail-logging.txt file for payload last_version does not exist or does not contain enough elements
[FTL] Could not validate templates: errors occurred during template validation
```

### Environment

```markdown
- OS: mac os 12 
- Nuclei:  v3.3.4 
- Go: go version go1.23.1 darwin/amd64
```

**Comment by DhiyaneshGeek** [comment]
Hi @EmptyZeroRain 

we have fixed the issue https://github.com/projectdiscovery/nuclei-templates/pull/10905

Let me know still you are facing the issue 

Thanks
