### ISSUE TITLE
[FALSE-POSITIVE] x11-unauth-access.yaml template

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei-templates#11309]
### Template IDs or paths

```markdown
- /javascript/misconfiguration/x11/x11-unauth-access.yaml
```

### Environment

```markdown
- OS: -
- Nuclei: -
- Go: -
```

### Steps To Reproduce

1. nuclei -u HOST:PORT -t nuclei-templates/javascript/misconfiguration/x11/x11-unauth-access.yaml --debug

### Relevant dumped responses

```shell
-
```

## Note:
I'm using this Shodan query: `product:"MikroTik bandwidth-test server"` to reproduce the false positive results, and all of the hosts give me false positive results

## Cause:
The template produces a lot of false positives because of this weak matcher:
```javascript
let accessGranted;

if (result[0] === 1) {
    accessGranted = "x11 Unauth Access - Detected";
} else {
    conn.Close();
}
```

**Comment by princechaddha** [comment]
Hi @daffainfo, Thank you for taking the time to create this issue and for contributing to this project. I have updated the template to fix false positive results.
