### ISSUE TITLE
[Feature] Add default ports to templates

### ISSUE THREAD

**Issue by gaby** [projectdiscovery/nuclei-templates#1163]
**Is your feature request related to a problem? Please describe.**

Currently none of the templates define default ports. All the templates only take a baseURL with no alternatives.for ex: RabbitMQ templates should also include an entry for port 15672, 80, 443 for the mgmt UI. 

**Describe the solution you'd like**

Default ports added to each template.

**Comment by geeknik** [comment]
Hello. It's up to the user to provide the correct ports as part of the URL list used with nuclei. If for example you're scanning for RabbitMQ then you would provide a list of URLs with the proper management ports defined. 👍🏻

**Comment by ehsandeep** [comment]
thank you for suggesting this @gaby, as geeknik mentioned, it's expected that users will feed actual URLs where templates need to be executed, defining ports into template results into every input requesting to the port defined in the template, and most of the time it's going to be timed out as unrelated host input will be connecting to those ports and causes performance issue overall.

**Comment by gaby** [comment]
Sounds good to me!
