### ISSUE TITLE
[false-positive] hatenablog-takeover

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1188]
**Nuclei version**

```
2.3.2
```

**Nuclei template version**

```
8.1.4
```

**Template ID**

hatenablog-takeover

**Commands to Reproduce**

```
nuclei -t takeovers/hatenablog-takeover.yaml -target https://insiders.sendgrid.com
nuclei -t takeovers/hatenablog-takeover.yaml -target https://toolkit.classdojo.com

```

The results have nothing to do with hatenablog.

**Comment by ehsandeep** [comment]
Thank you @pdelteil for reporting, fixed here https://github.com/projectdiscovery/nuclei-templates/commit/9aff53118b4414641fb4c8cd6ffabf467cfaf517
