### ISSUE TITLE
[false-positive] redmine-db-config 

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1195]
**Nuclei version**

```
v2.3.2
```

**Nuclei template version**

```
8.1.4
```

**Template ID**

 redmine-db-config

**Commands to Reproduce**

```
nuclei -t exposures/configs/redmine-db-config.yaml -target https://music.youtube.com/
nuclei -t exposures/configs/redmine-db-config.yaml -target https://pl.pinterest.com
```

**Comment by ehsandeep** [comment]
thank you @pdelteil for reporting this, should be fixed with https://github.com/projectdiscovery/nuclei-templates/blob/3ef39c173e4cc1937158c6ad9ab30d2f2e7366d1/exposures/configs/redmine-db-config.yaml
