### ISSUE TITLE
Regex missing valid result

### ISSUE THREAD

**Issue by melbadry9** [projectdiscovery/nuclei-templates#121]
https://github.com/projectdiscovery/nuclei-templates/blob/827db6a33e4008ff8bf36ab0766a6f219fd78b20/vulnerabilities/crlf-injection.yaml#L16

### Example 
```http
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Mon, 25 May 2020 16:32:58 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: Redacted
< Set-Cookie:crlfinjection=crlfinjection
```

**Comment by bauthard** [comment]
Thank you @melbadry9 for creating this issue, I also found a similar mismatch with URL redirect regex as well, need to adjust the regex to fix this. 

https://github.com/projectdiscovery/nuclei-templates/blob/827db6a33e4008ff8bf36ab0766a6f219fd78b20/vulnerabilities/open-redirect.yaml#L19

Above regex also missed valid redirect for the following example:- 

```
HTTP/1.1 302 Found
Date: Mon, 25 May 2020 22:16:45 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 39
Connection: close
Location: https://evil.com/
Vary: Accept

Found. Redirecting to https://evil.com/
```

**Comment by melbadry9** [comment]
This pull request should fix the false negative #122

**Comment by Pxmme** [comment]
Hey guys,

Am I missing something? The original regex for CRLF injection seems to match @melbadry9's example:

![image](https://user-images.githubusercontent.com/22918318/83286821-e3834a80-a1e0-11ea-8ff7-5567ac1b7582.png)

The original regex for open redirection also seems to match @bauthard's example:

![image](https://user-images.githubusercontent.com/22918318/83286904-07469080-a1e1-11ea-8ed6-08d2abb848fb.png)

What am I missing here? 🤔

**Comment by melbadry9** [comment]
@Pxmme your regex works on theory, but when tested on vulneable host didn't match. I don't know why. 
@bauthard @Ice3man543 any idea about this behavior?

**Comment by bauthard** [comment]
Indeed it looks valid here but didn't work out on vulnerable targets, if you want I've some targets to confirm in the discord server @Pxmme ?

**Comment by Pxmme** [comment]
Hey @bauthard yeah I'd be happy to, shoot me a DM on Discord!

**Comment by Pxmme** [comment]
Unable to figure this out... @melbadry9 suggested that we should look at "how Nuclei actually parses the headers and the HTTP responses", but that's way out of my skill zone 😆 

All the original regex are matching every case possible on multiple regex-sandbox websites such as https://regex101.com/, https://regexr.com/ and https://www.regextester.com/ FYI @bauthard

**Comment by manuelbua** [comment]
@Pxmme i noticed the same thing while testing more edge cases in #152: dropping the start of line/text `^` would work, as is prepending a `(?m)` for multiline matching, so both of these should work:
```
(?m)^Location..
Location
```

Also escaping regexes in YAML is quite a beast :)

**Comment by melbadry9** [comment]
The issue is now fixed.
