### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [projectdiscovery/nuclei-templates#1323]
after every update of templates .nuclei-ignore reset itself I don't think it's some kind of feature. as need to reconfigure it can you please make a change to have it not updated along with updation of templates

**Comment by ehsandeep** [comment]
Hi @GDATTACKER-RESEARCHER, 

This is expected, as detailed here https://nuclei.projectdiscovery.io/nuclei/get-started/#template-exclusion, `.nuclei-ignore` is something not meant to used/update by users, as nuclei support [config file](https://nuclei.projectdiscovery.io/nuclei/get-started/#nuclei-config), you can overwrite `nuclei-ignore` by explicitly adding/removing tags in your default config file which will remain unchanged after updates.
