### ISSUE TITLE
[nuclei-template] Exposed mysql.initial

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#1374]
Exposed mysql.initial

https://github.com/Elsfa7-110/testbug/blob/main/mysql.initial.yaml

**Template Details**

id: exposed-mysql-initial

info:
  name: Exposed mysql.initial
  author: ELSFA7110
  severity: info
  reference: |
        - https://hackerone.com/reports/1081817
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/mysql.initial.sql"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Roundcube Webmail initial database structure"
        part: body
        condition: and

      - type: status
        status:
          - 200

```

**Comment by NagliNagli** [comment]
I actually created this for me as well, but I don't think it's a vuln.

he got rewarded for other stuff, it's a generic file.

**Comment by ehsandeep** [comment]
@NagliNagli You are right, so the severity is marked as `info`

**Comment by ehsandeep** [comment]
thank you @Elsfa7-110, added the template in the linked PR.

**Comment by NagliNagli** [comment]
Good @ehsandeep
