### ISSUE TITLE
Need to send same header with multiple values in same template

### ISSUE THREAD

**Issue by Vishnuraghav89** [projectdiscovery/nuclei-templates#1379]
Could you please give provide an example template for below scenerio.

Header: value1
Header: value2

{{Baseurl}}

I want that first request need to sent with value 1 and then second request need to sent with value2.

Both request need to sent separately with same header but with different different value in same template only.

**Comment by ehsandeep** [comment]
@Vishnuraghav89 this same as https://github.com/projectdiscovery/nuclei-templates/discussions/1378, closing from here.
