### ISSUE TITLE
[false-positive] top-xss-params

### ISSUE THREAD

**Issue by ramondunker** [projectdiscovery/nuclei-templates#1420]
**Nuclei version**
```
2.3.6
```

**Nuclei template version**

```
8.2.4
```

**Template ID**

```
top-xss-params
```

**Commands to Reproduce**

```
nuclei -t  nuclei-templates/vulnerabilities/generic/top-xss-params.yaml -target https://events.developers.zebra.com/
```

**Comment by geeknik** [comment]
Please test the change in #1421 and let me know if this solves your FP.

**Comment by ramondunker** [comment]
Hi @geeknik, #1421 did fix this FP. Thanks for the swift response :)

**Comment by geeknik** [comment]
You're welcome. :) Good luck out there!
