### ISSUE TITLE
[false-positive] unbounce-takeover 

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1433]
More than a false positive, is not possible to takeover anymore. The remaining edge case doesn't work anymore ([more info](https://github.com/EdOverflow/can-i-take-over-xyz/issues/11))

**Comment by ehsandeep** [comment]
Removed here https://github.com/projectdiscovery/nuclei-templates/commit/62f1da31fb05a7d37e932ed9f6cd3400bb70c725, thanks for confirming.
