### ISSUE TITLE
Multiple test

### ISSUE THREAD

**Issue by bsysop** [projectdiscovery/nuclei-templates#145]
Hi heros!

Want to thank you again for that amazing work!

Have a way to do multiple tests with just one request?

In this case, im sure multiple requests could be saved, with that a lot time too: https://github.com/projectdiscovery/nuclei-templates/pull/138/commits/fdf9402840cd227d3ec27716293afff84c69c532

**Comment by bauthard** [comment]
Hey @bsysop, 

Thanks a lot for your words, and that's definitely possible, you can add as many matches as you want for a single base request and here is working example https://github.com/projectdiscovery/nuclei-templates/blob/master/subdomain-takeover/detect-all-takeovers.yaml, you make one base request and checks against all the takeover signatures, surely we need to make it more clear by adding more templates as an example so you don't find it hard to be sure on this and we are working towards that, let me know this what you are looking for. 

Thanks!

**Comment by bsysop** [comment]
Wow, thats pretty exactly what i was speaking about.

I will ping Hakluke for that pull request.

Thanks @bauthard

**Comment by bauthard** [comment]
Hey @bsysop, 

Finally, this is done https://github.com/projectdiscovery/nuclei-templates/pull/138#issuecomment-650545758 💯

**Comment by bsysop** [comment]
Fantastic @bauthard 

Thank you very much!.
