### ISSUE TITLE
i am facing this problem while running nuclei 

### ISSUE THREAD

**Issue by RizwanSiDdiqu1** [projectdiscovery/nuclei-templates#1501]
![nuclei](https://user-images.githubusercontent.com/72160000/118801628-12f9ef80-b856-11eb-9a47-863cffe47c79.png)
**Nuclei version**

```
nuclei -version 
```

**Nuclei template version**

```
cat ~/.nuclei-config.json
```

**Describe the bug**

**Commands to reproduce**

```
nuclei -t xxx -target xxx
```

**Screenshots**

**Comment by savushkin-yauheni** [comment]
Hi
use `-tags fuzz` option, because `xff-403-bypass.yaml` has fuzz tag.

**Comment by wantedbhai** [comment]
it works
