### ISSUE TITLE
[false-positive] xxljob-default-login

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1512]
**Nuclei version**

```
v2.3.7
```

**Nuclei template version**

```
v8.2.9
```

**Template ID**

xxljob-default-login

**Commands to Reproduce**

```
nuclei -debug -t /home/kali/nuclei-templates/default-logins/xxljob/xxljob-default-login.yaml -u https://api.input.intl.miui.com
```

I think the matchers are not enough. It does give a false positive with any username/password.

**Comment by ehsandeep** [comment]
This should be fixed now, thanks for flagging @pdelteil
