### ISSUE TITLE
[false-positive] landingi-takeover

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#1629]
According to [this](https://github.com/EdOverflow/can-i-take-over-xyz/issues/117) there's no evidence is still possible to take over the subdomains. I just tried. The template should be moved to info category. 

**Nuclei version**

```
2.3.7
```

**Nuclei template version**

```
8.3.3
```

**Template ID**

landingi-takeover

**Commands to Reproduce**

```
nuclei -t landingi-takeover.yaml  -t https://casting.otodom.pl

```

**Comment by ehsandeep** [comment]
Thanks, updated at https://github.com/projectdiscovery/nuclei-templates/commit/ba0d092d4d8dfae79ba02c1259027c7422cc4b3e
