### ISSUE TITLE
[Bug] open-redirect.yaml - Fail because regex

### ISSUE THREAD

**Issue by bernardofsr** [projectdiscovery/nuclei-templates#1685]
**Nuclei version**
```
2.3.7
```

**Nuclei template version**

```
v8.3.4
```

**Describe the bug**

The regex fails to analyze request response.

**Example:**
```
[INF] [open-redirect] Dumped HTTP response for https://redacter.com@example.com

HTTP/1.1 200 OK
Connection: close
Accept-Ranges: bytes
Age: 233178
Cache-Control: max-age=604800
Content-Type: text/html; charset=UTF-8
Date: Fri, 11 Jun 2021 16:16:27 GMT
Etag: "3147526947"
Expires: Fri, 18 Jun 2021 16:16:27 GMT
Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
Server: ECS (dcb/7FA5)
Vary: Accept-Encoding
X-Cache: HIT

<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
...
````

The regex search for Location on the header but the headers doesn't contain Location.

**Commands to reproduce**
```
nuclei -t nuclei-templates/vulnerabilities/generic/open-redirect.yaml -target xxx
```

**Comment by ehsandeep** [comment]
@bernardofsr `https://redacter.com@example.com` will redirect to `example.com` is not open redirect, it is expected behavior.

For example:- https://facebook.com@example.com

**Comment by bernardofsr** [comment]
> @bernardofsr `https://redacter.com@example.com` will redirect to `example.com` is not open redirect, it is expected behavior.
> 
> For example:- https://facebook.com@example.com

But it's one of the payloads on open-redirect:
- '{{BaseURL}}@example.com'

**Comment by ehsandeep** [comment]
Thanks for pointing it out, Removed it here https://github.com/projectdiscovery/nuclei-templates/commit/962959f573ac26b1eb8b44b5d7c3847091a5c4f4

**Comment by bernardofsr** [comment]
> Thanks for pointing it out, Removed it here [962959f](https://github.com/projectdiscovery/nuclei-templates/commit/962959f573ac26b1eb8b44b5d7c3847091a5c4f4)

You can substitute to this: ////@example.com 
Works on some sites and I recently reported to DOD.

**Comment by ehsandeep** [comment]
sure, will do, closing this one as the issue is resolved.
