### ISSUE TITLE
[nuclei-template] enhancement to weblogic-t3-detect.yaml

### ISSUE THREAD

**Issue by milo2012** [projectdiscovery/nuclei-templates#1767]
**Template Details**
Hi
I suggest adding the extractors to the template "network/weblogic-t3-detect.yaml" to return the version of Weblogic since its in the response.

Before the change
[2021-06-24 17:26:21] [weblogic-t3-detect] [network] [info] 127.0.0.1:7001

After the change
[2021-06-24 17:26:07] [weblogic-t3-detect] [network] [info] 127.0.0.1:7001 [12.2.1.2.0]

Thank you for the awesome project 

Attached is the updated template
[weblogic-t3-detect.txt](https://github.com/projectdiscovery/nuclei-templates/files/6708054/weblogic-t3-detect.txt)

```yaml
id: weblogic-t3-detect

info:
  name: Detect Weblogic T3 Protocol
  author: F1tz
  severity: info
  description: Check T3 protocol status.
  tags: network,weblogic

network:
  - inputs:
      - data: "t3 12.2.1\nAS:255\nHL:19\nMS:10000000\nPU:t3://us-l-breens:7001\n\n"

    host:
      - "{{Hostname}}"
    read-size: 1024
    matchers:
      - type: word
        words:
          - "HELO"
    read-size: 1024
    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "HELO:(.*).false"

**Comment by ehsandeep** [comment]
thank you @milo2012, I've updated the template to include the extractor, thanks for sharing this.
