### ISSUE TITLE
Plastic SCM.

### ISSUE THREAD

**Issue by dhayalandeena10** [projectdiscovery/nuclei-templates#1848]
id: plastic SCM

info:
  name: plastic-scm
  author: DEENA!!!
  severity: critical
  tags: unauth-access

requests:
  - method: GET
    path:
      - "{{BaseURL}}/account/register"
      - "{{BaseURL}}/account"

    matchers-condition: or
    matchers:
      - type: word
        words:
          - "Register - Plastic SCM"
        part: body

      - type: word
        words:
          - "Log in - Plastic SCM"
        part: body

**Comment by dhayalandeena10** [comment]
id: plastic SCM

info:
  name: plastic-scm
  author: DEENA!!!
  severity: critical
  tags: unauth-access

requests:
  - method: GET
    path:
      - "{{BaseURL}}/account/register"
      - "{{BaseURL}}/account"

    matchers-condition: or
    matchers:
      - type: word
        words:
          - "Register - Plastic SCM"
        part: body

      - type: word
        words:
          - "Log in - Plastic SCM"
        part: body

**Comment by DhiyaneshGeek** [comment]
@dhayalandeena10 exposed-panels/plastic-scm-login.yaml can you add it to the existing one ?

**Comment by dhayalandeena10** [comment]
Login page isn't vulnerable , This is a misconfiguration which make this a bug.

I think this should not just be a exposed panel but a misconfiguration.

So I think it's better to add it as a new template.

Registration page is the one which is the root cause of this bug.

What are your thoughts?

**Comment by gy741** [comment]
Good catch @dhayalandeena10 

Can you add a reference?

I looked at your template and found the problem.

Ref : https://infosecwriteups.com/story-of-google-hall-of-fame-and-private-program-bounty-worth-53559a95c468

**Comment by dhayalandeena10** [comment]
can you please tell what's the problem?

I have tested it and it's working perfectly.

I don't know why some - are changed to some other symbols please change it to - so that the template will work for sure.

**Comment by dhayalandeena10** [comment]
`id: plastic SCM

info:
  name: plastic-scm
  author: DEENA!!!
  severity: critical
  tags: unauth-access

requests:
  - method: GET
    path:
      - "{{BaseURL}}/account/register"
      - "{{BaseURL}}/account"

    matchers-condition: or
    matchers:
      - type: word
        words:
          - "Register - Plastic SCM"
        part: body

      - type: word
        words:
          - "Log in - Plastic SCM"
        part: body`

**Comment by dhayalandeena10** [comment]
[plastic-scm.txt](https://github.com/projectdiscovery/nuclei-templates/files/6758084/plastic-scm.txt)

**Comment by dhayalandeena10** [comment]
now you can use it perfectly i think

**Comment by dhayalandeena10** [comment]
[plastic-scm.txt](https://github.com/projectdiscovery/nuclei-templates/files/6758087/plastic-scm.txt)

**Comment by dhayalandeena10** [comment]
now it should be perfect i think

**Comment by gy741** [comment]
Your template looks good. @dhayalandeena10

**Comment by gy741** [comment]
I also like the code below. :)

Changed some content.

```
id: plastic SCM

info:
  name: plastic-scm
  author: DEENA!!!
  severity: critical
  tags: unauth-access
  ref: https://infosecwriteups.com/story-of-google-hall-of-fame-and-private-program-bounty-worth-53559a95c468

requests:
  - method: GET
    path:
      - "{{BaseURL}}/account/register"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>Register - Plastic SCM</title>"
        part: body

      - type: status
        status:
          - 200
```

**Comment by dhayalandeena10** [comment]
sure..

**Comment by ehsandeep** [comment]
Thank you @dhayalandeena10 for sharing this template and @DhiyaneshGeek @gy741 for the review, I went ahead and updated the template to do registration and confirm the access to the configuration panel here - https://github.com/projectdiscovery/nuclei-templates/pull/1858
