### ISSUE TITLE
add Prototype Pollution template

### ISSUE THREAD

**Issue by Kalimon12** [projectdiscovery/nuclei-templates#1969]
https://github.com/KathanP19/protoscan

**Comment by geeknik** [comment]
There exists a basic headless template at https://github.com/projectdiscovery/nuclei-templates/blob/master/headless/prototype-pollution-check.yaml, however, a pull request to improve upon it would be happily accepted. 👍🏻

**Comment by toufik-airane** [comment]
Dear @Kalimon12,

As mention by @geeknik, do you think you can enhance the [existing Nuclei template](https://github.com/projectdiscovery/nuclei-templates/blob/master/headless/prototype-pollution-check.yaml)? 

Thank you.

**Comment by ehsandeep** [comment]
Closing as this is already supported.

**Comment by lemosnlmb** [comment]
> There exists a basic headless template at https://github.com/projectdiscovery/nuclei-templates/blob/master/headless/prototype-pollution-check.yaml, however, a pull request to improve upon it would be happily accepted. 👍🏻
> 
> For example:
> 
> ```
> ~$ nuclei -headless -t nuclei-templates/headless/prototype-pollution-check.yaml -target https://prototype-pollution.tomnomnom.repl.co/
> 
>                      __     _
>    ____  __  _______/ /__  (_)
>   / __ \/ / / / ___/ / _ \/ /
>  / / / / /_/ / /__/ /  __/ /
> /_/ /_/\__,_/\___/_/\___/_/   2.4.0
> 
>                 projectdiscovery.io
> 
> [INF] Your nuclei-templates are up to date: v8.4.0
> [INF] Using Nuclei Engine 2.4.0 (latest)
> [INF] Using Nuclei Templates 8.4.0 (latest)
> [INF] Using Interactsh Server https://interact.sh
> [INF] Templates loaded: 1 (New: 8)
> [2021-07-13 08:59:57] [prototype-pollution-check] [headless] [medium] https://prototype-pollution.tomnomnom.repl.co/ [[https://prototype-pollution.tomnomnom.repl.co/?__proto__%5Be32a5ec9c99%5D=ddcb362f1d60&__proto__.e32a5ec9c99=ddcb362f1d60]]
> ```

Doest seem to be working
![image](https://user-images.githubusercontent.com/80685782/177980717-6e50996c-49fd-4c3b-bcea-7625e63e4810.png)
