### ISSUE TITLE
[False Positive] file/keys/twitter-secret.yaml

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei-templates#2229]
git clone git clone https://github.com/twitter/chill /tmp/chill 
nuclei -t file/keys/twitter-secret.yaml -target /tmp/chill/

![2021-07-27_11-57](https://user-images.githubusercontent.com/466878/127196158-8191ff65-57c0-4d08-b073-aff1bd30a7fd.png)

no secrets found in that file.

**Comment by princechaddha** [comment]
Hi @geeknik, thanks for taking the time to create this issue and contributing to this project 🍻

Unfortunately, this issue has taken longer than usual. The issue is now resolved
