### ISSUE TITLE
[Feature] detectify templates

### ISSUE THREAD

**Issue by iburkhardt** [projectdiscovery/nuclei-templates#2248]
Hello everyone, everything good?

I'm leaving here with you the checklist that Detectify does, if anyone wants to create templates for them, the community thanks!

https://ghostbin.com/paste/O3gQX

**Comment by ehsandeep** [comment]
Hi @iburkhardt,

We appreciate your desire to assist this project's growth, but the information in the link isn't publicly available on the detectify website, thus we recommend that you erase the link's content if it is under your control.
