### ISSUE TITLE
Cisco ASA detection

### ISSUE THREAD

**Issue by 0x240x23elu** [projectdiscovery/nuclei-templates#2272]
Hi,
  Please add on cisco ASA detection 

"/+webvpn+/index.html"

it will allow redirect on login page where "/CACHE/sdesktop/install/start.htm" mention .

![image](https://user-images.githubusercontent.com/52744492/127652622-55053317-a6ff-4477-9a08-195fa624594a.png)

**Comment by geeknik** [comment]
Good morning. There exists a Cisco ASA detection template at https://github.com/projectdiscovery/nuclei-templates/blob/master/exposed-panels/cisco-asa-panel.yaml which detected the VPN instance at the host in your screenshot via `https://blackhole.ext.grab.com/+CSCOE+/logon.html`. 👍🏻

**Comment by 0x240x23elu** [comment]
Hi Cisco Now he have new security .
you can my script 
![image](https://user-images.githubusercontent.com/52744492/127841772-5c058cb0-8cd1-48d2-9bb1-46764c2daf18.png)


and this is your script
![image](https://user-images.githubusercontent.com/52744492/127841854-e1d9af5e-7d0f-43eb-ad52-7adef1039771.png)

your script not able to detect cisco ASA panel

**Comment by 0x240x23elu** [comment]
this is my script:
id: cisco-detect
info:
  name: cisco
  author: 0x240x23elu
  description: Cisco ASA detect
  severity: info
  tags: cisco,panel

requests:
  - method: GET
    path:
      - "{{BaseURL}}/+CSCOE+/logon.html"
      - "{{BaseURL}}"

    matchers:

      - type: word
        words:
          - "SSL VPN Service"
          - "/+CSCOE+/logon.html"
          - "webvpn"
        part: all

**Comment by ehsandeep** [comment]
Closing due to inactivlity.
