### ISSUE TITLE
impact of public front-page-misconfig.yaml ?

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei-templates#232]
Sorry for making this issue, but I can't understand on my own why this would be even accepted as low severity instead of being closed as N/A. it is always expecting a 247 size response, but it isn't disclosing anything sensitive/reportable.

Am I wrong here? Please point me in the right direction

I figured out that is possible to know the server which is running and something else. That's it right? Found it on VDPs only :(

**Comment by bauthard** [comment]
Hi @marcelo321, 

I've updated the template as Informative https://github.com/projectdiscovery/nuclei-templates/blob/master/security-misconfiguration/front-page-misconfig.yaml
