### ISSUE TITLE
Discuss ftp-default-credentials severity rating

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei-templates#2452]
The `network/ftp-default-creds.yaml` template is currently set at a severity rating of critical, which I don't really agree with, especially since the template is checking for the `anonymous` account and that is so very rarely a critical thing.  Unless we can test for the ability to upload a file to an anonymous FTP server ( still not sure that would be `critical` material ), maybe we split the templates into `ftp-default-credentials` which tests for actual accounts and a secondary `anonymous-ftp-enabled` which tests for the `anonymous` ftp account(s) and which has a `low` or `info` severity. Thoughts?

**Comment by pdelteil** [comment]
I agree

**Comment by ehsandeep** [comment]
@geeknik @pdelteil this is now updated in linked PR.
