### ISSUE TITLE
Error Parsing yaml file

### ISSUE THREAD

**Issue by melbadry9** [projectdiscovery/nuclei-templates#25]
https://github.com/projectdiscovery/nuclei-templates/blob/2e38d35226a203ba7c3833b96ee9ebe1ad021f41/vulnerabilities/discourse-xss.yaml#L11

- Fix

```
- "{{BaseURL}}/email/unsubscribed?email=test@gmail.com%27\"><svg/onload=alert(1337)>" 
```

**Comment by bauthard** [comment]
Thank you so much @melbadry9 for the review, I've updated the template.
