### ISSUE TITLE
Not able to verify template result(Webpack Sourcemap Disclosure #2512)

### ISSUE THREAD

**Issue by Vishnuraghav89** [projectdiscovery/nuclei-templates#2520]
Hi Sandeep and team,

I got few result using below template but unfortunately not able to validate the results.
Could you please let us know how to verify these result as I'm not able to understand template request.

```**Webpack Sourcemap Disclosure #2512**```

```javascript 
id: webpack-sourcemap-disclosure

info:
  name: Webpack Sourcemap Disclosure
  author: dhiyaneshDk
  severity: medium
  tags: exposure,files

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{RootURL}}/{{Path}}/{{map}}.js.map"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "application/octet-stream"
        part: header

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        internal: true
        name: map
        group: 1
        regex:
          - "sourceMappingURL=([a-z0-9.]+).js.map"
```

**Comment by DhiyaneshGeek** [comment]
@Vishnuraghav89  it's still not completed yet , this template will work only on the next nuclei release :)

**Comment by ehsandeep** [comment]
@Vishnuraghav89 As @DhiyaneshGeek mentioned and indicated in the PR, this is WIP template and blocked as it will not with the current version of nuclei, closing this issue, this can be tracked at https://github.com/projectdiscovery/nuclei-templates/pull/2512

**Comment by Vishnuraghav89** [comment]
Hi Projectdiscovery/Nuclei-Templates,

Could you please give us any idea that when we can expect newer version of
nuclei???

Thanks & Regards,
Vishnu Raghav

**Comment by ehsandeep** [comment]
It will be out this week.
