### ISSUE TITLE
Updating guide document

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/nuclei-templates#26]
Document guide can be improved by adding more examples of a few cases like 

- [x] Adding multiple cookies
- [x]  POST body examples 

Guide link:- https://github.com/projectdiscovery/nuclei-templates/blob/master/GUIDE.md

**Comment by toufik-airane** [comment]
- [X] Use of Binary matcher (https://github.com/projectdiscovery/nuclei/pull/31)

**Comment by bauthard** [comment]
- [ ] Use of DNS request @Mzack9999
