### ISSUE TITLE
[Bug]  airflow-default-credentials.yaml

### ISSUE THREAD

**Issue by blablareportblabla** [projectdiscovery/nuclei-templates#2620]
Hi team

Today i launched last version of airflow. And noticed that login paths are differ from path in `airflow-default-credentials.yaml` template.

https://github.com/projectdiscovery/nuclei-templates/blob/67766f381a6935f6754d013b69484b54c696a041/default-logins/apache/airflow-default-credentials.yaml#L18

Last version:
<img width="727" alt="Screenshot 2021-09-09 at 15 33 21" src="https://user-images.githubusercontent.com/77134139/132686397-9a613b54-90b6-4a9d-8a78-7bcef7305136.png">

And you may notice:

https://github.com/projectdiscovery/nuclei-templates/blob/67766f381a6935f6754d013b69484b54c696a041/default-logins/apache/airflow-default-credentials.yaml#L24

`_csrf_token` changed to  `csrf_token`

Thanks.

**Comment by c2c-pages-reports** [comment]
And we should pass `session` cookie, otherwise it raise 400 error.

**Comment by c2c-pages-reports** [comment]
https://github.com/projectdiscovery/nuclei-templates/blob/master/default-logins/apache/apache-superset-default-credentials.yaml

superset and airflow have the same auth logic. In superset template everything is okay.

**Comment by c2c-pages-reports** [comment]
And finally

https://github.com/projectdiscovery/nuclei-templates/blob/8c1c7787afc0b50b9cfa2891126a6c8e404dd269/exposed-panels/airflow-panel.yaml

I think should be:

```
id: apache-airflow

info:
  name: Airflow login
  author: savik

requests:
  - method: GET
    path:
      - "{{RootURL}}/login/"
    matchers:
      - type: word
        words:
          - "Sign In - Airflow"
        part: body
```

**Comment by c2c-pages-reports** [comment]
Hm. but i found some hosts by your template too. So different versions.. What should we do in that kind of situation ?

**Comment by ehsandeep** [comment]
@c2c-pages-reports we can have multiple templates based on versions as they are unique.

**Comment by ehsandeep** [comment]
> Today I launched the last version of airflow and noticed that login paths are differ from path

@c2c-pages-reports do you have any reference for a new login path for airflow or ways to set up the same?

**Comment by ehsandeep** [comment]
This should be fixed with https://github.com/projectdiscovery/nuclei-templates/pull/3217/commits/b05e5668be20c0a4eeba2f443693700a16902505
