### ISSUE TITLE
error when trying to run all template

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/nuclei-templates#265]
i was mentioned you early and one of guys told me that i could run all template at once against list of urls.
But i tried so many times.
the case is when i run nuclei with list contains only subdomains without http(s) not working.

[https://imgur.com/MVq5Waa](url)

so i tried run another tool to probe then not working either !
BUT if i run it directly to feed nuclei with stdin directly like
```cat listofurl | httprobe | nuclei -t ~/tools/nuclei-templates/ -v -o nuclei -c 50 -timeout 3```
it would work with some template not all

**Comment by bauthard** [comment]
Hey @Sy3Omda, 

Can you update the link of the screenshot or just upload it again?

**Comment by Sy3Omda** [comment]
https://imgur.com/MVq5Waa

**Comment by Ice3man543** [comment]
@Sy3Omda Thanks for the issue. You're using a very outdated version of the tool. Kindly update the tool and try again. Also, you should not run all the templates at once since there are multiple types of templates supporting multiple inputs. Nuclei is best used in a targeted way to say find all panels of certain software of fingerprinting sites. Closing this issue since this is not an issue with the tool itself.

**Comment by Sy3Omda** [comment]
PS
referring to this tweet which by nuclei which conform i can run it at once .

![image](https://user-images.githubusercontent.com/48482029/88524822-2489b680-cffa-11ea-9921-260bf0908198.png)

So do you mean it should not (as best practice) OR must not !

**Comment by bauthard** [comment]
Hi @Sy3Omda, 

Technically you can run, but as suggested in the tweet we do not advise without context/target awareness, we always imagined to use nuclei as a tool which always gives you accurate results and get used likewise, but if you don't care much about running based on the context or going after particular issue, feel free to use so, in that case, it's very possible that few templates will not run as each template is created for a different issue few of them accept additional file/path input which you need to update it on your system, again in sort, you can run all at once, but it is something we do not advise :)

**Comment by Sy3Omda** [comment]
@Mad-robot unfortunately I do not want to move because once and while I update the the repo folder itself for running up to date temples so i could refer this solution which I just published
```https://twitter.com/Sy3Omda/status/1292846177059311617?s=19```
