### ISSUE TITLE
Creating new template

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/nuclei-templates#267]
Hi,
i was trying to create new template with multiple headers and i have read the wiki but could not found what i miss.

referring to this template vulnerabilities/x-forwarded-host-injection.yaml

**Comment by bauthard** [comment]
Can you please be more specific about what problem you are facing? about creating new templates with custom header, there are many examples in the project, and here is a good one https://github.com/projectdiscovery/nuclei-templates/blob/77e5d112be1e3a2a6ce659d525ed5aedf553ee5b/files/server-status-localhost.yaml, you can simply copy-paste them and add/update your header/path or whatever you need. 

Let me know if it helps, if not please detail the issue.

**Comment by Sy3Omda** [comment]
not working .
the thing is the whole url is redirected to new one which is configured in header!

**Comment by bauthard** [comment]
Hey, if you want us to help you, you need to add more details, which includes 

- CMD you used to run the template. 
- Nuclei version (nuclei -version)
- Error screenshot

**Comment by Sy3Omda** [comment]
```
id: server-status-localhost

info:
  name: Server Status Disclosure
  author: bauthard
  severity: low

requests:
  - method: GET
    # Example of sending some headers to the servers
    headers:
      X-Forwarded-Host: "omda.com"
      X-Forwarded-Scheme: "nothttps"
    path:
      - "{{BaseURL}}/"
    matchers:
      - type: word
        words:
          - "omda"
```
this is the full template .
i`m trying to pass multiple headers in the same time.
the result as i am testing in burp suite is the link will be redirect to the ```X-Forwarded-Host: ``` value and it works well in burp

**Comment by bauthard** [comment]
Hey @Sy3Omda, 

This is working as expected, not sure I get your problem, if you have something to share which you cant' here, feel free to DM us on discord. 

![image](https://user-images.githubusercontent.com/8293321/88574793-7bc27200-d060-11ea-966e-a24c8f02c0b6.png)

**Comment by bauthard** [comment]
Closing as this is working expected.
