### ISSUE TITLE
False positives for Google Cloud key template

### ISSUE THREAD

**Issue by karelorigin** [projectdiscovery/nuclei-templates#27]
Apparently Google Maps uses the same format for API keys as Google Cloud, which means that the template gives false positives when encountering a Maps key. 

I don't think there's a way to fix this, unless the Google Cloud keys are embedded in a way that's distinguishable from Maps. However, that's not very likely since they're probably not meant to be public in the first place.

**Comment by Ice3man543** [comment]
So the only way this can be tackled is by adding another condition type that matches negatively, i.e, if a negative matcher also matches that means the key is invalid. This would be like a second layer filter on top of matchers.

**Comment by bauthard** [comment]
Hi @karelorigin, 

Thanks for pointing this out, I would not say this as `False positives` as this is working as expected and defined in the template, what is not right is naming it as `Google Cloud API Key` which is not the case most of the time, as the same key can be used with multiple services of the Google cloud platform, I've updated the name of the template as `Google API key` to set the right expectation for the users and later on it's a manual task to identify or check the permission of the key.
