### ISSUE TITLE
[false-positive] php-warning

### ISSUE THREAD

**Issue by hhrithik** [projectdiscovery/nuclei-templates#2705]
**Nuclei version**

```
v2.3.7
```

Hi team,

I have found that PHP-warning teamplate is giving a lot of false-positive results.

![nuc](https://user-images.githubusercontent.com/53258131/133833095-4cd275b9-3600-4ef5-82c6-538234b10315.png)
 

Regards,
Hrithik

**Comment by geeknik** [comment]
Fixed by #2706 👍🏻
