### ISSUE TITLE
HTTP Header Usage Question

### ISSUE THREAD

**Issue by gy741** [projectdiscovery/nuclei-templates#276]
Hello,

The ```raw requests``` method allows you to select the HTTP version(HTTP/1.1, HTTP/2.0).

Is there a way to use the "raw requests'" approach without using it?

I want to send the below request in "HTTP/2.0" way.

```
id: test

info:
  name: test
  author: karas
  severity: low

requests:
  - method: GET
    headers:
      User-Agent: karas
    path:
      - "{{BaseURL}}/karas/"
    matchers:
      - type: word
        words:
          - "<title>karas</title>"
```

**Comment by bauthard** [comment]
Hi @gy741, 

Yes, that's expected, we introduced `RAW` request to have full control over the request, so that's possible with RAW request only. 

other way is simple and handy to use, but with few limitations like this, let me know if you have any more questions/feedback.

**Comment by gy741** [comment]
Hi @bauthard 

Thank you for your quick answer!

I'll open this up if I have any more questions.

Have a nice day.
