### ISSUE TITLE
tomcat-manager-bruteforce.yaml High false positive rate

### ISSUE THREAD

**Issue by un-fmunozs** [projectdiscovery/nuclei-templates#278]
This template seems to be checkin only for HTTP response and gives a high false positive rate IMHO

https://github.com/projectdiscovery/nuclei-templates/blob/master/brute-force/tomcat-manager-bruteforce.yaml

Maybe we can add the matcher for Apache Tomcat that is present on  files/public-tomcat-instance.yaml

    matchers:
      - type: word
        words:
          - Apache Tomcat

```
buggie@ubuntu-s-1vcpu-1gb-tor1-01:~$ echo https://mobile.twitter.com | ./go/bin/nuclei -t nuclei-templates/brute-force/tomcat-manager-bruteforce.yaml

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] [tomcat-manager-bruteforce] Loaded template tomcat-manager-bruteforce-fuzzing (@pdteam) [high]
[tomcat-manager-bruteforce] [http] https://mobile.twitter.com/manager/html [password=admin,username=admin]
[tomcat-manager-bruteforce] [http] https://mobile.twitter.com/manager/html [password=guest,username=admin]
[tomcat-manager-bruteforce] [http] https://mobile.twitter.com/manager/html [password=password,username=admin]
[tomcat-manager-bruteforce] [http] https://mobile.twitter.com/manager/html [password=test,username=admin]
[tomcat-manager-bruteforce] [http] https://mobile.twitter.com/manager/html [username=admin,password=12345]
[tomcat-manager-bruteforce] [http] https://mobile.twitter.com/manager/html [password=123456,username=admin]
[tomcat-manager-bruteforce] [http] https://mobile.twitter.com/manager/html
```

Regards

**Comment by bauthard** [comment]
Hi @un-fmunozs, 

Thank you for creating this issue, this is where running them all doesn’t work well, this template is specifically created to run against hosts running tomcat manager panel, not in general for all targets, but as you said it's possible to patch this to avoid f/p when someone running all the templates at once, I will update this.

**Comment by bauthard** [comment]
This is updated at https://github.com/projectdiscovery/nuclei-templates/releases, thanks again for pointing this out @un-fmunozs
