### ISSUE TITLE
[false-positive] /vulnerabilities/generic/open-redirect.yaml 

### ISSUE THREAD

**Issue by osamahamad** [projectdiscovery/nuclei-templates#2821]
**Nuclei version**

```
2.5.2
```

**Nuclei template version**

```
8.5.6
```

The regex in /vulnerabilities/generic/open-redirect.yaml 

```(?m)^(?:Location\s*?:\s*?)(?:https?://|//)?(?:[a-zA-Z0-9\-_\.@]*)example\.com.*$```
related to open redirect vulnerabilities detection may introduce false positive as can be seen in :

https://regex101.com/r/spLaiz/1

![image](https://user-images.githubusercontent.com/59566963/132168173-881f4b18-b85b-4b2b-8859-a1652c233a77.png)

as we can see it will be true if example.com found in path + subdomain section in some situations.

Using the following regex might be a better solution to avoid false positives; 
```(?m)^(?:Location\s*?:\s*?)(?:https?://|//)?(?:[a-zA-Z0-9\-_\.@]*)example\.com?(?:[a-zA-Z0-9\/@]*)*$```
![image](https://user-images.githubusercontent.com/59566963/132171152-3402d036-25e9-4223-b0d8-5c9347070df2.png)

https://regex101.com/r/b7cbd2/2

**Commands to Reproduce**

```
nuclei -u http://lib.store.yahoo.com/ -t vulnerabilities/generic/open-redirect.yaml
```

```
[open-redirect] [http] [low] http://lib.store.yahoo.com/example.com/
```

**Comment by geeknik** [comment]
Thank you for the report, we are having a discussion about a fix for the open redirect regex over here @ #2776 👍🏻
