### ISSUE TITLE
[Bug] with the api-iterable template

### ISSUE THREAD

**Issue by thezakman** [projectdiscovery/nuclei-templates#2843]
**Nuclei version**

```
nuclei -version 
```

**Nuclei template version**

```
api-iterable template
```

**Describe the bug**
I think this is broken right now, right? It should try to validade the API KEY, but it's only printing the request path without the key.

[2021-10-06 02:45:42] [api-iterable] [http] [info] https://api.iterable.com/api/export/data.json?dataTypeName=emailSend&range=Today&onlyFields=List.empty

**Commands to reproduce**

```
nuclei -t xxx -target xxx
```

**Screenshots**

**Comment by ehsandeep** [comment]
Closed with https://github.com/projectdiscovery/nuclei-templates/commit/10ecdc806a453f925710374f4d704bff354da601
