### ISSUE TITLE
Remove endpoint from spring actuator template

### ISSUE THREAD

**Issue by mzfr** [projectdiscovery/nuclei-templates#292]
In the `springboot-actuators` template there are various endpoints and in those endpoints, there is `/health` and `/info` but the issue is these endpoints are not sensitive and shouldn't be checked.

For reference: https://www.amitph.com/how-to-secure-spring-boot-actuator-endpoints/

It would be nice to remove them from the template.

**Comment by bauthard** [comment]
Done at https://github.com/projectdiscovery/nuclei-templates/commit/f0512b88d367a04b39b553d668e5192c045cd971
