### ISSUE TITLE
http-username-password generate false positive

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/nuclei-templates#305]
this template ```tokens/http-username-password.yaml```
generate a lot of false positive results

**Comment by bauthard** [comment]
Can you share examples including nuclei and template version?

**Comment by un-fmunozs** [comment]
Try on this http://apartamentoscolombia.com/test/

URLs that include ports are flagged as password. I'd remove the : from the last metachar, since a password on a url must always include the @

**Comment by un-fmunozs** [comment]
Before:
```
[http-username-password] [http] http://apartamentoscolombia.com/test/ [https://user:,https://user@,https://localhost:,https://something:]
```
localhost and something should have not been identified as password

After change:
```
[http-username-password] [http] http://apartamentoscolombia.com/test/ [https://user:pass@,https://user@,https://user:safepassword123_S!@]
```

**Comment by bauthard** [comment]
Thank you for sharing example and updating the regex @un-fmunozs

**Comment by Sy3Omda** [comment]
```[http-username-password] [http] http://web.archive.org/ [https://5588e3adb3e545248e893d6f2fc41ba2@]```

**Comment by bauthard** [comment]
that's valid match @Sy3Omda as per the regex, and it's possible you will get a result like this as valid cases follow the same pattern, as template suggests, it's generic check.
