### ISSUE TITLE
Freshdesk takeover is not vulnerable now

### ISSUE THREAD

**Issue by savushkin-yauheni** [projectdiscovery/nuclei-templates#3116]
Hi team

https://github.com/projectdiscovery/nuclei-templates/blob/f6f32ae344ffe57fbbfd926afff87d2c44987970/takeovers/freshdesk-takeover.yaml

Freshdesk changed their CNAME logic and it's not possible to takeover a domain now.

https://github.com/EdOverflow/can-i-take-over-xyz
https://support.freshdesk.com/support/solutions/articles/37590-using-a-vanity-support-url-and-pointing-the-cname

Thanks

**Comment by ImNightmaree** [comment]
![image](https://user-images.githubusercontent.com/22177675/141700382-7b9c52f0-283d-46b8-afe4-b34a80349fc0.png)

Appears confirmed...

**Comment by ImNightmaree** [comment]
Thanks for flagging @savushkin-yauheni - the above PR will remove the template.
