### ISSUE TITLE
Client.Timeout exits the template (Question)

### ISSUE THREAD

**Issue by Ncoder2** [projectdiscovery/nuclei-templates#320]
Hi, i am trying to create a new template with the following requests:

  ` - method: GET
    path:
      - "{{BaseURL}}:8089/services"
      - "{{BaseURL}}:8000/services"
    matchers:
      - type: status
        status:
          - 200`
You can see this involves a port number. 

When i run this template, ideally i expect the code to run both the paths, even if one of it fails. But what happens is when the first path fails due to a client.timeout error, the program quits without executing the second path. 

**[WRN] Could not execute step: could not handle http request: Could not do request: GET https://example.com:8089/services giving up after 2 attempts: Get "https://example.com:8089/services": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[INF] No results found. Happy hacking!**

Is there some configuration i need to change in my template or enable any option to have the second path executed ? Or is this how the application works ?

**Comment by bauthard** [comment]
Hi @Ncoder2, 

Thanks for reporting this, this known issue and we are tracking it here https://github.com/projectdiscovery/nuclei/issues/232, will be fixed soon in next update, closing this, as we already have an open ticket for this.
