### ISSUE TITLE
[FTL] Could not run nuclei: no valid templates were found

### ISSUE THREAD

**Issue by meetgyn** [projectdiscovery/nuclei-templates#3310]
[FTL] Could not run nuclei: no valid templates were found
  in nuclei -t /root/nuclei-templates/vulnerabilities/grafana/grafana-file-read.yaml

**Comment by ehsandeep** [comment]
@meetgyn  - https://github.com/projectdiscovery/nuclei/issues/1349

**Comment by abd-4fg** [comment]
@ehsandeep So i used -dast flag and the fuzzing template started to run , Is that the main cause of this problem ?

![image](https://github.com/projectdiscovery/nuclei-templates/assets/81921899/23cb237b-ab7e-4a52-96ba-a0189c5b21e1)
