### ISSUE TITLE
About BUG

### ISSUE THREAD

**Issue by sinlee1** [projectdiscovery/nuclei-templates#342]
use the following commands to perform operations:
`cat output.txt|httpx -silent|nuclei -t nuclei-templates/ -l output.txt`

Error prompt:
`[ERR] Could not parse file '/var/local/projectdiscovery/nuclei-templates/.pre-commit-config.yaml': No requests defined`

How to solve this error?

**Comment by bauthard** [comment]
Hey, this is not a bug or issue, nuclei accept templates to run, `.pre-commit-config.yaml` is not a template file but configuration file for this project, instead of using `nuclei-templates/`, you can define specific paths you want to run, for example `-t dns/ -t cves/ -t files/` to avoid this.

**Comment by sinlee1** [comment]
But I have used nuclei -t nuclei-templates/, why is it still reporting an error?

**Comment by bauthard** [comment]
Hey, as said above, `.pre-commit-config.yaml` is not a valid template and not meant to be used with nuclei, you can remove it locally if you want to ignore the error.

**Comment by sinlee1** [comment]
I can understand that the really useful things are in the cves directory, and the others are not very useful, right?

**Comment by sinlee1** [comment]
The problem has been solved, I have deleted this local configuration file~

**Comment by dwisiswant0** [comment]
Do **NOT** run templates via `nuclei-templates/` directory recursively.

**Comment by sinlee1** [comment]
> Do **NOT** run templates via `nuclei-templates/` directory recursively.

Why？Do you directly execute the cvs directory? There are too few POCs in this directory

**Comment by sinlee1** [comment]
@dwisiswant0 What is the correct way?

**Comment by dwisiswant0** [comment]
This is the proper way, @sinlee1:

```
> nuclei -l file -t cves/ -t files/ -t workflows/
```

**Comment by sinlee1** [comment]
@dwisiswant0 Thx

**Comment by wxz896446511** [comment]
![image](https://user-images.githubusercontent.com/43559734/145748288-e68171d6-73ca-49bd-8e8f-d6dd6ed5173c.png)

**Comment by wuha0926** [comment]
Could not run nuclei: no valid templates were found
