### ISSUE TITLE
Duplicate template (Linkerd SSRF)

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei-templates#3459]
Hi, I think I found a duplicate template

https://github.com/projectdiscovery/nuclei-templates/blob/master/vulnerabilities/linkerd/linkerd-ssrf.yaml
https://github.com/projectdiscovery/nuclei-templates/blob/master/misconfiguration/linkerd-ssrf-detect.yaml

**Comment by ehsandeep** [comment]
@daffainfo, both are separate, one for service detection and one for SSRF issue.

**Comment by daffainfo** [comment]
Oh, okay i thought they are the same template because they have the same request
