### ISSUE TITLE
Absence of "max-size" parameter on "keys" templates result False Negatives

### ISSUE THREAD

**Issue by secureITmania** [projectdiscovery/nuclei-templates#3477]
In the android apk decompile folder, some file sizes are beyond 5MB, especially the "**index.android.bundle**". Due to the absence of the "**max-size**" parameter in the templates **nuclei is failed** to identify the vulnerability. 

Is there is any nuclei configuration to change the default "max-size" with argument or "config.yaml" instead of modifying 
the templates? 

![nuclei issue](https://user-images.githubusercontent.com/67820809/148053827-3e40e720-0a24-4a00-bad5-7055e9f2f69f.png)

**Comment by ehsandeep** [comment]
@secureITmania thanks for pointing this out, currently we can only define default size in the template itself.

**Comment by ehsandeep** [comment]
@timkoopmans this is now addressed at engine level, by increasing default file size to read from 5 MB to 1GB - https://github.com/projectdiscovery/nuclei/pull/1577, changes will refect after next release of nuclei

**Comment by ehsandeep** [comment]
should be addressed with the latest release of nuclei.
