### ISSUE TITLE
Status code causing false positive 

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/nuclei-templates#351]
https://github.com/projectdiscovery/nuclei-templates/blob/037e24adf17c579230173d47a9a6b88c70ef597b/files/zip-backup-files.yaml#L52

Hi, 
I think status code is causing false positive results because a lot of sites has some endpoints are accepting any input and gives you a 200 as s response code

**Comment by bauthard** [comment]
@Sy3Omda this template has `matchers-condition: and`, so it's not only the status code getting checked, do you have any example to share?

**Comment by Sy3Omda** [comment]
> @Sy3Omda this template has `matchers-condition: and`, so it's not only the status code getting checked, do you have any example to share?

yup could u dm me on twitter for this

**Comment by bauthard** [comment]
Closing as this is not reproducible.
