### ISSUE TITLE
network-Incomplete data flow

### ISSUE THREAD

**Issue by yuzhe-Mortal** [projectdiscovery/nuclei-templates#3517]
**ftp-default-credentials.yaml**
![image](https://user-images.githubusercontent.com/52953085/148889951-fb6dc16b-ac9d-438a-9344-0cfb81217be0.png)

**Comment by ehsandeep** [comment]
@yuzhe-Mortal as per the screenshot, you running `ftp-weak-credentials`, and `ftp-default-credentials` mentioned in the issue, could you please confirm the template and add a little more detail about the issue so we review it correctly?

**Comment by pussycat0x** [comment]
Hello, @yuzhe-Mortal. We have successfully tested the `ftp-weak-credentials.yaml` file, and it is functioning properly. Could you please provide additional details regarding the issue you are experiencing?

**Comment by pussycat0x** [comment]
Hello @yuzhe-Mortal , I am closing this issue now. If you are still experiencing the same problem, please feel free to reopen it. 🚀 .
