### ISSUE TITLE
Could not run nuclei: no valid templates were found on FUZZING Directory

### ISSUE THREAD

**Issue by sakyb7** [projectdiscovery/nuclei-templates#3548]
Hi Team,
I dont know why `nuclei-templates/fuzzing/` or `nuclei-templates/fuzzing/*` is giving `Could not run nuclei: no valid templates were found`
I also tried to run single template inside the dir still wont work... `nuclei-templates/fuzzing/cache-poisoning-fuzz.yaml`

Screenshot below:
![image](https://user-images.githubusercontent.com/42310984/149762465-663768e5-84d1-4f1d-8c0a-889cab4ff439.png)

**Comment by ehsandeep** [comment]
See the discussion at https://github.com/projectdiscovery/nuclei/discussions/1337
