### ISSUE TITLE
False Positives with crlf-injection.yaml Template

### ISSUE THREAD

**Issue by attacker007** [projectdiscovery/nuclei-templates#356]
Hi, 

I am getting false positive for the template 

```
crlf-injection.yaml

```

I was checking one target which fixed the issue with "400" Status code - Bad Request 
but this tool still showing that its vulnerable.

**Comment by bauthard** [comment]
Hey @attacker007,  

You can reach out to us on discord with target details for the review, otherwise, we have no information to review this issue.

**Comment by attacker007** [comment]
Hi @bauthard  Cant disclose target. Don't you think that if System responds with 400 Bad Status Code , then this template should not give response as "Vulnerable" to CRLF ? 

Regards,

**Comment by bauthard** [comment]
Not really, if the headers being updated, its doesn't matter what's the status code, and if you see the template it checks for response header, not the status code, anyway, I will keep this open and once we can reproduce this from our side, we will fix it or feel free to submit a PR if you know how to fix this.

**Comment by bauthard** [comment]
Closing due to lack of info!

**Comment by bug-te8t** [comment]
Same I am also getting false positive
