### ISSUE TITLE
Could not run nuclei: no valid templates were found

### ISSUE THREAD

**Issue by monixxxx** [projectdiscovery/nuclei-templates#3601]
[FTL] Could not run nuclei: no valid templates were found
in nuclei -t /root/nuclei-templates/technologies/graphql-detect.yaml

**Comment by ehsandeep** [comment]
@monixxxx you can run it with `nuclei -t technologies/graphql-detect.yaml -itags fuzz`, see https://github.com/projectdiscovery/nuclei/discussions/1337#discussioncomment-1755851 for more details.
