### ISSUE TITLE
Make severity level "unknown"

### ISSUE THREAD

**Issue by Ilyassov** [projectdiscovery/nuclei-templates#3713]
Add severity level unknown.

Sometimes when you write template you dont actually know, which severity level your finding will be.

For example if u use nuclei as a fuzzer. The results of fuzzing often have an unknown level of severity, but there is no such severity level.

**Comment by ehsandeep** [comment]
@Ilyassov thanks, this will require change in nuclei engine, we are alreday tracking this issue here - https://github.com/projectdiscovery/nuclei/issues/1190

**Comment by ehsandeep** [comment]
@Ilyassov this is now supported with latest version of nuclei
