### ISSUE TITLE
False Negative Open redirect

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#3726]
### Nuclei Version:

[INF] Using Nuclei Engine 2.6.0 (latest)
[INF] Using Nuclei Templates 8.8.5 (latest)

### Template file:

vulnerabilities/generic/open-redirect.yaml

### Command to reproduce:

nuclei -u https://www.free.fr -t vulnerabilities/generic/open-redirect.yaml -stats

Here is the open redirect: https://www.free.fr//example.com/

### HTTP GET response is 200

echo https://www.free.fr//example.com/ | httpx -debug-resp

[INF] Dumped HTTP response for https://www.free.fr:443//example.com/

HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html
Date: Fri, 18 Feb 2022 15:11:38 GMT
Etag: W/"620e6c43-3d01"
Last-Modified: Thu, 17 Feb 2022 15:39:47 GMT
Server: nginx/1.14.2
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

**Comment by everett-protocol** [comment]
Resolving this issue can help us to find open redirect on bug bounty domain.

**Comment by ehsandeep** [comment]
@2pifinance thanks for flagging this, looks like the redirect is happening at run time which can be only detected with headless template.

**Comment by akincibor** [comment]
Technically there is no redirection. But redirection happen.

I tried this, but doesn't work:

```
id: headless-open-redirect

info:
  name: Headless Open URL redirect detection
  author: akincibor
  severity: low
  description: A user-controlled input redirects users to an external website.
  tags: redirect,generic

requests:
  - method: GET
    path:
      - '{{BaseURL}}//{{interactsh-url}}/'
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the HTTP Interaction
        words:
          - "http"
```
