### ISSUE TITLE
nginx Server detection @pdnuclei   template 

### ISSUE THREAD

**Issue by 0x240x23elu** [projectdiscovery/nuclei-templates#374]
https://twitter.com/0x240x23elu/status/1300329398982201349

id: nginx-Detect

info:
  name: Detect nginx
  author: 0x240x23elu
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        words:
          - "nginx"
        condition: and
        part: header
      - type: word
        words:
          - "nginx"
        part: body

**Comment by bauthard** [comment]
Thank you for submitting this template @0x240x23elu, this is already part of [tech-detect](https://github.com/projectdiscovery/nuclei-templates/blob/a1432f7cdeb7070843a25a1a273d354df7a25edf/technologies/tech-detect.yaml) template, as such closing this issue.
