### ISSUE TITLE
[nuclei-template] Basic SQL injection detection Nuclei Template

### ISSUE THREAD

**Issue by 0x240x23elu** [projectdiscovery/nuclei-templates#375]
https://twitter.com/0x240x23elu/status/1300327035575783424
https://gist.githubusercontent.com/0x240x23elu/1cf0830ecc73656b79e011b471e8c167/raw/1ccd6dff3bc7fc91d31bc7eb0ba2808b1ef86e28/sqli2.yaml

**Comment by bauthard** [comment]
Thank you @0x240x23elu, this is a nice template for error based SQL detection, and useful for specific use case, as of now we are holding this and will add into the template after next release of nuclei, which will have a feature to block running few templates on default, till that time, we are keeping this open.

**Comment by ehsandeep** [comment]
Closing this, as [error-based-sql-injection](https://github.com/projectdiscovery/nuclei-templates/blob/master/vulnerabilities/generic/error-based-sql-injection.yaml) includes all the matchers already.

**Comment by skalvin** [comment]
is there a working template to detect sql injection timebase?

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>mvthnA

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>EonOC3

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>GXegIa

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Eg5tBQ

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>eM48aa

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>IwD6sT

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>iL43og

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>brzNhj

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>esvVsl

**Comment by dody200411** [comment]
'"></script><div rNnTRbt=roann>jpwpSG

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>BrIUvy

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>67o9nt

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>RbdZRs
