### ISSUE TITLE
log4j template list

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei-templates#3817]
- [x] Apache Struts2
- [x] VMWare Center
- [x] Apache Solr Server
- [x] VMWare Horizon
- [x] VMWare Vrealize
- [x] Unifi
- [x] Apereo CAS
- [x] Jamf Pro
- [x] Code42
- [x] Springboot
- [x] OpenNMS
- [x] VMware Site Recovery Manager
- [x] ElasticSearch
- [x] GoAnyWhere
- [x] VMware NXS-T
- [x] Metabase
- [x] Grails
- [x] Cisco vManage
- [x] Cisco Unified Communications
- [x] Graylog
- [x] Citrix XenMobile Server

Todo:

- [x] Okta IDP
- [ ] Tableau
- [x] Logstash
- [x] Cisco BroadWorks
- [x] Cisco WebEx
- [x] ManageEngine Desktop Central
- [x] Symantec SEPM
- [x] Jitsi Meet
- [x] Citrix XenApp
- [x] Splunk Enterprise
- [x] FortiPortal
- [x] Sonicwall NSM
- [x] Pega
- [x] Papercut
- [x] F-Secure – Policy Manager
- [x] FlexNet
- [x] OpenShift

**Comment by akincibor** [comment]
oracle weblogic server could be added
