### ISSUE TITLE
False Negative - Kibana Panel Detection 

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#3838]
### Nuclei Version:
- Nuclei Engine 2.5.7-dev (development)
- Nuclei Templates 8.8.7
### Template file:
exposed-panels/kibana-panel.yaml
### Command to reproduce:
- Some versions will have a different title: <title>Kibana Login</title>
- Since version v7.8.0, title is now: <title>Elastic</title> https://github.com/elastic/kibana/blob/v7.8.0/src/core/server/rendering/views/template.tsx
- Some hosts redirect to a different non standard path. Adding a request to BaseURL and redirects: true, fixed that.
- The header Kbn-Name is not always present and sometimes is all lower case

1. Test against any kibana version >= v7.8.0
``curl -s http://$HOST:$PORT/app/kibana | grep '<title>'``
``.....<title>Elastic</title>``
2. nuclei -debug -t exposed-panels/kibana-panel.yaml http://kibana_host:port

Docker compose files different kibana versions
https://github.com/c-sh0/docker_files/tree/main/elastic

Patched version
https://github.com/c-sh0/nuclei_templates/blob/main/kibana/kibana-panel.yaml

**Comment by princechaddha** [comment]
Hello @c-sh0, Thank you for sharing this issue in detail. I have made some changes in the above PR. Let me know if it looks good to you 🚀

**Comment by c-sh0** [comment]
Quick search from shodan. The template does not detect Kibaba versions with:
* <title>Kibana Login</title>
* Does not have a Kbn-Name header

**Comment by princechaddha** [comment]
Thanks, @c-sh0 for verifying the updated template. I have added `<title>Kibana Login</title>` and the `matchers-condition` is `or` so even if there's no `kbn-name` header, the hosts will match.

**Comment by c-sh0** [comment]
The only other issue I saw is a request to /login would return a 404 for some hosts. They just may be weird corner cases? A request to / and following the redirect worked around those. (ie: request to / would redirect to /app/kibana, or /some/other/path) similarly having all three requests (/, /app/kibana, and /login) would handle any cases where a server doesn't redirect. - Just my $0.02 :)

**Comment by princechaddha** [comment]
@c-sh0 Thanks for pointing out the edge cases, I have made the changes above
