### ISSUE TITLE
Cache-poisoning enhancement

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#3912]
Resolving potential false negative due to lot of hacker requesting to the same domain with same cache buster (+ severity low because impact integrity of the page)

```
id: cache-poisoning

info:
  name: Cache Poisoning
  author: melbadry9,xelkomy,akincibor
  severity: low
  reference:
    - https://blog.melbadry9.xyz/fuzzing/nuclei-cache-poisoning
    - https://portswigger.net/research/practical-web-cache-poisoning
  tags: cache,generic

requests:
  - raw:
      - |
        GET /?{{randstr_1}}=9 HTTP/1.1
        X-Forwarded-Prefix: cache.example.com
        X-Forwarded-Host: cache.example.com
        X-Forwarded-For: cache.example.com

      - |
        GET /?{{randstr_1}}=9 HTTP/1.1

    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(body_2, "cache.example.com")'
```

**Comment by akincibor** [comment]
randstr 1 should be the same for the second request

**Comment by akincibor** [comment]
[2022-03-16 12:20:47] [cache-poisoning] [http] [low] https://REDACTED/?26Sv42zMCfXFC02Ec3FbfAmQVgn=9
[2022-03-16 12:21:10] [cache-poisoning] [http] [low] https://REDACTED/?26Sv42zMCfXFC02Ec3FbfAmQVgn=9
[2022-03-16 12:22:07] [cache-poisoning] [http] [low] https://REDACTED/?26Sv42zMCfXFC02Ec3FbfAmQVgn=9

**Comment by princechaddha** [comment]
Hello @akincibor, thank you so much for creating filing issue and contributing to the project  🚀

**Comment by dogasantos** [comment]
Hi @princechaddha @akincibor 
This is a nice template, it helpmed me to find an interesting issue on my assets.
If I may, I'd like to suggest the following change:

```
id: cache-poisoning-xss

info:
  name: Cache Poisoning Based Stored XSS
  author: melbadry9,xelkomy,akincibor
  severity: high
  reference:
    - https://blog.melbadry9.xyz/fuzzing/nuclei-cache-poisoning
    - https://portswigger.net/research/practical-web-cache-poisoning
  tags: cache,generic

requests:
  - raw:
      - |
        GET /?thisisjustrandom=thisisjustrandom HTTP/1.1
        X-Forwarded-Prefix: prefix.cache.example.com
        X-Forwarded-Host: host.cache.example.com
        X-Forwarded-For: for.cache.example.com
      - |
        GET /?thisisjustrandom=thisisjustrandom HTTP/1.1
    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - 'contains(body_2, "cache.example.com")'

    extractors:
      - type: regex
        part: all
        regex:
          - "(prefix|host|for).cache.example.com"

```

This should help to see the culprit header for the cached content.
Thanks again

**Comment by princechaddha** [comment]
@dogasantos, thank you so much for updating this template and contributing to this project 🍻
I have created a PR with the changes [here](https://github.com/projectdiscovery/nuclei-templates/pull/4418). Please let me know if the made changes look good, and we will merge the PR
