### ISSUE TITLE
Unable update Nuclei templates 

### ISSUE THREAD

**Issue by RBNA-ES** [projectdiscovery/nuclei-templates#3942]
Hi,

I tried to update nuclei templates using the command `nuclei -ut` but keep getting the below error. 
```
[ERR] Could not update templates: GET https://api.github.com/repos/projectdiscovery/nuclei-templates/releases/tags/v8.9.1: 401 Bad credentials []
```
Please give some advice to resolve this issue.

Thank you.

**Comment by ehsandeep** [comment]
@RBNA-ES this is fixed here - https://github.com/projectdiscovery/nuclei/issues/1679 in dev version of nuclei, a new release of nuclei will be pushed by EOD or tomorrow.
