### ISSUE TITLE
jolokia-info-disclosure false positive

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#3963]
### Nuclei Version:

latest

### Template file:

jolokia-info-disclosure.yaml

### Command to reproduce:

jolokia-info-disclosure:memory:

False positive because the path is added in the source code + 200 OK

["actuator","jolokia","read","java.lang:type=Memory"],"slug":["undefined","actuator/jolokia/read/java.lang:type=Memory"]},

**Comment by akincibor** [comment]
I have multiple false positive and always it's inside <script id="__NEXT_DATA__" type="application/json">
So maybe adding do not contain __NEXT_DATA__ will resolve the issue ?

**Comment by princechaddha** [comment]
Hello @akincibor, Thanks for creating this issue, the above PR should resolve it 👍
