### ISSUE TITLE
[Feature] auto update readme stats on new release

### ISSUE THREAD

**Issue by team-projectdiscovery** [projectdiscovery/nuclei-templates#401]
**Describe the solution you'd like**

Updating readme stats in an automated way. 

- [ ] Update template directory/count/HTTP request on new release. 
- [ ] Update tree view of template directory on new release.

**Comment by toufik-airane** [comment]
PR https://github.com/projectdiscovery/nuclei-templates/pull/438

**Comment by team-projectdiscovery** [comment]
Done!
