### ISSUE TITLE
False Positive: kube-api-roles

### ISSUE THREAD

**Issue by edoardottt** [projectdiscovery/nuclei-templates#4027]
### Template file: 
```
nuclei-templates/technologies/kubernetes/kube-api/kube-api-roles.yaml
```

### Command to reproduce: 
```
nuclei -u "https://advertising.samsclub.com/" -t ~/nuclei-templates/technologies/kubernetes/kube-api/kube-api-roles.yaml
```

### Anything else:

https://advertising.samsclub.com/api/v1/roles
https://advertising.walmart.com/api/v1/roles

I can't find documentation for this endpoint... are we sure it exists?

**Comment by princechaddha** [comment]
Hello @edoardottt, Thank you so much for contributing to the project by creating this issue. We have removed this template since we were unable to verify this API endpoint.
