### ISSUE TITLE
Duplicate Detection Templates for the Same Application (Avatier Password Management)

### ISSUE THREAD

**Issue by AdamCrosser** [projectdiscovery/nuclei-templates#4067]
It looks like the `exposed-panels/aims-password-portal.yaml`, `avatier-password-management.yaml`, and  `aims-password-mgmt-client.yaml` detection templates seem to all target the same application.

For example, searching on Shodan for `http.favicon.hash:983734701` I've found several instances where these templates all match the same application. However, the `aims-password-portal.yaml` template misses a few instances where the user has customized the default page. 

```sh
➜  echo https://redacted.com/ | nuclei -silent -t ./exposed-panels/aims-password-mgmt-client.yaml
[2022-04-06 12:37:29] [aims-password-mgmt-client] [http] [info] https://redacted.com/aims/ps/
➜   echo https://redacted.com/ | nuclei -silent -t ./exposed-panels/aims-password-portal.yaml
[2022-04-06 12:37:48] [aims-password-portal] [http] [info] https://redacted.com/aims/ps/default.aspx
➜  echo https://redacted.com/ | nuclei -silent -t ./exposed-panels/avatier-password-management.yaml
[2022-04-06 12:38:03] [avatier-password-management] [http] [info] https://redacted.com/aims/ps/
```

**Comment by ehsandeep** [comment]
@AdamCrosser thanks, this should be now resolved with linked PR.
