### ISSUE TITLE
How to iterate over links in html, and do other things like in yaml

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei-templates#4133]
How to iterate over links in html, and do other things like
a/xx1/xx2
a/xx1/xx2
operate:
The other value specified by a/xx1/ initiates the request again

thanks

**Comment by ehsandeep** [comment]
@hktalent, You can use `iterate-all: true` attribute along with the internal extractor, here is an example template - [robots-txt-endpoint.](https://github.com/projectdiscovery/nuclei-templates/blob/master/miscellaneous/robots-txt-endpoint.yaml)
