### ISSUE TITLE
nuclei-templates/vulnerabilities/wordpress/ninjaform-open-redirect.yaml

### ISSUE THREAD

**Issue by omarhashem123** [projectdiscovery/nuclei-templates#4178]
in this template it should detect open redirection in ninjafrom but validation expertion is totally wrong as he try to redirct to google.com and match on google.com but alot of websites that i scanned was having in their html source code google.com which lead to alot of false/positive

Fix:match on something like that for example
random-value.evil.com

**Comment by princechaddha** [comment]
Hello @omarhashem123, thank you so much for creating this issue and contributing to this project  🚀
