### ISSUE TITLE
[false-positive] lotus-domino-version

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei-templates#440]
Can you please drafting `lotus-domino-version`, @bauthard? Cause it's giving a lots of false-positives.

**Comment by bauthard** [comment]
Hey @dwisiswant0, 

Sure, just you know we didn’t create a release of the latest changes, so shouldn’t be an issue, also can you please DM on discord so we can push a fix for this? A few tests run on tons of URLs doesn’t flag any results for me.

**Comment by CasperGN** [comment]
Tuning in - just ran against 406 urls with only correct positives - can you disclose some of the false positives?

/ Casper

**Comment by dwisiswant0** [comment]
> Hey @dwisiswant0,
> 
> Sure, just you know we didn’t create a release of the latest changes, so shouldn’t be an issue, also can you please DM on discord so we can push a fix for this? A few tests run on tons of URLs doesn’t flag any results for me.

DMing you.

**Comment by bauthard** [comment]
@CasperGN, here is the case:-

```
                <form method="post" action="" style="font-size:14px;" id="inc_apply_form">
		<input type="hidden" name="text[Referrer]" value="">
		<input type="hidden" name="text[SitePage]" value="/iNotes/Forms5.nsf">
		<div id="form_left" class="form_first_part">
```
Here `/iNotes/Forms5.nsf` is the path of the request getting added into responses.

**Comment by bauthard** [comment]
@CasperGN If you are on discord we can share more info, Discord:- https://discord.com/invite/KECAGdH

**Comment by bauthard** [comment]
@dwisiswant0 should be fixed with https://github.com/projectdiscovery/nuclei-templates/commit/ba446fae09908962ef895130e1cd89f2a35c3800, thank you both of you for quickly filing and fixing the issue.
