### ISSUE TITLE
Relative Paths

### ISSUE THREAD

**Issue by w4cky** [projectdiscovery/nuclei-templates#465]
Hi, i write nuclei template. I have problem with path :( 
which variable is responsible for Relative Paths ?

My problem: 
   GET {{**RelativePath???**}} HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0
        Accept-Language: en-US,en;q=0.9
        Connection: close
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

**Comment by bauthard** [comment]
Hey @w4cky, 

You can read about available variables here https://nuclei.projectdiscovery.io/templating-guide, nuclei do not have any variable for RelativePath.

**Comment by w4cky** [comment]
Hey, thanks for the answer. I read your manual, but thought there were also undescribed variables :) how can i get relative path? There is a method for this? some truncate etc?I wanted to write a simple password cracker, but without a relative path it doesn't make sense; (It is not clear which endpoint (directory) is password protected.

**Comment by bauthard** [comment]
Hey @w4cky, 

You can define, one or multiple paths like this, all the capabilities are well defined on the guide page, not sure if it helps for something you looking for. 

```
      - {{BaseURL}}/
      - {{BaseURL}}/path1
      - {{BaseURL}}/path2
```

**Comment by w4cky** [comment]
@bauthard  i understand but 
I cannot define it. See I'm writing a template to find directories:

/Administrator
/ admin
/ panel
etc ...

And if it finds that / admin requires BASIC AUTH, it has to send a few requests to / admin to check simple passwords.

I don't know how to pass the directory it finds (/ admin, / panel, etc). Do you have any idea?

**Comment by bauthard** [comment]
Unfortunately, this is something not supported, for the time being, nuclei mostly focus to ease the defined testing, you can also write conditional templates using workflows, but you need to be specific for something, and not generic for multiple paths. 

For workflow example, check this out https://github.com/projectdiscovery/nuclei-templates/blob/master/workflows/grafana-workflow.yaml, where template 1 detects for grafana panel and if found run 2nd template checks for common password on that found grafana panel, you can follow the same based on specific tech/panel.

**Comment by w4cky** [comment]
unfortunately it doesn't finish what i need. Will you add this functionality to nuclei?

**Comment by bauthard** [comment]
@w4cky As of now, we are focusing on making the current features stable, so in the future, we will see what else we can add to ease testing, but tbh it will take some time to introduce new features. 

let me know if you have more questions or we can close this out.

**Comment by w4cky** [comment]
thanks for the answers. Close please.
