### ISSUE TITLE
Help needed to extract value using extractors

### ISSUE THREAD

**Issue by allwin101** [projectdiscovery/nuclei-templates#466]
**Describe the bug**
I am trying to extract the value of an input tag using extractors. It is working well in the regex builder but not in the yaml file. Not sure what I am missing. Help needed to build regex to extract only the value **( GIJCojJrWkxfpxgm )** rather than the whole tag.

**Suggestion**
It would be helpful to have generic regex examples like above as part of documentation while building templates for easy correlation

**Comment by CasperGN** [comment]
Hi @allwin101 

Is the value always "just" alphanumeric values? In that case, could you try this one:
```
- "(?m:([[:alpha:]]+))"
```

/ Casper

**Comment by CasperGN** [comment]
I think it may actually be related to using `FindAllString` in the extractor whereas `FindAllStringSubmatch` can return the matchgroup.
I've compiled with the extractor.go as:
```go
Line 57 ...
	for _, regex := range e.regexCompiled {
		matches := regex.FindAllStringSubmatch(corpus, -1)
		for _, match := range matches {
			results[match[1]] = struct{}{}
		}
	}
```
Which yields:
```
[cgn@localhost nuclei-templates]$ ../nuclei/nuclei2 -target https://stage51-a.cricut.com -t files/tester.yaml -silent
[test] [http] https://stage51-a.cricut.com/ [82RJr4LIaRkAFAgZ]
```
I can't grasp the consequences of the already existing templates to make this change as a PR at the moment though.
Would need one of the core-members to chime in on this i guess.

/ Casper

**Comment by allwin101** [comment]
Thank you so much @CasperGN for the reply..Appreciate your help. Let me wait for some official changes on it

**Comment by Ice3man543** [comment]
@CasperGN This can be solved in a backwards compatible way by introducing a new option for regex extractor which will allow user to get a specific group of the match instead of the entire match. Let me make a PR for that!

**Comment by CasperGN** [comment]
And that is by far the better option @Ice3man543. Just FYI on PR projectdiscovery/nucle/pull/231

Also, let me know if I can assist in any way!

/ Casper

**Comment by Ice3man543** [comment]
@CasperGN FYI https://github.com/projectdiscovery/nuclei/pull/312. This is what i came up with!
