### ISSUE TITLE
templates with payloads/wordlists are not being executed when called directly

### ISSUE THREAD

**Issue by dogasantos** [projectdiscovery/nuclei-templates#4774]
### Issue description:
Hey guys,
Just trying to create my own template and seeing this issue. I've tried with a standard template and also produces the same behavior:
```
$ nuclei -t ~/nuclei-templates/vulnerabilities/grafana/grafana-file-read.yaml -u https://target
//bannercut//
[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.3 (latest)
[INF] Using Nuclei Templates 9.0.9 (latest)
[FTL] Could not run nuclei: no valid templates were found
```
The -validator returns everything as good as possible, but when we try to call the template directly as above, no no valid templates were found.

Are you aware of this?
ty

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/nuclei-templates/discussions/4677

**Comment by ehsandeep** [comment]
@dogasantos there are certain tags/templates that are excluded from the default scan, more details - https://nuclei.projectdiscovery.io/nuclei/get-started/#template-exclusion

In this case, your template getting excluded as it contains `fuzz` tag, default exclusion can be bypassed using `-itags fuzz` or just remove the `fuzz` tag from your custom template.
