### ISSUE TITLE
No results..

### ISSUE THREAD

**Issue by Sajeeshab** [projectdiscovery/nuclei-templates#4786]
How to solve this ....

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.3 (latest)
[INF] Using Nuclei Templates 9.0.9 (latest)
[INF] Templates added in last update: 47
[INF] Templates loaded for scan: 152
[INF] Templates clustered: 6 (Reduced 3 HTTP Requests)
[INF] Using Interactsh Server: oast.pro
[INF] No results found. Better luck next time!

**Comment by daffainfo** [comment]
Please print the debug output, try this command
```
nuclei -u https://example.com -t nuclei-templates --debug
```

**Comment by ehsandeep** [comment]
See https://github.com/projectdiscovery/nuclei-templates/discussions/4785
