### ISSUE TITLE
Cisco Telepresence Template not working

### ISSUE THREAD

**Issue by oppsec** [projectdiscovery/nuclei-templates#4865]
### Command to reproduce: nuclei -t ~/nuclei-templates/exposed-panels/cisco/cisco-telepresence.yaml -u http://177.220.81.13

Hello, Project Discovery Team! Hope everyone is doing well.
Today I've run nuclei against a website that uses Cisco TelePresence software but the template isn't working.

![image](https://user-images.githubusercontent.com/50470310/179846607-af58089a-9e13-4875-85f8-a3cf6bc0580b.png)
![image](https://user-images.githubusercontent.com/50470310/179846682-bc1c75d2-524e-4601-b47f-8c388f1bc5ed.png)

**Comment by princechaddha** [comment]
Hi @oppsec, Thank you for taking the time to create this issue and for contributing to this project 🍻
The template has been updated with the `redirects: true`. Thanks
