### ISSUE TITLE
phpMyAdmin Setup File accessbile

### ISSUE THREAD

**Issue by ArjunChandarana** [projectdiscovery/nuclei-templates#4906]
### Template Information:

There is one setup/index.php file accessible on phpMyadmin Panel without any authorization if setup file is not disabled.

### Nuclei Template:

```

id: unauthorized-phpMyadminSetup

info:
  name: Phpmyadmin Setup Accessbile
  author: ArjunChandarana
  severity: High
  tags: phpmyadminsetup,unauthorized setup accessible

requests:
  - method: GET
    path:
      - "{{BaseURL}}/setup/index.php"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "You want to configure phpMyAdmin using web interface"
          - "<title>phpMyAdmin setup</title>"
        condition: or

      - type: status
        status:
          - 200

```
![nuclei](https://user-images.githubusercontent.com/41663776/180658041-0e672fe7-fe94-460b-a639-afcec416c314.png)

![phpMyAdmin-setup](https://user-images.githubusercontent.com/41663776/180658063-7ca0846c-4929-4970-9e69-f18c7bcc1edf.jpg)

**Comment by akincibor** [comment]
https://github.com/projectdiscovery/nuclei-templates/blob/master/misconfiguration/phpmyadmin/phpmyadmin-setup.yaml

**Comment by ArjunChandarana** [comment]
Hi,
I tried using this template but setup/index.php was not detected

**Comment by ArjunChandarana** [comment]
After adding {{baseurl}}/setup/index.php it was detected by nuclei

**Comment by princechaddha** [comment]
Hi @ArjunChandarana, Thank you for taking the time to create this issue and for contributing to this project 🍻
