### ISSUE TITLE
typo in filename (syfmony-profiler.yaml instead of symfony-profiler.yaml)

### ISSUE THREAD

**Issue by DanielRuf** [projectdiscovery/nuclei-templates#4944]
### Issue description:

There is a small typo in the filename:

https://github.com/projectdiscovery/nuclei-templates/blob/master/exposures/configs/syfmony-profiler.yaml

So if this is fixed, then there are two symfony-profiler.yaml files. What should the name of the duplicate file?

**Comment by ehsandeep** [comment]
@DanielRuf, thanks should be fixed with https://github.com/projectdiscovery/nuclei-templates/pull/4945
