### ISSUE TITLE
Issue on dsl matchers

### ISSUE THREAD

**Issue by zy9ard3** [projectdiscovery/nuclei-templates#4995]
Hi Team,

Hope All are going well !!

### Nuclei Version:

nuclei 2.7.5

### Template file :

Custom Template : [method-override-headers-detect-for-cache-poisoning](https://github.com/zy9ard3/templates/blob/main/method-override-cp-dos.yaml)

I can able to validate the template and seems wrote as perfect, kindly please refer once if you doubt of any issue has

### Command to reproduce :

Use the above template with the host `https://cars.hotels.com` as the host is accepting method-overriding via headers while I can able to verify it manually but I'm unable to detect it with the above template which nuclei doesn't taking dsl values as matcher instead showing as `No parameter 'status_code_2' found` detecting as False Negative while the issue exists in real

![reference](https://user-images.githubusercontent.com/67743789/182704953-a5f23738-b1b7-41c6-b9e3-25913386a928.png)

*Kindly please look on the issue and kindly let me know if anything I missed out, I'm glad to help on any questions/infos if required further*

Thanks & Regards,
@zy9ard3

**Comment by ehsandeep** [comment]
@zy9ard3, thanks for creating an issue for this, this is a issue with engine and being tracked here - https://github.com/projectdiscovery/nuclei/issues/2394

**Comment by zy9ard3** [comment]
Hi @ehsandeep 

Thanks for taking look on this !!

Also noticed the same issue exists on raw templates as well only with `status_code_*` dsl matcher

![Screenshot_2022-08-10_15_00_31](https://user-images.githubusercontent.com/67743789/183995924-f0ef65a2-30fa-40fa-874e-8b8b5c719bca.png)

Thanks & Regards,
@zy9ard3
