### ISSUE TITLE
False Positive: omnia-mpx-lfi

### ISSUE THREAD

**Issue by edoardottt** [projectdiscovery/nuclei-templates#5002]
### Nuclei Version: 
`2.7.5`

### Template file: 
`‎‎vulnerabilities/other/omnia-mpx-lfi.yaml`

### Command to reproduce:
```bash
nuclei -t ~/nuclei-templates/vulnerabilities/other/omnia-mpx-lfi.yaml -u "https://community.geotab.com/"
```

**Comment by princechaddha** [comment]
Hi @edoardottt, Thank you for taking the time to create this issue and for contributing to this project 🍻
