### ISSUE TITLE
[Feature] Stop on first match

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei-templates#510]
Hello,

I would love to have an option in the nuclei templates, to stop running nuclei or the templates, once a successful match/hit.

Let's say we are looking for phpinfo directories, once I get a positive match of /info.php I don't want to issue 50 more requests (that the templates has), and instead move to the next templates or stop running nuclei if it gets on valid match/hit.

This is something that would save a lot of time on special templates.

**Comment by bauthard** [comment]
Hi @marcelo321, 

How this is different from https://github.com/projectdiscovery/nuclei/issues/318?

**Comment by marcelo321** [comment]
Sorry @bauthard I completely forgot that I created that issue. Sorry for the spam

**Comment by bauthard** [comment]
no problems, just wanted to confirm, thank you.
