### ISSUE TITLE
Templates for login-spray (credential stuffing)

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei-templates#5153]
### Template for?

Similar to [token-spray](https://github.com/projectdiscovery/nuclei-templates/blob/master/token-spray/README.md), that takes `token` value as user input to run against multiple API endpoints to confirm the validity, same can be done for checking **user/email** + **password** combination against various services/panels for credentials validation aka [credential stuffing ](https://owasp.org/www-community/attacks/Credential_stuffing) using the self-contained template.

### Details:

To start with login-spray templates, here is list of few well known services / panel to cover:

- [ ] #6937
- [ ] GitLab
- [ ] BitBucket
- [ ] Atlassian
- [ ] Slack

**Comment by parthmalhotra** [comment]
Bump
