### ISSUE TITLE
False Positive wix-takeover

### ISSUE THREAD

**Issue by alcaparra** [projectdiscovery/nuclei-templates#5195]
The template [takeovers/wix-takeover.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/master/takeovers/wix-takeover.yaml) triggers a false positive when you access a wix website directly though its IP Address, throwing the error "_Hey, We Know What You're Trying To Do :) But We Actually Need You To Type In The Website URL_".

Stricter rules should be added, I unfortunately don't have any server that should test Positive.

**Comment by alcaparra** [comment]
False Positive webserver: `https://privatebin.net/?99df6667c1a7b88e#83WudQFBST9pQhZxe9b4n9iquyy6CA3KbgN8hD7XJfeN` _(please dont mention the ip in followup messages)_

**Comment by alcaparra** [comment]
Okay, I found a domain vulnerable to wix-takeover.
Find the page source attached: https://privatebin.net/?6bd75b0d359c0303#6X7ptxDBpYaJAvxR7vBNvztdkMRWK7ZTzz7Gp7Eq7332

It turns out the matchers were correct, "Error ConnectYourDomain occurred" only appears on vulnerable sites.
The error lies in the conditional, it should be set to "and", because "wixErrorPagesApp" also appears on unrelated errors.

**Comment by alcaparra** [comment]
https://github.com/projectdiscovery/nuclei-templates/commit/f1e9fa8082ca7e91be315df216af0f5d02357f6a

**Comment by ehsandeep** [comment]
@alcaparra thank you for reporting this, should be fixed with #5219
