### ISSUE TITLE
Multiple matchers with DNS request

### ISSUE THREAD

**Issue by melbadry9** [projectdiscovery/nuclei-templates#52]
Is multiple matchers are possible while using DNS request ?
Is there a way to make HTTP requests when specific DNS condition is true?

**Comment by bauthard** [comment]
Hi @melbadry9, 

> Is multiple matchers are possible while using DNS request ?

It should be doable like we do with HTTP. 

> Is there a way to make HTTP requests when specific DNS condition is true?

Currently, you can use DNS and HTTP requests in the same template but can not use to serve any condition to each other and this is something we want to do it, as it's really open many possibilities to automate.

**Comment by bauthard** [comment]
@Mzack9999 Multiple matchers are not working for DNS requests right now. 

```
root@b0x:~/nuclei-templates# query_domain hackerone.com | nuclei -silent -t cname-detector.yaml 
[cname-service-detector] [dns] mta-sts.hackerone.com
[cname-service-detector] [dns] mta-sts.forwarding.hackerone.com
[cname-service-detector] [dns] mta-sts.managed.hackerone.com
[cname-service-detector] [dns] docs.hackerone.com
```

```
root@b0x:~/nuclei-templates# cat cname-detector.yaml 
id: cname-service-detector

info:
  name: 3rd party service checker
  author: bauthard
  severity: info


dns:
    - name: "{{FQDN}}"
      type: CNAME
      class: inet
      recursion: true
      retries: 5

      matchers:
      - type: word
        name: zendesk
        words:
          - "zendesk.com"
      matchers:
      - type: word
        name: github
        words:
          - "github.io"
```

expected action is to list subdomains with `cname` `zendeskc.com` and `github.io` in it, but this miss out `zendesk.com` for `support.hackerone.com` and with DNS request the result miss out the name of matches as well, for the reference https://github.com/projectdiscovery/nuclei/blob/5f837610f17b5e53c5f324fb233195338869d0e0/pkg/matchers/matchers.go#L15

**Comment by bauthard** [comment]
This is fixed and here is working example @melbadry9 

https://github.com/projectdiscovery/nuclei-templates/blob/master/dns/cname-service-detector.yaml
