### ISSUE TITLE
Update intrusive Tag

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei-templates#5271]
### Please describe your feature request:

As discussed on the discord channel [here](https://discord.com/channels/695645237418131507/700096242226692236/1013884611740319816), we need to update the templates which include file uploads, file creation, or that are making any changes on the target host with an `intrusive` tag.

This allows users to ignore templates with intrusive tags on sensitive targets if required.

**Comment by geeknik** [comment]
There are only 65 templates tagged as "intrusive" but in reality, there are many, many, many templates in this repo which can be considered intrusive.

**Comment by princechaddha** [comment]
@geeknik Templates that involve file uploads or modifications to application settings are tagged as intrusive. It would be really helpful if you could provide examples of template types that you consider intrusive. This will enable us to properly identify and tag them accordingly, ensuring that no cases have been overlooked.
