### ISSUE TITLE
Potential DSL variable substitution issues

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei-templates#5358]
There is a good chance that variable substitution does not work correctly in multiple templates.

One fixed example: https://github.com/projectdiscovery/nuclei-templates/pull/5357

To be reviewed the following:
```sh
grep -RE "\{\{[^}]+?\{\{" ~/nuclei-templates --color=auto
```

![image](https://user-images.githubusercontent.com/13679401/190138403-95fe053e-2852-43a9-89bb-11cac26972e5.png)

**Comment by princechaddha** [comment]
This issue has been resolved at the engine level and will now function correctly in both scenarios.
