### ISSUE TITLE
Too Many FPs from Yesterday added Exposures tokens

### ISSUE THREAD

**Issue by tarunkant** [projectdiscovery/nuclei-templates#5388]
### Description:
The matches are very generic and that pulls out a lot of False Positives

### Nuclei Version:
2.7.7

### Template file:
exposures/tokens/discord/discord-backup-code.yaml
exposures/tokens/github/github-recovery-code.yaml
exposures/tokens/gitlab/gitlab-recovery-code.yaml

### Command to reproduce:
Putting just one example:

`nuclei -target https://superstats.espncricinfo.com -t ~/nuclei-templates/exposures/tokens/discord/discord-backup-code.yaml`
`nuclei -target https://superstats.espncricinfo.com -t ~/nuclei-templates/exposures/tokens/github/github-recovery-code.yaml`
`nuclei -target https://superstats.espncricinfo.com -t ~/nuclei-templates/exposures/tokens/gitlab/gitlab-recovery-code.yaml`

**Comment by DhiyaneshGeek** [comment]
@tarunkant Thanks for raising the issue, checking this currently :)

**Comment by tarunkant** [comment]
@princechaddha, your PR only deletes `discord-backup-code.yaml`, other two exposures also generating alot FPs too.
cc/ @DhiyaneshGeek

**Comment by princechaddha** [comment]
Hi @tarunkant, Thank you for taking the time to create this issue and for contributing to this project 🍻
We have deleted those templates and will add them after updating the matchers

**Comment by tarunkant** [comment]
> Hi @tarunkant, Thank you for taking the time to create this issue and for contributing to this project 🍻 We have deleted those templates and will add them after updating the matchers

https://github.com/projectdiscovery/nuclei-templates/issues/5388#issuecomment-1249236591
The other two exposure tokens should also have strict matchers as they also contributing a lot in FPs :) :
exposures/tokens/github/github-recovery-code.yaml
exposures/tokens/gitlab/gitlab-recovery-code.yaml

**Comment by tarunkant** [comment]
Thanks it is resolved now.
