### ISSUE TITLE
graphql [nuclei-template] 

### ISSUE THREAD

**Issue by Elsfa7-110** [projectdiscovery/nuclei-templates#540]
**Template Details**
search for graphql endpoints with good wordlist
```
nuclei template goes here
```
https://github.com/Elsfa7-110/graphql-elsfa7-nuclei-template/blob/main/graphql.yaml

**Comment by bauthard** [comment]
Thank you @EasyNV for submitting this, I guess we can update the additional endpoints in the existing template for [graphql-detection](https://github.com/projectdiscovery/nuclei-templates/blob/9396e6058d874991bc01c0819de99ee80ce9415c/technologies/graphql.yaml).

**Comment by Elsfa7-110** [comment]
no any problem
and i am working now to make other templates

**Comment by bauthard** [comment]
@Elsfa7-110 this has been updated here https://github.com/projectdiscovery/nuclei-templates/commit/9cce7c42447f14097ae1081e79589c74197e9946, thank you.
