### ISSUE TITLE
 Template silverstripe login 

### ISSUE THREAD

**Issue by RamkrishnaSawant** [projectdiscovery/nuclei-templates#5468]
### Template Information:

This template finds silverstripe cms  login page
Reference : https://userhelp.silverstripe.org/en/4/managing_your_website/logging_in/

### Nuclei Template:

```id: silverstripe-login 

info:
  name: silverstripe login
  author: Ramkrishna Sawant
  severity: info
  tags: panel,silverstripe

requests:
  - method: GET
    path:
      - "{{BaseURL}}/admin"
    matchers:
      - type: word
        words:
          - "Password"
          -  "silverstripe cms"
        condition: and

```

**Comment by RamkrishnaSawant** [comment]
Hello  can anyone see this new template?

**Comment by DhiyaneshGeek** [comment]
@RamkrishnaSawant could you share some debug data or shodan query to finger print these login panels ?
