### ISSUE TITLE
elasticbeantalk-takeover - Not possible?

### ISSUE THREAD

**Issue by PR3R00T** [projectdiscovery/nuclei-templates#5470]
Hey, 

template stored at: [nuclei-templates](https://github.com/projectdiscovery/nuclei-templates)/[dns](https://github.com/projectdiscovery/nuclei-templates/tree/master/dns)/elasticbeantalk-takeover.yaml

I dont believe this is possible to do this takeover anymore, I see when I create and register applications in AWS, AWS inserts a unique tag inbetween the app name and the region.elasticbeanstalk.com. 

Happy to be proven wrong if anyone has a better understanding and view on this.

Kind Regards

PR3R00T

**Comment by princechaddha** [comment]
Hi @PR3R00T, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to the project 🍻

**Comment by princechaddha** [comment]
@PR3R00T, Sorry for the confusion. We are reverting the changes as the case you referenced is not covered by this template. This template covers another subdomain takeover. For more details, you can read the comment under the template's metadata.
