### ISSUE TITLE
[false-positive]  Netlify subdomain takeover

### ISSUE THREAD

**Issue by NagliNagli** [projectdiscovery/nuclei-templates#549]
**Nuclei version**

```
2.1.1
```

**Nuclei template version**
```
7.1.2
```
**Nuclei template ID**
```
detect-all-takeovers
```

The change which had been made today detects most of 404 pages into Netlify takeover.

**Comment by bauthard** [comment]
@NagliNagli thanks for reporting, fixed it here https://github.com/projectdiscovery/nuclei-templates/commit/3d7806c4a7645b7d193b4c2a608b7d87ee3ad538

**Comment by NagliNagli** [comment]
Can we remove unbounce, fastly as well? as they are not vulnerable.

**Comment by bauthard** [comment]
@NagliNagli they both are valid for few edge cases as listed here https://github.com/EdOverflow/can-i-take-over-xyz, for the same reason we are keeping them in the list for now.
