### ISSUE TITLE
-ntv indexing problem

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#5982]
`nuclei -l target.txt -ntv v9.2.6`

<img width="1321" alt="Capture d’écran 2022-11-06 à 23 59 24" src="https://user-images.githubusercontent.com/99909324/200199943-d3dedaf6-3aff-435b-a391-889b79efbe6b.png">

**Comment by princechaddha** [comment]
Hi @akincibor, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue. You are receiving this error as the files were moved to the installer directory under `misconfig` folder after this release.
