### ISSUE TITLE
Versa Network Templates

### ISSUE THREAD

**Issue by c-sh0** [projectdiscovery/nuclei-templates#5987]
### Template Information:
Some templates for some Versa Networks SASE/SDWAN products. 

### Nuclei Template:
https://github.com/c-sh0/nuclei_templates/tree/main/versa-networks
Tested via Shodan searches

**Comment by princechaddha** [comment]
Hi @c-sh0, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and sharing these templates with the community 🍻
