### ISSUE TITLE
Subdomain Takeover False Positives When Scanning IP Addresses

### ISSUE THREAD

**Issue by AdamCrosser** [projectdiscovery/nuclei-templates#6016]
One issue I've seen with many of the subdomain takeover templates is they trigger when scanning of an IP address as well as scanning of a subdomain as long as the correct content is returned. Unfortunately, the issue is only valid when scanning a subdomain. 

This may be unique to the way I use Nuclei, but typically I like to scan both subdomains I've discovered as well as the IP addresses directly after resolving the discovered subdomains to IP addresses. This can sometimes lead to discovering interesting issues where there is different content or services exposed on the IP address than there is on the vhost exposed through the subdomain. 

Unfortunately, many of the subdomain takeover templates trigger when scanning IP address as well as the subdomain. This can lead to a lot of false positives with the subdomain takeover templates such as the GitHub takeover template. This is shown in the snippet given below:

```
➜  nuclei-templates ✗ echo https://185.199.110.153:443/ | nuclei -t ./takeovers/github-takeover.yaml
[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.7 (outdated)
[INF] Using Nuclei Templates 9.2.7 (latest)
[INF] Templates added in last update: 50
[INF] Templates loaded for scan: 1
[2022-11-10 12:21:02] [github-takeover] [http] [high] https://185.199.110.153:443/
➜  ✗
```

**Comment by ehsandeep** [comment]
We can fix this by adding the below matcher in all takeover templates.

```yaml
    matchers-condition: and
      - type: dsl
        dsl:
          - Hostname != ip
```

**Comment by ehsandeep** [comment]
@AdamCrosser should be fixed with https://github.com/projectdiscovery/nuclei-templates/pull/6066 in master, again thanks for flagging this.
