### ISSUE TITLE
[False-Positive] cowrie-honeypot-detect 

### ISSUE THREAD

**Issue by y0no** [projectdiscovery/nuclei-templates#6067]
This template seems to trigger a lot of false positive on OpenSSH server.

### Nuclei Version:

2.7.9

### Template file:

[network/cowrie-honeypot-detect.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/master/network/cowrie-honeypot-detect.yaml)

### Command to reproduce:

```bash
echo <openssh server IP> |  nuclei -t ~/nuclei-templates/network/cowrie-honeypot-detect.yaml
```

**Comment by princechaddha** [comment]
Hello @y0no, Thank you for taking the time to create this issue and for contributing to this project 🍻

We have confirmed the template has been causing a lot of FP results so for the time being, we have removed this template. Thanks
