### ISSUE TITLE
regex extractor with /g (global) flag by default

### ISSUE THREAD

**Issue by organiccrap** [projectdiscovery/nuclei-templates#61]
Hi, Is there any way to disable global flag in regex/extractor? for example, the matching regex have multiple entries in a page response. Rather than extractor printing out all the occurrences, is there a way to only print the first occurrence.

**Comment by bauthard** [comment]
This is added here https://github.com/projectdiscovery/nuclei/issues/50, either you can wait for the next release or use this to see the latest changes. 

```
GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/cmd/nuclei@master
```
