### ISSUE TITLE
[nuclei-template]  Actuator-Unauthorized

### ISSUE THREAD

**Issue by sparrownut** [projectdiscovery/nuclei-templates#6114]
### Template Information:

Spring Boot Actuator Unauthorized is a critical vuln

### Nuclei Template:

```
id: Actuator-Unauthorized
info:
  name: Spring Boot Actuator Unauthorized
  author: stupidfish
  severity: critical
  description: Spring Boot Actuator Unauthorized
  reference:
    - https://www.freebuf.com/column/234719.html
  tags: actuator,unauthorized

requests:
  - method: GET
    path:
      - "{{BaseURL}}/actuator;/env;"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'activeProfiles'
          - 'name'
          - 'value'
        condition: and

```

![image](https://user-images.githubusercontent.com/31125137/202936091-8433ba3b-fb79-4431-a8e1-99a0fed67d47.png)

**Comment by DhiyaneshGeek** [comment]
@sparrownut we already have a template for this [nuclei-templates](https://github.com/projectdiscovery/nuclei-templates/tree/02f7229c6a56c32b778d78a762f247d0cc88d331)/[misconfiguration](https://github.com/projectdiscovery/nuclei-templates/tree/02f7229c6a56c32b778d78a762f247d0cc88d331/misconfiguration)/[springboot](https://github.com/projectdiscovery/nuclei-templates/tree/02f7229c6a56c32b778d78a762f247d0cc88d331/misconfiguration/springboot)/springboot-env.yaml

Let me know if i'm wrong

**Comment by sparrownut** [comment]
some of waf will&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 21, 2022 14:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [projectdiscovery/nuclei-templates] [nuclei-template] Actuator-Unauthorized (Issue #6114)




 
@sparrownut we already have a template for this nuclei-templates/misconfiguration/springboot/springboot-env.yaml
 
Let me know if i'm wrong
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.




Many wafs will block existed template. For example, multiple targets in my recent scan will be blocked by the waf. My submitted template can bypass the basic wafs.Message ID: ***@***.***&gt;

**Comment by sparrownut** [comment]
> p

thanks ^^
