### ISSUE TITLE
I found a error in "default-logins/others/kingsoft-v8-default-login.yaml"

### ISSUE THREAD

**Issue by zlgxzswjy** [projectdiscovery/nuclei-templates#6124]
### Command to reproduce:
run : nuclei -debug -t  /root/.local/nuclei-templates/default-logins/others/kingsoft-v8-default-login.yaml -u http://x.x.x.x

This template uses the “md5” function to evaluate the “password” parameter and send the packet. However, the {{md5("{{password}}")}} in the template does not evaluate to md5 value, it needs to be {{md5("§password§")}}. In addition, I suspect that there are a number of templates in "default-logins" that are written incorrectly like this

incorrect:
![image](https://user-images.githubusercontent.com/12388719/203252131-ba4b5a9d-505e-4c0d-ac08-a1a801949947.png)

right:
![image](https://user-images.githubusercontent.com/12388719/203252248-c3d2dcf7-9be6-4b55-adff-404f04282c64.png)

**Comment by ehsandeep** [comment]
@zlgxzswjy this is a known issue with the nuclei engine that got fixed as part of https://github.com/projectdiscovery/nuclei/issues/2789 in the `dev` branch, and new release will be published in a week.
