### ISSUE TITLE
[Bug] cannot able to use workflows

### ISSUE THREAD

**Issue by Dixith1999** [projectdiscovery/nuclei-templates#616]
**Nuclei version**

```
nuclei -version 
```

**Nuclei template version**

```
cat ~/.nuclei-config.json
```

**Describe the bug**
cannot able to use workflows
saying templates not found
i have the latest version and updated my templates also

**Commands to reproduce**

```
nuclei -t xxx -target xxx
```

**Screenshots**

**Comment by bauthard** [comment]
Hi @Dixith1999, 

Please see this issue https://github.com/projectdiscovery/nuclei/issues/398 for details.
