### ISSUE TITLE
Insecure Firebase Check false positive if put method is enabled

### ISSUE THREAD

**Issue by fail-open** [projectdiscovery/nuclei-templates#6217]
### Nuclei Version:

2.7.9

### Template file:

misconfiguration/google/insecure-firebase-database.yaml

### Command to reproduce:

This likely isnt an issue, but in a case where put method is generically enabled on a host, this template will also flag it as insecure firebase since all it does is put a file and check for the file. Not sure if it can be tweaked to be more specific to spotting firebase.

**Comment by DhiyaneshGeek** [comment]
@akincibor i have updated the template and raised a PR #[6367](https://github.com/projectdiscovery/nuclei-templates/pull/6367), let me know if this works , thanks for raising the issue 😄
