### ISSUE TITLE
False positive npmrc-authtoken

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#6218]
Output: `# //npm.pkg.github.com/:_authToken=${GITHUB_NPM_TOKEN}`

**Comment by DhiyaneshGeek** [comment]
@akincibor Thanks for raising the issue

was there no token leaked ?

**Comment by akincibor** [comment]
Yes no token was leaked.

**Comment by DhiyaneshGeek** [comment]
@akincibor i'm looking into it thanks for flagging the issue 👍
