### ISSUE TITLE
Refactoring directory structure to improve visibility of protocols and templates

### ISSUE THREAD

**Issue by princechaddha** [projectdiscovery/nuclei-templates#6279]
I am creating this issue to propose and discuss the idea of refactoring the directory structure in the nuclei-templates repository. The goal of this refactoring effort would be to better organize and categorize the templates based on the protocols they use

This will make it easier to find and understand the different protocols that we support and will keep the repository neat and organized. The new directory structure will increase visibility around the different protocols, making it easier for contributors and users to navigate the repository and find the templates that they are looking for. 

We plan to move all of the web templates from the root directory to a new `http` folder. In addition, we will move all of the CVEs to the relevant protocol directories. For example, all of the network-related CVEs will be moved to the network directory, and all of the web-related CVEs will be moved to the `http` directory

**Comment by vzamanillo** [comment]
In my opinion, I don't know if the best way to organize the templates is by directories, I mean, not that it's bad, but maybe the templates should be organized differently. Imagine for a moment we take all the templates from each directory and put them in a single directory, there is no longer any organization and the only possible way to find a template would be to search for tags. I think that the organization of the templates should not depend on where they are located in the file system. Maybe using a hybrid directory model + a new template category attribute would make it easier. I don't know, but I imagine the templates as rows in a database table, with their attributes and properties, the important thing is to have a good search engine.

**Comment by dm-ct** [comment]
This would be really useful, especially if protocol support in Nuclei expands to more non-HTTP protocols, would make it far easier to "put stuff in the right place" or just "find stuff" in general.
