### ISSUE TITLE
False positive insecure-firebase-database.yaml

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#6285]
Hi,

This template does not verify if it is really a firebase issue. The issue I discovered was a PUT request enabled on the host but it was not related to firebase.

**Comment by DhiyaneshGeek** [comment]
@akincibor i have updated the template and raised a PR #[6367](https://github.com/projectdiscovery/nuclei-templates/pull/6367), let me know if this works , thanks for raising the issue 😄
