### ISSUE TITLE
PyPI server detect

### ISSUE THREAD

**Issue by ocervell** [projectdiscovery/nuclei-templates#6297]
### Nuclei Version:
latest

### Template file:
technologies/pypi-server-detect.yaml

is detecting PyPI server, seems like the body matchers do not work as there is no PyPI string in the body.

**Comment by DhiyaneshGeek** [comment]
@ocervell could you provide more info, is it like the PyPi string is not present in the body and the application is running on PyPI technology ?

Let me know if i'm wrong 😄

**Comment by jordanpotti** [comment]
It's missing `matchers-condition: and`
