### ISSUE TITLE
False positive matches for WordPress Plugins

### ISSUE THREAD

**Issue by ricardomaia** [projectdiscovery/nuclei-templates#6431]
Hi @ricardomaia,

Could you test for 'https://join.beaxy.com' ? some template generate false positive.

`nuclei -u https://join.beaxy.com -t technologies/wordpress/plugins`

_Originally posted by @akincibor in https://github.com/projectdiscovery/nuclei-templates/issues/6424#issuecomment-1365108827_

**Comment by ricardomaia** [comment]
This behavior was caused by inline CSS comment present into page source code.

![image](https://user-images.githubusercontent.com/1353811/209565087-70710764-c14e-48f7-9fda-376487f4723b.png)

I'll try to figure out how to modify the regex rule and avoid matching in cases like this.

**Comment by akincibor** [comment]
What about adding `Content-Type: text/plain` as an extra match ?

**Comment by ricardomaia** [comment]
> What about adding `Content-Type: text/plain` as an extra match ?

I don't think it's necessary, and I have concerns that adding stricter rules could affect detection and generate false negatives under some conditions.

For example... I'm using about 215 targets in my tests for model validation and your problem is the first of its kind. It is more prudent, I think, to wait for concrete situations where the content type is needed and modify the templates step-by-step.

What do you think?

By the way... I submit a PR to regenerate the templates fixing this issue and am waiting for approval, merge and GitHub action cron scheduling.
