### ISSUE TITLE
dir-listing case-sensitive problem

### ISSUE THREAD

**Issue by hczdmr** [projectdiscovery/nuclei-templates#6454]
### Nuclei Version:

2.8.3

### Template file:

/[miscellaneous](https://github.com/projectdiscovery/nuclei-templates/tree/main/miscellaneous)/dir-listing.yaml

### Command to reproduce:
nuclei -u http://177.220.141.2:8080/webdav/ -t /opt/nuclei-templates/miscellaneous/dir-listing.yaml

### Anything else:
Template works as case-sensitive. Because of that it can not find this vulnerability. You can fix it using "case-insensitive: true" option.

**Comment by ritikchaddha** [comment]
Hello @hczdmr, Thank you for pointing this out and contributing to this project. Your efforts are greatly appreciated. Cheers! 🍻 
I've created a PR https://github.com/projectdiscovery/nuclei-templates/pull/6495 for this issue and added you as a co-author.
