### ISSUE TITLE
base64 the BaseURL variable

### ISSUE THREAD

**Issue by 0xspade** [projectdiscovery/nuclei-templates#6513]
Hi Team,

I'm trying to create a custom nuclei template however, I can't make it right, currently I need to base64 the {{BaseURL}} value. so the GET parameter should be like this `{{BaseURL}}/some-endpoint?param={{base64( {{BaseURL}}/internalfileshere )}}&param=test`.

I already tried to create a variable but no luck. Can someone help me?

**Comment by ritikchaddha** [comment]
Hello @0xspade, you can use the below to get the base64 of `{{BaseURL}}`, you are just missing the double quote.
`- '{{BaseURL}}/some-endpoint?param={{base64("{{BaseURL}}/internalfileshere")}}&param=test'`

**Comment by 0xspade** [comment]
That does it. Thanks for the help @ritikchaddha :)
