### ISSUE TITLE
[issue] aws.interact.sh: SERVFAIL

### ISSUE THREAD

**Issue by dogasantos** [projectdiscovery/nuclei-templates#6536]
Hey guys,
it seems that you have a DNS record (aws.interact.sh) as requirement for this template, but it's not set as it produces SERVFAIL:

``` 
nslookup aws.interact.sh
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find aws.interact.sh: SERVFAIL
```

template: https://github.com/projectdiscovery/nuclei-templates/blob/main/misconfiguration/proxy/metadata-aws.yaml

Do you have/maintain the proper record to me patched here?

Ty

**Comment by DhiyaneshGeek** [comment]
Hi @dogasantos It is working as intended , can you try again now 

Thank you 

![image](https://user-images.githubusercontent.com/24750220/212525888-3b4cefb8-2671-45b9-b473-17ef5892360a.png)

**Comment by ehsandeep** [comment]
@dogasantos @DhiyaneshGeek `interact.sh` is deprecated interactsh server, so I've updated them with one of the current server.
