### ISSUE TITLE
CNVD-2022-03672.yaml invalid regex

### ISSUE THREAD

**Issue by SleepingBag945** [projectdiscovery/nuclei-templates#6574]
<img width="342" alt="图片" src="https://user-images.githubusercontent.com/100852628/213858307-c9573abc-ea51-4310-8ead-43f29c6c7b80.png">

cnvd/2022/CNVD-2022-03672.yaml 模板的正则表达式错误。这会导致verify_string字段匹配出错导致漏洞验证失败。
<img width="616" alt="图片" src="https://user-images.githubusercontent.com/100852628/213858237-691a372d-b865-4f4b-86f4-7cf3cfd27dac.png">

请将
 '"verify_string":"(.\*)"'
改为
'"verify_string":"(.\*?)"'
<img width="332" alt="图片" src="https://user-images.githubusercontent.com/100852628/213858366-84386ddb-01fb-4c1c-9abb-153699389d04.png">
这样能正确匹配到verify_string
<img width="602" alt="图片" src="https://user-images.githubusercontent.com/100852628/213858420-938d862b-1495-4964-a657-e67f66ef3dba.png">

**Comment by ritikchaddha** [comment]
Hello @SleepingBag945, Thank you for pointing this issue out, really appreciate your contribution to this project 🍻 

Create a PR for this https://github.com/projectdiscovery/nuclei-templates/pull/6688
