### ISSUE TITLE
There is a weird second misconfiguration directory present in the root file structure of the repository

### ISSUE THREAD

**Issue by praetorian-thendrickson** [projectdiscovery/nuclei-templates#6602]
```
https://github.com/projectdiscovery/nuclei-templates/tree/main/%E2%80%8E%E2%80%8Emisconfiguration
```
and
```
https://github.com/projectdiscovery/nuclei-templates/tree/main/misconfiguration
```
Are both present. It looks like something weird happened and the second misconfiguration folder was created, but the other characters present in the file name don't render in the github ui

**Comment by DhiyaneshGeek** [comment]
Hi @praetorian-thendrickson Thank you so much for flagging the issue

we have raised a PR [6605](https://github.com/projectdiscovery/nuclei-templates/pull/6605) , and fixed the issue

Let us know if the changes work !

Thank you :)

**Comment by praetorian-thendrickson** [comment]
thanks looks fixed to me!
