### ISSUE TITLE
ruijie-password-leak.yaml is not valid

### ISSUE THREAD

**Issue by JiaDuo** [projectdiscovery/nuclei-templates#6654]
### Issue description:

There is a fixed md5 value in the comments of the Ruijie UAC device administrator login code, but this md5 value is not the md5 of the login password, but the md5 value of 654321, because actually this is not a vulnerability.

All this is not a security issue.

**Comment by DhiyaneshGeek** [comment]
Hi @JiaDuo We have fixed the template to detect the passwords of different user level such as super_admin, guest_admin, reporter_admin #6686

Thanks for flagging the issue 😄 

Feel free to re-open the issue if it doesn't fix the issue !
