### ISSUE TITLE
Duplicate Exposed Panels Folder

### ISSUE THREAD

**Issue by AdamCrosser** [projectdiscovery/nuclei-templates#6704]
I noticed that there are two exposed-panels folders in the Nuclei repository. I noticed one of them has non-printable characters in the file name which seemed a little strange. Using the -b flag in the ls command you can view non-printable characters in file names.

![exposed-panels1](https://user-images.githubusercontent.com/45573557/217643446-fc2413be-fe8a-43c9-bad9-891559675ed5.png)

When I examine that directory there is just a single template. 

<img width="525" alt="Screen Shot 2023-02-08 at 2 24 22 PM" src="https://user-images.githubusercontent.com/45573557/217643561-3fb3f878-7284-49ee-85d4-9343bb108411.png">

Do we want to move this vertex tax template into the exposed-panels folder and delete the version of the exposed-panels folder containing non-printable characters?

**Comment by ritikchaddha** [comment]
Hello @AdamCrosser, Thank you for bringing this to our attention. Because some characters were added accidentally, the error was caused. This commit  [eea66d3](https://github.com/projectdiscovery/nuclei-templates/commit/eea66d32a29e2968d7057e2834798bf14e4cdf42) contains an update for this issue.
