### ISSUE TITLE
Is there a problem with this line?

### ISSUE THREAD

**Issue by AbelChe** [projectdiscovery/nuclei-templates#6744]
https://github.com/projectdiscovery/nuclei-templates/blob/bfe9f92f07a7be9131d884bbab097b1a4c540034/network/enumeration/mongodb-info-enum.yaml#L14

**Comment by No-Github** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/18167071/218709949-db33aa96-a155-4177-8b0c-26b5837976f7.png">
缩进格式问题吧
