### ISSUE TITLE
Osint templates

### ISSUE THREAD

**Issue by zeroc00I** [projectdiscovery/nuclei-templates#6761]
Hello folks!
Does Nuclei team have an interest on open contributions to OSINT templates?
I was imagining to contributing your project with something like the Sherlock (https://github.com/sherlock-project/sherlock) tools does: fetch a username across many social media platforms.

Would this be interesting?

**Comment by DhiyaneshGeek** [comment]
Hi @zeroc00I Yes, you can contribute. feel free to raise a PR 

If you need any help with creation of the template, you can join our [discord server ](https://discord.gg/projectdiscovery)

**Comment by princechaddha** [comment]
Hi @zeroc00I, Thank you for taking the time to create this issue and for contributing to this project 🍻
