### ISSUE TITLE
Issue with resolving version api (hosted on cloudflare) failing to install templates

### ISSUE THREAD

**Issue by cyb3rzest** [projectdiscovery/nuclei-templates#6794]
After removing and installing multiple times, using go install command as well as apt install nuclei, getting this below error

```console
┌──(root💀ViTi-Security)-[~]
└─# nuclei -ut
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.9
		projectdiscovery.io

[INF] nuclei-templates are not installed, installing...
[ERR] Could not update templates: Version string empty
```                                                                                      
Not only this, have manually downloaded the templates, and validated it, still giving the same error.

```console                                                                                                  
┌──(root💀ViTi-Security)-[~]
└─# nuclei -validate /root/nuclei-templates 
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.9
		projectdiscovery.io
[INF] All templates validated successfully
                                                                                                               
┌──(root💀ViTi-Security)-[~]
└─# nuclei -ut                             
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.9
		projectdiscovery.io
[INF] nuclei-templates are not installed, installing...
[ERR] Could not update templates: Version string empty
```

**Comment by DhiyaneshGeek** [comment]
Hi @cyb3rzest is it possible share the some info regarding which operating system you are trying to install

**Comment by cyb3rzest** [comment]
> Hi @cyb3rzest is it possible share the some info regarding which operating system you are trying to install

Hi, I am using Kali Linux 2022.4, temporarily fixed it, but its needed to be rectified

**Comment by cyb3rzest** [comment]
@DhiyaneshGeek its not fixed till now.
Could not update templates: could not read configuration file: EOF
![image](https://user-images.githubusercontent.com/29830064/223430144-6f886338-7ecf-431c-a2ed-c4ac944aff61.png)

**Comment by Mzack9999** [comment]
Can you provide more context about kali linux version? Is it running in a container? In a virtualized environment (eg. VirtualBox)?

Could you post the output of `nuclei -hc`?

Thanks!

**Comment by derekmurawsky** [comment]
I'm having the same issue, MacOS Ventura 13.1, Macbook M1. It's a clean install via brew. 

### Steps to reproduce:

1. rm -rf ~/.config/nuclei
2. brew remove nuclei
3. brew install nuclei
4. nuclei -ut

<img width="443" alt="image" src="https://user-images.githubusercontent.com/3741839/230497300-7d0b63e4-ee92-4690-89f6-e0180c6a391f.png">

I do have dns configured to use pihole, but tried with it enabled as well as disabled. I killed mdnsresponder in between tests as well (that should flush the local dns cache). 

This is working for me via a github action, though.

**Comment by derekmurawsky** [comment]
I was able to install it from another machine on my network, so there's clearly something up with my mac. I'll keep poking at it and post anything I find here. 

I did notice that even curl would take a long time to start from within my shell (iterm2/zsh). I'll start poking there.

**Comment by ehsandeep** [comment]
@derekmurawsky Yes, looks like some dns issue on the system, Can you try with using `-sr` option as well?

```
   -sr, -system-resolvers  use system DNS resolving as error fallback
```

**Comment by derekmurawsky** [comment]
> @derekmurawsky Yes, looks like some dns issue on the system, Can you try with using `-sr` option as well?
> 
> ```
>    -sr, -system-resolvers  use system DNS resolving as error fallback
> ```

It's definitely something specific to my terminal. Brave works, sshing to a local server and doing it there works, but curl takes exactly 30.x seconds, which screams DNS timeout or similar. The output of the SR command was:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/3741839/230627343-5b70b43f-4dee-4b63-aeb8-a3ccb8d70f6d.png">

I'm going to spend some time debugging my zsh config to see if I can isolate the problem.

**Comment by ehsandeep** [comment]
I updated the title based on what we know about this issue.

Users reported nuclei failed to resolve version API (hosted on Cloudflare), failing to install templates / ignore file.

### How to reproduce this?

We still don't know how to replicate this on our side as only a few of the users are facing this issue, and most of the time, running nuclei on 
- Kali OS
- Behind VPN / Proxy

**Comment by Mzack9999** [comment]
At current time with latest kali linux the issue appears to be standard certificates not installed on the system:
```console
# nuclei -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.4

                projectdiscovery.io

[WRN] failed to update nuclei templates: [:RUNTIME] failed to install templates at /root/.local/nuclei-templates <- [:RUNTIME] Get "https://api.github.com/repos/projectdiscovery/nuclei-templates/releases/latest": x509: certificate signed by unknown authority
[ERR] Could not find template '/root/.local/nuclei-templates': no templates found in path /root/.local/nuclei-templates
[INF] Current nuclei version: v2.9.4 (latest)
[INF] Current nuclei-templates version:  (outdated)
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no valid templates were found
```
It can be fixed generally by installing the following packages:
```console
$ sudo apt install git curl build-essential
```

**Comment by princechaddha** [comment]
Due to inactivity, we are closing this issue. Please don't hesitate to create a new issue if you encounter any bugs or have any questions regarding template writing. Feel free to join our [Discord server](https://discord.com/invite/projectdiscovery)
