### ISSUE TITLE
Github Recovery Code in keys produce a lot of FPs

### ISSUE THREAD

**Issue by brabbit10** [projectdiscovery/nuclei-templates#6799]
### Nuclei Version:

v2.8.9

### Template file:

/file/keys/github-recovery-code.yaml

### Command to reproduce:

This template produces FPs in almost any mobile app (decompiled apk and ipa).
Need to demote this to informative or at least low, or fine-tune the match
Also its not in the github folder in the keys folder.

**Comment by brabbit10** [comment]
Examples of FPs:

![image](https://user-images.githubusercontent.com/62747128/221415234-135ab9b5-82e6-47a1-be71-670537c50cd0.png)

![image](https://user-images.githubusercontent.com/62747128/221415311-6233524c-efe6-48a1-938c-908975f1dc29.png)

**Comment by princechaddha** [comment]
Hi @brabbit10, Thank you for taking the time to create this issue and for contributing to this project 🍻
