### ISSUE TITLE
Replace CVSSv3.0 scores with CVSSv3.1 

### ISSUE THREAD

**Issue by sullo** [projectdiscovery/nuclei-templates#6824]
Templates contain CVSSv3.0 scores. They should be upgraded to CVSSv3.1 scores. 

Currently there are 1542 templates which have version 3.0 scores.

### Please describe your feature request:
Templates should be consistent in which version of CVSS is used.

### Describe the use case of this feature:
Consistent reporting for our customers.

**Comment by ehsandeep** [comment]
Closing this one to avoid manual work; instead, templates are automatically updated based on information available from NVD, keeping CVSS 3.1 on priority when available.
