### ISSUE TITLE
False Negative: http-etcd-unauthenticated-api-data-leak

### ISSUE THREAD

**Issue by nibiwodong** [projectdiscovery/nuclei-templates#6851]
### Command to reproduce:
nuclei -u http://x.x.x.x:2379 -t ./nuclei-templates/misconfiguration/etcd-unauthenticated-api.yaml

The Content-Type in HTTP response header should be application/json, but not text/plain

https://github.com/projectdiscovery/nuclei-templates/blob/main/misconfiguration/etcd-unauthenticated-api.yaml
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/17465789/223328546-834c6774-4df6-461b-8eef-31baab19e289.png">

**Comment by ehsandeep** [comment]
@nibiwodong thanks for reporting, should be fixed with https://github.com/projectdiscovery/nuclei-templates/pull/6852
