### ISSUE TITLE
react config exposure

### ISSUE THREAD

**Issue by random-robbie** [projectdiscovery/nuclei-templates#6861]
```
id: react-app-env-js

info:
  name: React App Environment Js
  author: random-robbie
  severity: medium
  reference: Sometimes contains secrets.
  metadata:
    verified: true
  tags: react,exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/env.js"
      - "{{BaseURL}}/config.js"
    
    
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "REACT_APP_"

        condition: and

      - type: word
        part: header
        words:
          - "application/octet-stream"
          - "application/javascript"

      - type: status
        status:
          - 200
  ```

**Comment by DhiyaneshGeek** [comment]
Hi @random-robbie Thanks raising the issue and sharing this template 

i did a Github Code Search Query for a look

https://cs.github.com/?q=REACT_APP_%20language%3AJavaScript&scopeName=All%20repos&scope=

But i couldn't find any sensitive secrets, is there any other matcher we can add ?

Let me know if i'm wrong :)

**Comment by random-robbie** [comment]
From a work perspective i've seen loads of API keys and other keys hidden in these files.
bug bounty wise i've had no hits but i know it's possible to find all sorts of api endpoints and keys from it.

**Comment by DhiyaneshGeek** [comment]
Hi @random-robbie i have added the template https://github.com/projectdiscovery/nuclei-templates/commit/c4ef1d54226cf37a185c03521b50da9d79204498

Thank you so much for sharing this template with the community !
