### ISSUE TITLE
XSS Template

### ISSUE THREAD

**Issue by Divesh2003** [projectdiscovery/nuclei-templates#6878]

**Comment by Divesh2003** [comment]
Assign me this issue

**Comment by ritikchaddha** [comment]
Hello @Divesh2003, could you please specify which issue you referring to?

**Comment by Divesh2003** [comment]
Actually which helps user to get the XSS vulnerability from the nuclei template

Assign this to me

**Comment by ritikchaddha** [comment]
Could you please clarify with a reference, which XSS issue you are referring to? Unfortunately, we are not able to assign issues/PRs to contributors, but you are welcome to create a PR for any issue you like and include yourself as an author.”

**Comment by Divesh2003** [comment]
Sure

**Comment by princechaddha** [comment]
Hi @Divesh2003, thank you for creating this PR. However, we are not certain about what the issue is about. 

In case you need any assistance with writing or submitting templates, you can join our [Discord server](https://discord.com/invite/projectdiscovery). We are always happy to help.
