### ISSUE TITLE
[false-positive] basic-auth-bruteforce is a lot of noise

### ISSUE THREAD

**Issue by 0xspade** [projectdiscovery/nuclei-templates#690]
**Nuclei version**

```
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current Version: 2.2.0
```

**Nuclei template version**

```
Latest
```

**Template ID**

`fuzzing/basic-auth-bruteforce.yaml`

**Comment by geeknik** [comment]
To be fair, it's kind of meant to be targeted against known basic auth endpoints and not every endpoint in your test run.

**Comment by team-projectdiscovery** [comment]
Hi @0xspade, 

As geeknik pointed out, this is expected and you should not be running `fuzzing` folder as in general unless you identified a specific target to run this template, we have also added this folder in the default ignores list, but it will only work if you are using nuclei templates using `update-template` flag, closing as this is expected.

![image](https://user-images.githubusercontent.com/8293321/102586439-2e8a8e00-4130-11eb-9a9d-494beda9dc5a.png)
