### ISSUE TITLE
`mismatched-ssl-certificate` template does not validate wildcard certificate is in use

### ISSUE THREAD

**Issue by mardinyadegar** [projectdiscovery/nuclei-templates#6919]
### Nuclei Version:

2.9.0

### Template file:

[nuclei-templates](https://github.com/projectdiscovery/nuclei-templates)/[ssl](https://github.com/projectdiscovery/nuclei-templates/tree/main/ssl)/mismatched-ssl-certificate.yaml

### Command to reproduce:

Running nuclei on such a host will lead to a false positive:

```bash
% nuclei -u http://api.isbx.uw2.eng.grxweb.com. -t ssl/mismatched-ssl-certificate.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.0

		projectdiscovery.io

[INF] Using Nuclei Engine 2.9.0 (latest)
[INF] Using Nuclei Templates 9.3.9 (latest)
[INF] Templates added in last update: 61
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[mismatched-ssl-certificate] [ssl] [low] api.isbx.uw2.eng.grxweb.com.:443 [CN: *.isbx.uw2.eng.grxweb.com]
```

### Anything else:
See command above.

**Comment by ehsandeep** [comment]
@mardinyadegar, thanks for flagging this, this is an issue with tlsx (integrated into nuclei) and is being tracked here - https://github.com/projectdiscovery/tlsx/issues/217, template will be indirectly fixed after updating/fixing bug in tlsx.

**Comment by ehsandeep** [comment]
@mardinyadegar isn't it the trailing dot in your input causing the issue?

Nuclei run without trailing dot in dns input.

```console
$ nuclei -u http://api.isbx.uw2.eng.grxweb.com -t ssl/mismatched-ssl-certificate.yaml -silent
```

Nuclei run with trailing dot in dns input.

```console
$ nuclei -u http://api.isbx.uw2.eng.grxweb.com. -t ssl/mismatched-ssl-certificate.yaml -silent
[mismatched-ssl-certificate] [ssl] [low] api.isbx.uw2.eng.grxweb.com.:443 [CN: *.isbx.uw2.eng.grxweb.com]
```

**Comment by mardinyadegar** [comment]
There's a chance that the trailing dot is causing the issue.

**Comment by pussycat0x** [comment]
@mardinyadegar This issue is now closed. Please feel free to reopen it if you have any further queries.
