### ISSUE TITLE
Spartacus template broken

### ISSUE THREAD

**Issue by Techbrunch** [projectdiscovery/nuclei-templates#7008]
### Template file:

The modifications made to the template broke it, please revert the latest changes:

https://github.com/projectdiscovery/nuclei-templates/pull/4937#issuecomment-1490543129

**Comment by princechaddha** [comment]
Hello @Techbrunch, Thank you for taking the time to create this issue and for contributing to this project 🍻

I have added it based on `https://publicwww.com/websites/%22%3Ccx-storefront%22/` but I believe utilizing a headless template would be a more effective approach to detect it. I will revert the changes.
