### ISSUE TITLE
MSSQL detect

### ISSUE THREAD

**Issue by olearycrew** [projectdiscovery/nuclei-templates#7064]
### Template for?

We have a great template for PQ and MySQL - `mysql-detect` and `pgsql-detect` but I don't see one looking for MSSQL on port 1433. We should add one...not sure other than the port what matchers to use so I opened this issue for discussion

### Details:
See https://github.com/projectdiscovery/nuclei/discussions/3374 for more details

**Comment by pussycat0x** [comment]
issue created #[3609](https://github.com/projectdiscovery/nuclei/issues/3609)

**Comment by pussycat0x** [comment]
Mssql detection template created [mssql-detect.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/javascript/detection/mssql-detect.yaml)
