### ISSUE TITLE
[false-positive] 

### ISSUE THREAD

**Issue by int3dev-cyber** [projectdiscovery/nuclei-templates#708]
False Positive Template : 
https://github.com/projectdiscovery/nuclei-templates/blob/master/vulnerabilities/wordpress-emails-verification-for-woocommerce.yaml

[wp-woocommerce-email-verification] [http] [critical] https://bugcrowd.com/blog/?alg_wc_ev_verify_email=eyJpZCI6MSwiY29kZSI6MH0=

<img width="1223" alt="Screenshot 2020-12-28 at 12 06 45 AM" src="https://user-images.githubusercontent.com/75508311/103177496-083bbf80-48a1-11eb-9abb-560713713366.png">

**Comment by bauthard** [comment]
@int3dev-cyber what version of nuclei you are running? I'm not able to reproduce this.

```bash
echo https://bugcrowd.com | nuclei -t vulnerabilities/wordpress-emails-verification-for-woocommerce.yaml

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.2.0

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [wp-woocommerce-email-verification] wordpress-emails-verification-for-woocommerce (@random-robbie) [critical]
[INF] Using 1 rules (1 templates, 0 workflows)
[INF] No results found. Happy hacking!
```

**Comment by bauthard** [comment]
Closing as this is not reproducible.
