### ISSUE TITLE
Could not run nuclei: no valid templates were found - wordpress-wp-cron.yaml file

### ISSUE THREAD

**Issue by kmskrishna** [projectdiscovery/nuclei-templates#7109]
while running the wordpress-wp-cron.yaml file nuclei says 

```
[INF] Current nuclei version: v2.9.2 (latest)
[INF] Current nuclei-templates version: 9.4.2 (latest)
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no valid templates were found
```

If we check if the template is valid using `-validate` flag, it says `[INF] All templates validated successfully.`

Even when I try to run using debug flag, it just says "could not run nuclei."

This is not the expected behaviour.

**Comment by ritikchaddha** [comment]
Hello there, @kmskrishna. This is the expected behavior because this template contains a 'dos' tag that prevents it from running by default. To execute this template, add '-tags dos' while running the nuclei command in CLI, or just remove the dos tag from the template.
Hope this helps!

**Comment by princechaddha** [comment]
Hi @kmskrishna, Thank you for taking the time to create this issue and for contributing to this project 🍻
