### ISSUE TITLE
gemfury takeover uses highly generic string

### ISSUE THREAD

**Issue by alexanderkjall** [projectdiscovery/nuclei-templates#7139]
### Nuclei Version:

[INF] Nuclei Engine Version: v2.9.2

### Template file:

takeovers/gemfury-takeover.yaml

### Command to reproduce:

docker run -it --rm projectdiscovery/nuclei -u status.vg.no -t takeovers/gemfury-takeover.yaml

### Anything else:

The string "404: This page could not be found." is extremely generic: https://github.com/projectdiscovery/nuclei-templates/blob/main/takeovers/gemfury-takeover.yaml#L24

The check triggered a couple of false positives for us.

**Comment by Johannes-Andersen** [comment]
It’s worth noting the string matches the default next.js 404 page

https://github.com/vercel/next.js/blob/da2804f9746c9e676d2ae4a9f619c2c5f9f62d7d/packages/next/src/client/components/error.tsx#L42

we “resolved” the issue by creating a custom 404 page to not match on that string anymore
