### ISSUE TITLE
Templates warning ⚠️

### ISSUE THREAD

**Issue by itsrvsingh** [projectdiscovery/nuclei-templates#7198]
![IMG_20230509_004729](https://user-images.githubusercontent.com/78691282/236912940-70c2f206-c55b-48e6-b43e-b59ea0899f7b.jpg)

**Comment by ehsandeep** [comment]
@itsrvsingh please refer to https://github.com/projectdiscovery/nuclei/issues/3662#issuecomment-1538836954
