### ISSUE TITLE
Springboot heapdump - gzip causes false detection

### ISSUE THREAD

**Issue by DShelef** [projectdiscovery/nuclei-templates#7271]
### Template file:
http/misconfiguration/springboot/springboot-heapdump.yaml

### Anything else:
If a website supports compression (`Accept-Encoding: gzip`) then the issue would be detected no matter what because of the gunzip header.
![image](https://github.com/projectdiscovery/nuclei-templates/assets/88281521/d2553cf6-d2aa-44f3-a77e-06b0ffa641d8)
Maybe it is worth to remove it, or check for the output's length as well.

**Comment by princechaddha** [comment]
Hey @DShelef, I've made the changes to the template. Could you please verify if the made changes fixed the false positive result? #7287

**Comment by ertygiq** [comment]
I think that 'Accept-Encoding' should be replaced with 'Content-Encoding'

**Comment by princechaddha** [comment]
@ertygiq Thanks for your response! I've made the change at https://github.com/projectdiscovery/nuclei-templates/commit/ca42f1af4decfc92dff98284b0319813b79dd480.

**Comment by DShelef** [comment]
@princechaddha This version doesn't produce false-positive.
Thanks.
