### ISSUE TITLE
[Feature] Split Up Large Templates Such As springboot-detect

### ISSUE THREAD

**Issue by wdahlenburg** [projectdiscovery/nuclei-templates#729]
**Is your feature request related to a problem? Please describe.**

I have been doing some analysis to see how to speed up Nuclei/make better use of CPU time and found that templates that contain a large number of endpoints end up taking a longer time than they need to.

A strong example is the springboot-detect template, which is an excellent template to have, however it has nearly 60 requests that it makes sequentially. Some of those requests are on a different port, which can add the timeout to the total template time.

**Describe the solution you'd like**

There are two solutions that I can think of.

The first solution is to split out large templates that don't require sequential requests into smaller templates. 

In the springboot-detect template an example of a sub-template would be:

```yaml
id: springboot-actuators-jolokia
...
requests:
  - method: GET
    path:
      - "{{BaseURL}}/jolokia"
      - "{{BaseURL}}/jolokia/list"
      - "{{BaseURL}}:8090/jolokia"
      - "{{BaseURL}}:8090/jolokia/list"
```

This solution allows for more granular criteria, which will hopefully lead to less false positives. Additionally, it allows for nuclei users that use the "-c" flag to run all of the sub-templates in parallel instead of a slow sequential template. Another benefit is that the severity could be updated to reflect the actual risk. Medium is decent for some of the actuators, but items like heapdump, env, and trace can easily become critical severity.

The downside is obviously that the number of templates increase. I'm not sure if there has been any guidance on when to split up templates, but I think it's worth considering.

I prefer this solution due to the granularity and speed improvements. 

The second solution would be to allow users to spin up additional go routines per template to process large templates in parallel. Templates that require sequential requests could opt-out of this behavior. I think the flags could become a little confusing for users that think they are currently making concurrent requests with "-c".

An example of this would be to see that there are multiple paths in a template, so make N requests at a time before moving on to the next set of requests. N could be a default of 5-10, but be another command line flag.

If N was 5, then 5 initial requests would be sent out, and the first one that is completed will pick up /actuator/conditions. Nuclei would iterate over the list until it was completed.

```
- "{{BaseURL}}/actuator"
- "{{BaseURL}}/actuator/auditevents"
- "{{BaseURL}}/actuator/auditLog"
- "{{BaseURL}}/actuator/beans"
- "{{BaseURL}}/actuator/caches"
- "{{BaseURL}}/actuator/conditions" 
```

**Comment by bauthard** [comment]
Hi @wdahlenburg, 

+1 for the idea of splitting the template, this template can be simplified and divided into many with unique matches, not only it will improve the detection it will also help to resolve other problems you have listed.

> The downside is obviously that the number of templates increases. I'm not sure if there has been any guidance on when to split up templates, but I think it's worth considering.

The number of templates is not an issue for the project, we encourage to have separate templates for anything that has unique paths, grouping template is advised only when you have the same path for multiple detections which is not the case here.

**Comment by bauthard** [comment]
Closing, as this is implemented.
