### ISSUE TITLE
[Feature] check for 401 before running basic-auth-bruteforce template

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei-templates#739]
Is there any way we can make nuclei to run basic-auth-bruteforce after checking the url provided returns 401? otherwise we have to exclude it from all scans most of the time or it gives all false positives

**Comment by bauthard** [comment]
Hi @marcelo321, 

If you are updating templates with `-update-templates` and using the same to run nuclei templates, this template including all templates in the fuzzing folder is ignored from default run using `.nuclei-ignore` file, you can check out the excluded folders here https://github.com/projectdiscovery/nuclei-templates/blob/master/.nuclei-ignore, it will only an issue if you are running nuclei templates from a custom location without `.nuclei-ignore` file, Can you confirm how you are running nuclei?

**Comment by bauthard** [comment]
We have removed and moved this template to another branch https://github.com/projectdiscovery/nuclei-templates/commit/29803150301fa2217c5ef325e67269672aad0603
