### ISSUE TITLE
Subdomain Takeover Addition

### ISSUE THREAD

**Issue by KingOfTheNOPs** [projectdiscovery/nuclei-templates#7415]
### Template Information:

Subdomain takeover template: https://github.com/projectdiscovery/nuclei-templates/blob/8b2bc8ab8ef801d4342bb4ec4fedb5460296da29/subdomain-takeover/detect-all-takeovers.yaml

In some cases, the page that resolves contains the information listed below. Adding the yaml addition to the current config would help with some false negative situations. 

### Nuclei Template:

```yaml
      - type: word
        name: googlebot
        words:
          - <meta name=\"googlebot\"
          - Error. Page cannot be displayed. Please contact your service provider for more details

```

**Comment by ritikchaddha** [comment]
Due to inactivity, we are closing this issue. Please feel free to open a new PR with more information.
