### ISSUE TITLE
[false-positive] 

### ISSUE THREAD

**Issue by zinminphyo0** [projectdiscovery/nuclei-templates#746]
**Nuclei version**

```
v2.2.0
```

**Nuclei template version**

```
v7.3.7
```

**Template ID**

basic-auth-bruteforce.yaml

**Comment by bauthard** [comment]
We have removed and moved this template to another branch. https://github.com/projectdiscovery/nuclei-templates/commit/29803150301fa2217c5ef325e67269672aad0603

**Comment by zinminphyo0** [comment]
Thank you
