### ISSUE TITLE
[Bug] wordpress-xmlrpc-file shows no results found despite application vulnerable

### ISSUE THREAD

**Issue by 0ut0fb4nd** [projectdiscovery/nuclei-templates#764]
**Nuclei version**

```
nuclei -version - v 2.2.0
```

**Nuclei template version**

v 8.0.1
cat ~/.nuclei-config.json
{"templates-directory":"/root/nuclei-templates","current-version":"8.0.1","last-checked":"2021-01-20T09:04:23.844182195-05:00"}

**Template ID**

Please submit the ID template producing false-positive results. 

**Commands to Reproduce**

```
nuclei -t wordpress-xmlrpc-file -target ?
```

It was found that the yaml file includes the matcher of type status 405 which is absolutely correct. But despite the application is vulnerable and the response code shows 405, it displays No Results Found.

The quick fix in my opinion is to add another matcher of type regex that matches "XML-RPC server accepts POST requests only."

<img width="439" alt="XML-RPC-FIX" src="https://user-images.githubusercontent.com/8946000/105199130-69834580-5b64-11eb-97c9-d30b9d6a279d.png">

Also I would like to add additional path for xmlrpc detection:
path:
 - "{{BaseURL}}/blog/xmlrpc.php"

**Comment by bauthard** [comment]
This has been updated here https://github.com/projectdiscovery/nuclei-templates/commit/a98c2c6bb1751be37f5ccaef8e695ebd97ec3c09, thank you for creating an issue for this.
