### ISSUE TITLE
ColdFusion.yaml

### ISSUE THREAD

**Issue by shelu16** [projectdiscovery/nuclei-templates#7730]
id: ColdFusion

info:
  name: ColdFusion
  author: 0x240x23elu
  severity: info
  description: ColdFusion Panel Detect
 l
  classification:
    cve-id: colffusion
  tags: ColdFusion
  metadata:
    max-request: 5

http:
  - method: GET
    path:
      - '{{BaseURL}}//CFIDE/wizards/common/utils.cfc?method=wizardHash'

    stop-at-first-match: true
    matchers-condition: and
    matchers:

      - type: word
        part: body
        words:
          - "ColdFusion"
          - "INPASSWORD"

**Comment by DhiyaneshGeek** [comment]
Hi @shelu16 we already have a template to detect both [coldfusion login](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposed-panels/adobe/adobe-component-login.yaml) and [admin panel](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposed-panels/coldfusion-administrator-login.yaml)

So we are closing this issue 

Thank you 😄
