### ISSUE TITLE
[Bug] rocketmq borken unauth template is prone to false positives

### ISSUE THREAD

**Issue by malikashish8** [projectdiscovery/nuclei-templates#7790]
The match conditions are too trivial and cause a lot of false positives. They identify any system that has a word in the request `serializeTypeCurrentRPC` in the response and does not use HTTP/1.1. For example, python http server module also shows up as a false positive. To reproduce the issue run the server:
```sh
python3 -m http.server
```
And run the scan on the python server:
```sh
❯ nuclei -u localhost:8000 -t network/misconfig/apache-rocketmq-broker-unauth.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.6

		projectdiscovery.io

[INF] Current nuclei version: v2.9.6 (outdated)
[INF] Current nuclei-templates version: v9.6.0 (latest)
[INF] New templates added in latest release: 33
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[apache-rocketmq-broker-unauth] [tcp] [high] localhost:8000
```
This finds a false positive in python http server.

**Comment by 845318843** [comment]
It still has false positives on 2025
