### ISSUE TITLE
Untrusted root certificate FP

### ISSUE THREAD

**Issue by pentesttools-com** [projectdiscovery/nuclei-templates#7891]
### Anything else:

Nuclei gives an untrusted root certificate FP if the target's certificate chain contains extraneous certificate/s. For example if the Root Certificate is included in the certificate chain, nuclei will give this finding. While I know that including extraneous certificates in the certificate chain is not good practice as it is redundant I think the warning is not correct, as it should signal a different thing.

**Comment by ehsandeep** [comment]
@pentesttools-com, thanks for creating an issue for it, do you have an example/reference/host to better understand what you are sharing?

**Comment by pentesttools-com** [comment]
Yes, I could share an example in private, maybe a discord dm as suggested in the issue template?

**Comment by ehsandeep** [comment]
> @ehsandeep Yes, I could share an example in private, maybe a discord dm as suggested in the issue template?

Yes, please join https://discord.gg/projectdiscovery and ping me (@pdteam)
