### ISSUE TITLE
keycloak - admin panel

### ISSUE THREAD

**Issue by incogbyte** [projectdiscovery/nuclei-templates#790]
**Template Details**

Admin panel based on cure53 report https://cure53.de/pentest-report_keycloak.pdf

```
id: key-cloak-admin-panel

info:
  name: Keycloak Admin Panel
  author: incogbyte
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/auth/admin/master/console/"
    matchers:
      - type: word
        words:
          - "<a href=\"http://www.keycloak.org\">"
        condition: and
        part: body
```

**Comment by bauthard** [comment]
Thank you @incogbyte for sharing templates, this has been added here https://github.com/projectdiscovery/nuclei-templates/commit/c649ff4a85e6b42904bd10c7b8bd427c86be32b5.
