### ISSUE TITLE
api-tatum

### ISSUE THREAD

**Issue by 0xPugazh** [projectdiscovery/nuclei-templates#8013]
### Nuclei Version:
``v2.9.11``

### Template file:
``http/token-spray/api-tatum.yaml``

### Command to reproduce:
```
nuclei -id api-tatum -var token={some random stuffs}
```

### Anything else:
![image](https://github.com/projectdiscovery/nuclei-templates/assets/75373225/a8a5bca8-4be0-4ffc-a40e-19d58f0a1ff4)

**Comment by princechaddha** [comment]
Hi @0xPugazh, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to this project 🍻

We will update this template with a request that uses the Tatum API key. Thanks
