### ISSUE TITLE
elastic-kibana-unauthorized-access

### ISSUE THREAD

**Issue by muhamedfarish** [projectdiscovery/nuclei-templates#8112]
### Template Information:

#Name: Elastic Kibana Unauthorized Access vulnerability
Reference:https://twitter.com/zoomeye_team/status/1696454558032294272

### Nuclei Template:

id: elastic-kibana-unauthorized-access
info:
  name: Elastic Kibana Unauthorized Access vulnerability
  author: Farish
  severity: high
  description: |
    This vulnerability occurs when unauthorized users are able to gain access to Kibana resources or data without proper authentication or authorization.
  reference:     
      - https://twitter.com/zoomeye_team/status/1696454558032294272

  metadata:
    ZoomEyeDork: app:"kibana"
    verified: true
  tags: unautherizedaccess,unauthenticated

http:
  - raw:
      - |
        GET /app/kibana HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - 'contains(content_type, "text/html")'
          - 'status_code == 200'
          - 'contains(body, "Dashboard")'
          - 'contains(body, "kibana")' 
          - 'contains(body, "console")'   
        condition: and

**Comment by DhiyaneshGeek** [comment]
Hi @muhamedfarish this template appears to be duplicate of [exposed-kibana.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/exposed-kibana.yaml)

so we are closing this issue 

Thanks 😄
