### ISSUE TITLE
Create get-ip.yaml

### ISSUE THREAD

**Issue by 5hank4r** [projectdiscovery/nuclei-templates#8133]
### Template / PR Information
This Template is created for extracting the IP 

**Template Validation**
I've validated this template locally?
 **YES** 

![image](https://github.com/projectdiscovery/nuclei-templates/assets/34772838/c9ec4f1d-a8dd-422d-9796-b4efd2963555)
 

```[tasklist]
### Tasks
```

**Comment by 5hank4r** [comment]
```coffeescript
id: get-ip

info:
  name: get ip
  author: Shankar Acharya
  severity: info
  reference: []
  metadata:
    max-request: 1
    verified: "true"
  tags: info,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        part: body
        regex:
          - \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b

```

**Comment by fmunozs** [comment]
The regex can be improved since it will match non-valid IP addresses such as 300.300.300.300 or 999.999.999.999

**Comment by 5hank4r** [comment]
Both internal and public IP addresses are important, as certain applications may include IP addresses in their source code. Therefore, this regex is designed to extract a wider range of IP addresses for greater flexibility.

 This pattern ensures that each octet is in the range of 0 to 255. ipv4 only

 \b((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b

**Comment by DhiyaneshGeek** [comment]
Hi @5hank4r the regex seems to be weak and creating false positive 

we have a template which detects [internal-ip-disclosure](http/misconfiguration/internal-ip-disclosure.yaml), so we are closing this issue

Thanks
