### ISSUE TITLE
[false-positive] 

### ISSUE THREAD

**Issue by KibodWapon** [projectdiscovery/nuclei-templates#817]
**Nuclei version**
latest
```
nuclei -version 
```
latest
**Nuclei template version**

```
latest
cat ~/.nuclei-config.json
```

**Template ID**

Please submit the ID template producing false-positive results. 

**Commands to Reproduce**

```
nuclei -t template_id -target ?
```
template
springboot-detect.yaml
http://106.13.243.61:8666//actuator return 
"ERROR: 8: method not found: /actuator"
matches keyword  "actuator"

**Comment by ehsandeep** [comment]
@KibodWapon can you share the exact command as this is not reproducible?

```
echo http://106.13.243.61:8666 | nuclei -t technologies/detect-springboot-actuator.yaml

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.2.0

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [detect-springboot-actuator] Detect Springboot Actuators (@that_juan_ & dwisiswant0 & wdahlenb) [info]
[INF] Using 1 rules (1 templates, 0 workflows)
[INF] No results found. Happy hacking!
```

**Comment by ehsandeep** [comment]
Hey, as the name suggests `springboot-detect.yaml` you are using outdated version of template, these templates are updated in [v8.0.2](https://github.com/projectdiscovery/nuclei-templates/releases/tag/v8.0.2) and the latest version of the templates release is `8.0.6`
