### ISSUE TITLE
[false-positive] front-page-misconfig

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#823]
**Nuclei version**

```
2.2.1-dev
```

**Nuclei template version**

```
v8.0.6
```

**Template ID**
```
front-page-misconfig
```
**Commands to Reproduce**

```
nuclei -t front-page-misconfig.yaml -target https://www.landelijkregisterkinderopvang.nl
```

Other urls: 

https://landelijkregisterkinderopvang.nl/
https://kgr-acc.mijn.rvo.nl
https://ivo-acc.nvwa.nl/

**Comment by ehsandeep** [comment]
Thank you @pdelteil for reporting this.
