### ISSUE TITLE
[Feature] Improvements for: fortinet-fortigate-panel.yaml and cisco-asa-panel.yaml

### ISSUE THREAD

**Issue by landaboot** [projectdiscovery/nuclei-templates#838]
**Problem**
Both fortinet-fortigate-panel and cisco-asa panels are not being detected on some situations, I noticed that sometimes a 302 occurs, and that's why it's not being detected.

**cisco-asa-panel.yaml**
![image](https://user-images.githubusercontent.com/34347996/107557229-17a86b00-6bb8-11eb-95f4-898bc652b195.png)

![image](https://user-images.githubusercontent.com/34347996/107557429-59d1ac80-6bb8-11eb-8d93-c5a635c5cdaf.png)

**After setting the _redirects: true_ and _max-redirects: 2_ on both templates**

![image](https://user-images.githubusercontent.com/34347996/107557950-fac06780-6bb8-11eb-8ba7-253b09bba187.png)

![image](https://user-images.githubusercontent.com/34347996/107559143-7373f380-6bba-11eb-9551-52d69318b574.png)

**Solution**

I've set `redirects: true` and `max-redirects: 2` as described above. I don't know if this is an isolated case, but I've noticed that those findings were missing during the recon.

**Comment by ehsandeep** [comment]
thank you for suggesting the improvements @landaboot, we updated the template here https://github.com/projectdiscovery/nuclei-templates/commit/04fc878af90d71445474a847b14acf49d0387abf.
