### ISSUE TITLE
ftp-anonymous-login false positive, missing a space

### ISSUE THREAD

**Issue by aertyu1** [projectdiscovery/nuclei-templates#8403]
### Nuclei Version:

[INF] Nuclei Engine Version: v2.9.15

### Template file:

/network/default-login/ftp-anonymous-login.yaml#L33

### Command to reproduce:

nuclei -id ftp-anonymous-login.yaml -u http://XX.230.XXX.XX

### Anything else:
If the response of the FTP server matches 230, like in IP address or banner, it does false positive.
Proposed solution: change the matcher at line 33 and add a space: "230" by "230 "

![image](https://github.com/projectdiscovery/nuclei-templates/assets/50700042/560936f8-0444-40a9-8875-6ad866944779)

**Comment by pussycat0x** [comment]
Hi @aertyu1 
Thank you for bringing this issue to our attention. We've implemented some changes; please review them and provide your feedback.

```
id: ftp-anonymous-login

info:
  name: FTP Anonymous Login
  author: C3l3si4n,pussycat0x
  severity: medium
  description: |
    Anonymous FTP access allows anyone to access your public_ftp folder, allowing unidentified visitors to download (and possibly upload) files on your website. Anonymous FTP creates the potential for a security hole for hackers and is not recommended.
  reference:
    - https://tools.ietf.org/html/rfc2577
  metadata:
    max-request: 1
  tags: network,ftp,default-login

tcp:
  - inputs:
      - data: "USER anonymous\r\n"
        read: 1024
      - data: "PASS anonymous\r\n"
        read: 1024

    host:
      - "{{Hostname}}"
    port: 21

    matchers-condition: and
    matchers:
      - type: word
        part: raw
        words:
          - "Anonymous access allowed,"
          - "Logged in anonymously"
          - "230 "
        condition: or

      - type: word
        part: raw
        words:
          - "HTTP/1.1"
          - "230."
        negative: true
        
     ```

**Comment by aertyu1** [comment]
Hi, @pussycat0x Thank you for the quick review and proposed fix.
Good point to add a check in negative. Shall it has condition: or ? I am new to negative matcher, great feature !
I you put both like below, with dot before and after to fully cover all IP bytes.
230\.
\.230
Thank you :)

**Comment by pussycat0x** [comment]
@aertyu1  Certainly, I will incorporate a negative matcher and condition into the final template.
