### ISSUE TITLE
Duplicate templates Oracle Httpserver 12c

### ISSUE THREAD

**Issue by fmunozs** [projectdiscovery/nuclei-templates#8411]
### Issue description:
These two templates are reporting the same technology:

https://github.com/projectdiscovery/nuclei-templates/blob/main/http/technologies/oracle-httpserver12c.yaml
https://github.com/projectdiscovery/nuclei-templates/blob/main/http/technologies/oracle/oracle-http-server-12c.yaml

**Comment by princechaddha** [comment]
Hi @fmunozs, Thank you for taking the time to create this issue and for contributing to this project. We have merged both the templates.
