### ISSUE TITLE
Issue with TemplateMan workflolw run / update

### ISSUE THREAD

**Issue by j4vaovo** [projectdiscovery/nuclei-templates#8416]
@DhiyaneshGeek 
![666](https://github.com/projectdiscovery/nuclei-templates/assets/128683738/9005169e-1611-457c-9453-fea63b05f0b7)
https://github.com/projectdiscovery/nuclei-templates/blob/369a7820bd2f03e186adb2769982b0b0df8f786e/http/vulnerabilities/other/graylog-log4j.yaml#L54C1-L55C1

**Comment by princechaddha** [comment]
Hi @j4vaovo, Thank you for taking the time to create this issue and for contributing to this project. Thanks for flagging this; otherwise, it might have gone unnoticed for a long time. I have raised a PR reverting it. Thanks

**Comment by marcelo321** [comment]
hi @j4vaovo, can I chat with you in discord or twitter? i'm zonduu1 on twitter
