### ISSUE TITLE
Duplicate template sftp

### ISSUE THREAD

**Issue by fmunozs** [projectdiscovery/nuclei-templates#8458]
### Please describe your feature request:

https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposures/configs/sftp-config-exposure.yaml
https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposures/configs/sftp-credentials-exposure.yaml

### Describe the use case of this feature:
These two templates are checking the same file and reporting the same problem, maybe they could be merged.

**Comment by princechaddha** [comment]
Hi @fmunozs, Thank you for taking the time to create this issue and for contributing to this project 🍻
