### ISSUE TITLE
bigip-detect.yaml

### ISSUE THREAD

**Issue by 0x240x23elu** [projectdiscovery/nuclei-templates#8510]
Hi,
  I think you have to add  for big ip detection 

/public/include/js/agent_common.js
/my.policy

and 
response in header 

Server : BigIP

![image](https://github.com/projectdiscovery/nuclei-templates/assets/52744492/048c67de-908b-4336-9648-2f9dadc3f020)

**Comment by 0x240x23elu** [comment]
![image](https://github.com/projectdiscovery/nuclei-templates/assets/52744492/51d3fe60-1be9-4eb4-9d1f-4adfb8f0289d)


id: bigip-detect

info:
  name: BIGIP-Detect
  author: PR3R00T
  severity: info
  reference:
    - https://www.intelisecure.com/how-to-decode-big-ip-f5-persistence-cookie-values
    - https://support.f5.com/csp/article/K23254150
  metadata:
    max-request: 1
  tags: bigip,f5,tech

http:
  - method: GET
    path:
      - "{{BaseURL}}/my.policy"

    host-redirects: true
    matchers:
      - type: word
        part: header
        words:
          - 'BigIP'

    matchers:
      - type: word
        part: body
        words:
          - 'F5 Networks.'

**Comment by 0x240x23elu** [comment]
![image](https://github.com/projectdiscovery/nuclei-templates/assets/52744492/e84bb3da-85c0-4fc3-aeec-1f463177a73d)

**Comment by 0x240x23elu** [comment]
https://templates.nuclei.sh/@0x240x23elu/hxjQu4Sx7qKBvDGj3MbBSU

**Comment by 0x240x23elu** [comment]
https://templates.nuclei.sh/@0x240x23elu/hxjQu4Sx7qKBvDGj3MbBSU

**Comment by princechaddha** [comment]
Hi @0x240x23elu, Thank you for taking the time to create this issue and for contributing to this project 🍻

We already have a template for BigIP detection [here](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/technologies/bigip-detect.yaml). Feel free to open Issue/PR for another template.Thanks

**Comment by princechaddha** [comment]
Hi @0x240x23elu, Thank you for taking the time to create this issue and for contributing to this project 🍻

I have merged both the templates, let me know if it looks good. Thanks
