### ISSUE TITLE
WRN] Found 3 templates loaded with deprecated protocol syntax, 

### ISSUE THREAD

**Issue by kolor33** [projectdiscovery/nuclei-templates#8542]
Hi Team 
I would like ask how to Handle with this issue .What to doing with this .How to fix.?

WRN] Found 3 templates loaded with deprecated protocol syntax, update before v3 for continued support.

thanks

**Comment by DhiyaneshGeek** [comment]
Hi @kolor33 

It might be due the deprecated protocol of `requests` and `network` 

Kindly refer to this discussion [3648](https://github.com/projectdiscovery/nuclei/discussions/3648)
