### ISSUE TITLE
dns/detect-dangling-cname.yaml not working anymore

### ISSUE THREAD

**Issue by jzr** [projectdiscovery/nuclei-templates#8545]
### Issue description:
dns/detect-dangling-cname.yaml does not match anything anymore, even on targets previously identified.

### Nuclei Version:
v3.0.3

### Template file:
dns/detect-dangling-cname.yaml

### Command to reproduce:
`nuclei -t dns/detect-dangling-cname.yaml --target accelerateatlanta.event.microsoft.com`

### Cause
With my limited understanding, I believe this is introduced in https://github.com/projectdiscovery/nuclei-templates/commit/404aabdcf43435f76f30f86de430a4bbec915ace

The template changed to consider only  `part: answer` and the regex is updated to end with `$`.

In the next commit for the template https://github.com/projectdiscovery/nuclei-templates/commit/ea197a8b2c37599e343d3d02f2d28a4d70949198 `part: answer` is removed, but the regex isn't reverted to the original. 

`part` now defaults to `raw,body,all`. 
The raw response never **ends** with the CNAME, so the regex can never match due to the `$`.

### Possible solution

In my opinion checking only the answer and keeping the `$` makes the most sense. 
There is no need to look for CNAMEs in any other sections.

```yaml
    - type: regex
      part: answer
      regex:
         - "IN\tCNAME\t(.+)$"
```

Sidenote: 
The current regex contains both `\t` (literal TAB character) and a double-quoted `\\t` (escape character for TAB).
While this doesn't have any impact in this case, it can be confusing.

**Comment by herry2525** [comment]
in Service booking funcationality  while create service booking first step is to provide basic contact , email address infomration and in second step to Choose your servicing workshop where workshop not able to select and not even able to go to step 3 ahead.
