### ISSUE TITLE
SMB-enum 

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/nuclei-templates#8608]
### Template file: 

https://github.com/projectdiscovery/nuclei-templates/blob/c106d4f4c148bcd27551c8c052d02a8ae2c7ac71/javascript/enumeration/smb-enum.yaml#L3

### Command to reproduce:
nuclei -l target -t smb-enum.yaml

### Anything else:
I don't know if its nuclei new engine issue or template itself, but tries SMB Enum on every port, its must do SMB enum only when 445 is exists 
![074e30fbe86d638eb164ea0797edd254](https://github.com/projectdiscovery/nuclei-templates/assets/10222100/bc3ef563-cca3-4a17-a227-04abb1bdfd23)

**Comment by pussycat0x** [comment]
Hi @mastercho, Thank you for highlighting this issue; I have updated the template.
