### ISSUE TITLE
sangfor-sysuser-conf false positive

### ISSUE THREAD

**Issue by DShelef** [projectdiscovery/nuclei-templates#8615]
### Template file:
`http/vulnerabilities/other/sangfor-sysuser-conf.yaml`

### Anything else:
This issue will be detect on pretty much every login page in Chinese (in my specific case, a cPanel login page).
If the language used is Chinese and the login page is returned for every URL (as cPanel does) then the issue is falsely detected.
I don't have a true detection, so I don't have any suggestions for how to fix this 🤷

**Comment by DhiyaneshGeek** [comment]
Hi @DShelef i have further analysed the issue and added additional matcher and raised a PR #8655 

Let me know if it looks good 

Thanks 
DhiyaneshGeek

**Comment by DShelef** [comment]
Hullo @DhiyaneshGeek.
Your change prevents my false-positive. Thank you very much.

**Comment by DhiyaneshGeek** [comment]
Hi @DShelef Thank you so much for the confirmation
