### ISSUE TITLE
Template tag refining

### ISSUE THREAD

**Issue by knavesec** [projectdiscovery/nuclei-templates#8699]
This doesn't quite fit a typical issue format so creating my own. TLDR: I've noticed that a considerable amount of templates are tagged incorrectly or in an non-specific way. A few examples can be seen below:

We can take a few Oracle related templates for example: 

* `./http/technologies/weblogic-detect.yaml` Searches Shodan for the string `Oracle Weblogic`, but the `tags` does not contain `oracle`
* `./http/default-logins/weblogic/weblogic-weak-login.yaml` checks for default Oracle Weblogic creds, but does not contain the `oracle` tag
* `./http/exposed-panels/weblogic-login.yaml` also locates Oracle Weblogic login panels, but DOES have the `oracle` tag
* `./http/exposures/logs/oracle-ebs-sqllog-disclosure.yaml` Has some Oracle EBS log leak files, so the tags are `oracle` and `ebs`
* `./http/vulnerabilities/oracle/oracle-ebs-xss.yaml` is targeting EBS, which has `oracle` and `ebs` tags
* `./http/exposures/configs/oracle-ebs-credentials.yaml` Is also targeting Oracle EBS config file leak, but the tags are `oracle` but not `ebs`
* `./http/vulnerabilities/oracle/oracle-ebs-bispgraph-file-access.yaml` also targets EBS, but does not have the `ebs` tag
* Other examples, where there is a `d-link` tag, and a `dlink` tag, both are the same thing but running specifically would miss one or the other without prior knowledge. This also means that the `d-link` tags will never be run by `-as` because it would break it into `d` and `link` without a manual wappalyzer mapping

Simply put, there are considerable inconsistencies between the tagging that is integral to testing. In my opinion there are a few things that may need to be done to remedy this, but frankly it may be best for a wider discussion over it.

1. Review the current templates to verify templates are tagged properly to include the applicable technologies
2. Ensure that submitted templates have the same level of scrutiny

Even though the Wappalyzer mappings file is specifically only for the automatic scan, but it may be beneficial to expand that use-case to the `-tags` input as well, so custom user defined technology mappings could be created (`wordpress == wordpress, wp, etc` (also lol what is the difference between wp and wordpress tags??)) rather than only being able to use this with `-as`. Since the `tech-detect`, `fingerprinthub` and `favicon` detection templates oftentimes returns tags that don't correspond to any templates (`outlook-web-application`, `f5-big-ip`, etc) that correlation is needed. Similarly `spring-boot` is returned, but all SpringBoot related templates are tagged `springboot`, and there are many other examples like that. There isn't the standardization, nor the way to map those tags manually

And lastly, it may be better to format tags better, especially for Companies (like Oracle) that have many products. Instead of tagging things `oracle,access,manager` a more specific tag would be `oracle-access-manager`. As an example, Wappalyzer output breaks up `oracle-application-server` into `oracle,application,server` which will run far more undesired templates against the unrelated and generic `application` and `server` tags. There are ~5 (including what appears to be duped in `http/technologies/oracle-httpserver-12c.yaml` and `http/technologies/oracle/oracle-http-server-12c.yaml`) templates that are specifically related to the Oracle Application/HTTP Server, but running the `oracle`, `application`, `server` tags it will run 70 templates 

For one off products, a simple tag like `wordpress` makes sense, but for companies (Oracle, VMWare, etc) that have multiple products, it would make sense to standardize tagging to be `{company}-{product}` as well as just `{company}` so tagging is both generic and highly specific. 

Like I said earlier, I don't know what's best and maybe these are just the ponderings of a senseless man, but I've had issues where undesired templates are run, or applicable templates aren't run because they're tagged incorrectly (or the technology detection templates return different tags)

Probably best for a wider discussion, can be had in the thread. I'm happy to help of course and I've already done a bit of work re-tagging things, but as for the direction of the overall effort I feel like it would need to be decided by the maintainers and I don't want to do a bunch of work re-tagging things that would need to be re-tagged again if the standard is different from what I envisioned

**Comment by princechaddha** [comment]
Hey @knave,

Thanks for the heads-up on the tagging issues! You're right, we've got some inconsistencies. The good news is, we're already on it. We're rolling out an automatic tagging enhancement soon. Once that's in place, feel free to pitch in with a PR if you spot anything amiss.

The plan is to update tags based on vendor, product, framework, directory, protocol, vulnerability type, and info block content. This should make things way more streamlined.

About the {company}-{product} tags, we like the idea but worry it might be too long. We're leaning towards a {company},{product} format for simplicity.

We've kicked off a PR for some basic tag improvements, especially with CVE templates. Other templates might need more manual review. Your input and any further ideas are super welcome.

Really appreciate your deep dive into this. We're on track to sorting out the tagging chaos. Thank you
