### ISSUE TITLE
Extract the type "text/*" of each URL to facilitate in-depth processing

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei-templates#8815]
how 
Extract the type "text/*" of each URL to facilitate in-depth processing

In other words, in headless mode, how to obtain the document type of each connection is very important, so as to exclude the URL of the binary stream and facilitate further analysis.

$ cat headless/extract-urls.yaml
```
id: extract-urls

info:
  name: Extract URLs from HTML attributes
  author: dwisiswant0
  severity: info
  tags: headless,extractor
headless:
  - steps:
      - args:
          url: "{{BaseURL}}"
        action: navigate

      - action: waitload

      - action: script
        name: extract
        args:
          code: |
            () => {
             return '\n' + [...new Set(Array.from(document.querySelectorAll('[src], [href], [url], [action]')).map(i => i.src || i.href || i.url || i.action))].join('\r\n') + '\n'
            }

    extractors:
      - type: kval
        part: extract
        kval:
          - extract
```

**Comment by tarunKoyalwar** [comment]
@hktalent , can you explain furthur what you mean by `Extract the type "text/*" of each URL to facilitate in-depth processing`

it looks like you are suggesting we should also extract urls from tags that have `text/*` content-type, other than hardcoded ones . am i correct ?

**Comment by hktalent** [comment]
@tarunKoyalwar 
I want to judge the current response type. If it is a text type, I hope to be able to extract all URLs through regular expressions, not just regular situations, even if the URLs are in js variables or comments, they can all be extracted and put in Of course, for the next-level crawler, it would be best to be able to process the same origin before that.

Meanwhile, here's the source:
1. Same domain name
2. If the company name similarity in the SSL information is >= 0.95, it will also be identified as the same source.

**Comment by hktalent** [comment]
@tarunKoyalwar thanks
