### ISSUE TITLE
[nuclei-template] settings.php.*-files

### ISSUE THREAD

**Issue by hackerrishad** [projectdiscovery/nuclei-templates#883]
**Template Details**

```
id: settings.php.*-files

info:
  name: settings.php.* information disclosure
  author: sheikhrishad
  severity: high

requests:
  - method: GET
    path:
      - "{{BaseURL}}/settings.php.bak"
      - "{{BaseURL}}/settings.php.dist"
      - "{{BaseURL}}/settings.php.old"
      - "{{BaseURL}}/settings.php.save"
      - "{{BaseURL}}/settings.php.swp"
      - "{{BaseURL}}/settings.php.txt"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DB_NAME"
          - "DB"

      - type: status
        status:
          - 200
```

**Comment by ehsandeep** [comment]
@hackerrishad Can you share more context/reference around this template?, based on matcher, I'm assuming this is for `wp-config.php` file from WordPress CMS, but the path indicates other file.

**Comment by hackerrishad** [comment]
@ehsandeep Unfortunately I don't have any reference about this :( . but I found some critical issues by using this template.

![2021-02-18_23-17](https://user-images.githubusercontent.com/51270384/108395115-a6b02580-723f-11eb-9594-7eb4560a48eb.png)

**Comment by ehsandeep** [comment]
Thank you @hackerrishad, I will be actively looking for few examples to configure the matcher and add this template.

**Comment by ehsandeep** [comment]
Added [here](https://github.com/projectdiscovery/nuclei-templates/pull/1138/commits/70e356a8040522c62bd110c3e71cffe5569a7ed1) @hackerrishad, thank you again.
