### ISSUE TITLE
Duplicated templates

### ISSUE THREAD

**Issue by knavesec** [projectdiscovery/nuclei-templates#8860]
Two templates are duplicated:

`http/misconfiguration/gitlab/gitlab-public-registration.yaml`
`http/misconfiguration/gitlab/gitlab-public-signup.yaml`

These are almost the exact same detection methods with a _small_ difference in detection logic. Would recommend merging the logic into one and deleting the other

**Comment by princechaddha** [comment]
Hi @knavesec, the response time to this issue was much longer than usual. Thank you for taking the time to create this issue. We have merged both the templates. Thanks!
