### ISSUE TITLE
httponly-cookie-detect template is wrong - httpOnly is not a misconfiguration

### ISSUE THREAD

**Issue by ChrisAD** [projectdiscovery/nuclei-templates#8873]
The template httponly-cookie-detect detects if cookies are flagged as httpOnly, as if it was a misconfiguration. httpOnly means JavaScript can not access the cookie, NOT that the cookie can only be transmitted over HTTP.

This template should be deleted as it is simply wrong. 

### Nuclei Version:

Latest 
### Template file:

http/misconfiguration/httponly-cookie-detect

### Command to reproduce:

Run the template and see it flags cookies that are marked as httpOnly, thinking it is a misconfigurtion. 

### Anything else:

![image](https://github.com/projectdiscovery/nuclei-templates/assets/6368326/23d8e554-050f-4706-8de4-95b07b6377d0)

**Comment by ChrisAD** [comment]
https://owasp.org/www-community/HttpOnly

**Comment by princechaddha** [comment]
Hi @ChrisAD,

Thank you for taking the time to create this issue. I agree that this is not a misconfiguration. While for penetration testers, 'Cookies Not Marked as HttpOnly' is a valid issue, we have deleted this template and will add one for cookies without the HttpOnly attribute.

Thanks
