### ISSUE TITLE
None of the fuzzing templates are working

### ISSUE THREAD

**Issue by nullenc0de** [projectdiscovery/nuclei-templates#8911]
I have tried this on multiple machines with multiple versions of nuclei (including the latest). But none of the nuclei-templates/http/fuzzing/ templates are valid templates.

see screenshot below:

![image](https://github.com/projectdiscovery/nuclei-templates/assets/30237867/1aebb1b2-1ae8-4f47-9261-bb766d91b1d4)

**Comment by DhiyaneshGeek** [comment]
Hi @nullenc0de , To run fuzzing templates

using the following flag

```-tags fuzz```

example: ```nuclei -tags fuzz -u http://domainname.com```

![image](https://github.com/projectdiscovery/nuclei-templates/assets/24750220/b2efc42d-c231-4699-b53e-265f476b1597)
