### ISSUE TITLE
The api gxlu?email= of gmail no longer active

### ISSUE THREAD

**Issue by lechuhuuha** [projectdiscovery/nuclei-templates#9022]
Sorry for this to say but after testing the api we all using for gmail unlimited account has been disable
its no longer return compass cookies
anyone know how to overcome this or we have to fallback to smtp

**Comment by ritikchaddha** [comment]
Hello @lechuhuuha, we appreciate you taking the time to bring this issue to our attention. Please be assured that we will look into this and make the necessary updates to the template. Thank you for your support and for helping us improve our templates.
