### ISSUE TITLE
[nuclei-template] AWStats script

### ISSUE THREAD

**Issue by hackerrishad** [projectdiscovery/nuclei-templates#908]
**Template Details**
AWStats is a free powerful and featureful tool that generates advanced web, streaming, ftp or mail server statistics, graphically. This log analyzer works as a CGI or from command line and shows you all possible information your log contains, in few graphical web pages.

```
id: awstats-script

info:
  name: AWStats script
  author: sheikhrishad
  severity: medium

requests:
  - method: GET
    path:
      - "{{BaseURL}}/awstats"
      - "{{BaseURL}}/awstats.conf"
      - "{{BaseURL}}/awstats.pl"
      - "{{BaseURL}}/logs/awstats.pl"
      - "{{BaseURL}}/webstats/awstats.pl"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Do not remove this line"

      - type: status
        status:
          - 200
```

**Comment by ehsandeep** [comment]
@hackerrishad added here https://github.com/projectdiscovery/nuclei-templates/pull/915
