### ISSUE TITLE
Issue with nuclei templates ssl can't disable. this automaticly ssl true. pls help

### ISSUE THREAD

**Issue by lamrecognitions** [projectdiscovery/nuclei-templates#9117]
### Issue description:
how do I disable ssl:443 on nuclei ? I have looked for all the ways but when I run `nuclei -t nuclei-templates/ -l list.txt` the output results always appear and the target is only the domain that has ssl `443` I want to scan all the domains I have including ssl 80. please tire

**Comment by ehsandeep** [comment]
@lamrecognitions it's unclear to me what you are looking to disable?

If you are looking to disabe scanning ssl templates, you can add `-ept ssl` to your existing cli option.

**Comment by pussycat0x** [comment]
Hi @lamrecognitions  

FYI :
If the input is provided as 127.0.0.1:8034 or any other host, Nuclei will initially execute `HTTPX.` It will then determine whether to use HTTPS:// or HTTP:// based on the response received. This process is automated. The only requirement is to ensure that the input list does not contain URLs starting with `HTTPS://`; if it does, HTTPX won't be executed on those URLs.

**Comment by fail-open** [comment]
disable httpx from running. -nh  -no-httpx

**Comment by pussycat0x** [comment]
Hello @lamrecognitions , I trust you've found the solution you were seeking. I'll be marking this issue as resolved for now. Should you have any further questions or concerns, please don't hesitate to reopen it.
