### ISSUE TITLE
apache-server-status

### ISSUE THREAD

**Issue by 0x45DDA458** [projectdiscovery/nuclei-templates#917]
id: apache-server-status

info:
  name: Apache Web Service Status Page
  author: prismacsi redteam
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/server-status"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'Apache Server Status for'

      - type: status
        status:
          - 200

**Comment by ehsandeep** [comment]
Hi @0x45DDA458, 

Thank you for sharing this template,  fortunately, we already have this template here https://github.com/projectdiscovery/nuclei-templates/blob/de5c1e0b4790ac15ee2665d9b6e9235412d71682/misconfiguration/server-status-localhost.yaml

**Comment by ehsandeep** [comment]
Closing as this is a duplicate.
