### ISSUE TITLE
Setup template with words/format to ignore

### ISSUE THREAD

**Issue by sumgr0** [projectdiscovery/nuclei-templates#92]
Hi Team,
Is there a way to format the template to ignore words/formats from the scan, more like grep -v?

To give an example, when using the dead-host-with-cname template, how can we setup the same to ignore the host pointing to CNAME within same host.

Example:
xyz.example.com having CNAME as abc.example.com [dead]

This would result in false positive.

**Comment by bauthard** [comment]
Hey @sumgr0, 

This is can be done by using [extractors](https://github.com/projectdiscovery/nuclei-templates/blob/master/GUIDE.md#extractors) to print the cname value and later post-process them to get unique results.

**Comment by bauthard** [comment]
Closing as no action needed on this.
