### ISSUE TITLE
[Feature] Add {{Random String}} option to templates

### ISSUE THREAD

**Issue by hazanasec** [projectdiscovery/nuclei-templates#923]
Hi team,

I want to contribute a template which requires sending a request to a non existent S3 bucket. Of course this is possible by having a random bucket name in the template, however if it's made public the request will fail the moment someone registers the bucket name (which I'm sure they will). 

Would be possible to have a random string option (maybe chose a length also)?

Thank you,
Hazana

**Comment by dwisiswant0** [comment]
Hi @hazanasec, I think it already exists (related to [nuclei#234](https://github.com/projectdiscovery/nuclei/issues/234)) but there is no documentation for it (yet).

**Comment by ehsandeep** [comment]
@hazanasec as dwisiswant0 pointed out, this is already supported, we will update the guide document soon with syntax.

**Comment by ehsandeep** [comment]
New helper functions details updated here https://nuclei.projectdiscovery.io/templating-guide/helper-functions/

**Comment by hazanasec** [comment]
@ehsandeep the helper functions aren't available for HTTP Base Requests?

**Comment by ehsandeep** [comment]
@hazanasec it's limited for RAW requests for now, we have an open GH issue to support this in the coming months https://github.com/projectdiscovery/nuclei/issues/554#issuecomment-782015652
