### ISSUE TITLE
Nuclei templates checksums

### ISSUE THREAD

**Issue by AgoraSecurity** [projectdiscovery/nuclei-templates#9264]
### Please describe your feature request:

Add checksums to the release of the Nuclei templates.

The binary does have it (https://github.com/projectdiscovery/nuclei/releases/download/v3.1.10/nuclei_3.1.10_checksums.txt) and it would be nice to add it to templates too.

Note: I know that templates have signature, but having a checksum of the release is another nice layer to add

### Describe the use case of this feature:

Add an extra layer of security when getting new templates

**Comment by princechaddha** [comment]
Hi @AgoraSecurity, Thank you for taking the time to create this issue and for contributing to this project 🍻

Starting from the next release, we will be adding a checksum of the release

**Comment by princechaddha** [comment]
Closing this issue as we are now adding a checksum to our release. Thank you once again
