### ISSUE TITLE
REQ Update template default login

### ISSUE THREAD

**Issue by lolminerxmrig** [projectdiscovery/nuclei-templates#9287]
Hi All.
REQ Update template default login

user : root
pass :calvin

https://github.com/ExpLangcn/NucleiTP/blob/19d2641e627c1e52f107821b9be2937eaf0989c8/info/dell-idrac.yaml

**Comment by lolminerxmrig** [comment]
OR template default login : 
https://github.com/Elsfa7-110/kenzer-templates/blob/311d3f1fd0e68191f388c5848ec228e9b6c96db1/nuclei/idscan/dell-idrac-detect.yaml

**Comment by pussycat0x** [comment]
Hi @lolminerxmrig  we already have default login template for [dell-idrac](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/default-logins/dell/dell-idrac-default-login.yaml) If there's anything you'd like to revisit or discuss further reopen the issue :) .
