### ISSUE TITLE
drupal-install template should be high severity

### ISSUE THREAD

**Issue by yaabdala** [projectdiscovery/nuclei-templates#9336]
### Issue description:
The drupal-install template classifies this exposure as `low`, I think it deserves a higher severity because an attacker could create admin credentials and takeover the box if they encounter a drupal instance in this state. Suggest `high` as an appropriate severity.

**Comment by pussycat0x** [comment]
Hi @yaabdala, Thank you for informing us. We have adjusted the severity accordingly.
