### ISSUE TITLE
Nuclei id templating

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei-templates#9342]
Can we change the template id according to the file name. For example, in folder `javascript/default-logins` there are 4 files:

```
mssql-default-logins.yaml
postgres-default-logins.yaml
redis-default-logins.yaml
ssh-default-logins.yaml
```

But when we checked the id:
```
mssql-default-logins
postgres-weak-credentials
redis-weak-credentials
ssh-weak-credentials
```

This is quite confusing for me because of the inconsistency in the ID of each template

**Comment by DhiyaneshGeek** [comment]
Hi @daffainfo 

i have made the changes and updated with a PR #9354 

Let me know if it looks good 

Thanks
