### ISSUE TITLE
microsoft-iis-version status code problem

### ISSUE THREAD

**Issue by hczdmr** [projectdiscovery/nuclei-templates#9356]
### Nuclei Version:
3.2.0

### Template file:
http/technologies/microsoft/microsoft-iis-version.yaml

### Command to reproduce:
nuclei -u https://xxx.com -t /opt/nuclei-templates/http/technologies/microsoft/microsoft-iis-version.yaml

### Description:
It cannot detect a misconfigured application due to the status code check in the template. For example; Let xxx.com be an exchange application. When I start a scan with this domain, the response to the outgoing request is 302 status code and redirect to xxx.com/owa/. It cannot detect it because there is a check for status code 200 in the template. It can detect when the status code control within the template is removed.

**Comment by hczdmr** [comment]
We can remove the status section and add the following code:
host-redirects: true
max-redirects: 5

**Comment by princechaddha** [comment]
Hi @hczdmr, Thank you for taking the time to create this issue and for contributing to this project 🍻
