### ISSUE TITLE
Issue with custom templates

### ISSUE THREAD

**Issue by Dark-Aura** [projectdiscovery/nuclei-templates#9369]
![image](https://github.com/projectdiscovery/nuclei/assets/65353593/255b1d90-66b9-4d6c-8b3d-51ced14cbe3f)

**Comment by DhiyaneshGeek** [comment]
Hi @Dark-Aura , 

Thanks for raising the issue 

Fuzzing templates can be loaded by using `-fuzz` option added in [nuclei v3.2.0](https://blog.projectdiscovery.io/nuclei-3-2/)

Let me know if it works

**Comment by Dark-Aura** [comment]
yup, its working 👍

**Comment by DhiyaneshGeek** [comment]
Thanks for confirming, so we are closing this issue
