### ISSUE TITLE
[Bug] Improper validation of open-redirection template

### ISSUE THREAD

**Issue by gano3s** [projectdiscovery/nuclei-templates#939]
**Nuclei version**

```
2.2.1-dev
```

**Nuclei template version**

```
the latest git version (commit c9a2327)
```

**Describe the bug**
Open redirection template does not fully validate redirections. If the final URL contains multiple subdomains or username (by character @) it is not properly recongized.

**Proposed fix**
https://github.com/projectdiscovery/nuclei-templates/pull/938

**Comment by ehsandeep** [comment]
@gano3s thank you for rasing this, do we have an example, or example case where the current regex will miss out?

**Comment by gano3s** [comment]
Hi @ehsandeep.
For obvious reasons, I cannot show you it in wild - I discovered this behavior on our internal systems and we already patched them :-)
But you can validate it by yourself on the https://regex101.com/

** The original regex **
![image](https://user-images.githubusercontent.com/2551605/109174580-42341f80-7785-11eb-957e-fd51d5492eae.png)
![image](https://user-images.githubusercontent.com/2551605/109174649-4fe9a500-7785-11eb-8512-b94c12e0f437.png)
** my change **

![image](https://user-images.githubusercontent.com/2551605/109174750-6a238300-7785-11eb-884f-6becfcee0829.png)
![image](https://user-images.githubusercontent.com/2551605/109174789-74de1800-7785-11eb-83c6-976497661072.png)

**Comment by ehsandeep** [comment]
thank you for adding more context to this and providing a fix, merged the PR here https://github.com/projectdiscovery/nuclei-templates/pull/938
