### ISSUE TITLE
symfony-debug.yaml template not giving accurate results 

### ISSUE THREAD

**Issue by rajathsharma** [projectdiscovery/nuclei-templates#9466]
Hello Team, I am currently testing a specific URL. During the execution of the nuclei templates, particularly the `symfony-debug.yaml`, it flagged a "symfony-debug" issue as a High finding. However, when I try to access the URL, I encounter a Request forbidden by administrative rules. message. Could you please verify the accuracy of the template?

https://github.com/projectdiscovery/nuclei-templates/blob/0585fa1bcb21fb595ef9f8ec3eb441f042ae105a/http/misconfiguration/symfony-debug.yaml

<img width="547" alt="image" src="https://github.com/projectdiscovery/nuclei-templates/assets/146168568/940f7089-523b-4d0b-b544-22b5c61aeac3">

**Comment by DhiyaneshGeek** [comment]
Hi @rajathsharma Thanks for raising the issue 

Is it possible to share more details about it by joining our  [discord server](https://discord.com/invite/projectdiscovery). ?

**Comment by rajathsharma** [comment]
Hi, I have raised the issue here: https://discord.com/channels/695645237418131507/1224204443936100493
