### ISSUE TITLE
Duplicate templates

### ISSUE THREAD

**Issue by daffainfo** [projectdiscovery/nuclei-templates#9505]
Need to delete one of them

https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/php-debugbar-exposure.yaml
https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposures/logs/php-debug-bar.yaml

**Comment by princechaddha** [comment]
Hi @daffainfo, Thank you for taking the time to create this issue
