### ISSUE TITLE
[nuclei-template] Dell iDRAC Workflow

### ISSUE THREAD

**Issue by kophjager007** [projectdiscovery/nuclei-templates#951]
A workflow for Dell iDRACs. If an instance is observed, check for default credentials.  
(workflows/dell-idrac-workflow.yaml)

```
id: dell-idrac-workflow.yaml
info:
  name: Dell iDRAC Security Checks
  author: kophjager007
  description: A workflow to identify Dell iDRAC instances and run all related nuclei templates.
  tags: workflow

workflows:
  - template: technologies/dell-idrac-detect.yaml
    subtemplates:
      - template: default-logins/idrac/dell-idrac-default.yaml

```

**Comment by ehsandeep** [comment]
thanks a lot, @kophjager007 for adding a complete set of templates, we have added the template in the following PR https://github.com/projectdiscovery/nuclei-templates/pull/968
