### ISSUE TITLE
Shopify Takeovers No Longer Possible

### ISSUE THREAD

**Issue by tylerwhardy** [projectdiscovery/nuclei-templates#9595]
### Anything else:

Shopify now requires domain ownership verification
![image](https://github.com/projectdiscovery/nuclei-templates/assets/50224819/ebd946fc-ec76-4f6d-afa8-03f28860bc1f)
As a result, this check can no longer produce a subdomain takeover

**Comment by DhiyaneshGeek** [comment]
Hi @tylerwhardy 

It looks like edge case scenario as mentioned in https://github.com/EdOverflow/can-i-take-over-xyz

Looking forward to hear back from you

Thanks

**Comment by DhiyaneshGeek** [comment]
Hi @tylerwhardy Due to the inactivity, also we didn't hear back from you

so we are closing this issue 

Thanks

**Comment by GDATTACKER-RESEARCHER** [comment]
IT'S POSSIBLE STILL BUT YES IN SOME CASES IT MIGHT REQUIRE DNS VERIFICATION. ALSO THE ERROR PAGE HAS BEEN REPLACED WITH NEW ONE.

**Comment by verdant-code** [comment]
So is it still possible?
