### ISSUE TITLE
Vercel Takeovers No Longer Possible

### ISSUE THREAD

**Issue by tylerwhardy** [projectdiscovery/nuclei-templates#9596]
### Command to reproduce: Any

![image](https://github.com/projectdiscovery/nuclei-templates/assets/50224819/577a8a04-a155-4a5e-bff3-6d60c9d3f40e)

### Anything else:

Vercel now requires domain verification via TXT record so domain takeovers are no longer possible. This template is obsolete and should be removed or archived.

**Comment by tylerwhardy** [comment]
https://github.com/projectdiscovery/nuclei-templates/blob/main/http/takeovers/vercel-takeover.yaml

**Comment by DhiyaneshGeek** [comment]
Hi @tylerwhardy 

It looks like edge case scenario as mentioned in https://github.com/EdOverflow/can-i-take-over-xyz

Looking forward to hear back from you

Thanks

**Comment by DhiyaneshGeek** [comment]
Hi @tylerwhardy 

Due to the inactivity, also this is an edge case 

we are closing this issue 

Thanks
