### ISSUE TITLE
[nuclei-template] 

### ISSUE THREAD

**Issue by nikhil-kumar01** [projectdiscovery/nuclei-templates#960]
**Details**

Description:
Arbitrary Text Injection is an attack where an application does not properly handle user-supplied data, an attacker can supply content to a web application, typically via a parameter value or through the URI path, that is reflected back to the web page.

Impact :
Risk factors depend on the business type of the application. If the application business brand is well known and has major competitors, this issue can be abused by malicious competitors/disgruntled employees/unsatisfied customers to trigger mass distributions of false messages to unsuspecting customers.

Refrence: 
https://owasp.org/www-community/attacks/Content_Spoofing
https://hackerone.com/reports/327671

```
id: Arbitrary Text Injection

info:
  name: Arbitrary Text Injection
  author: Nikhil Kumar(https://www.linkedin.com/in/nikhil-kumar-4b9443166/)
  severity: Low
  tags:  injection

  
requests:
  - method: GET
    path:
      - "{{BaseURL}}/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"

    matchers:
      - type: word
        words:
          - "!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"
        part: body

#Hackerone Report
#https://hackerone.com/reports/327671
...

**Comment by ehsandeep** [comment]
@nikhil-kumar01 really appreciate you writing and sharing the template, unfortunately, text injection is not a valid security issue, content-spoofing is more aligned with HTML/CSS or any injection that has more control to reflect the significant change on the page, with that said I'm closing this issue.
