### ISSUE TITLE
xtremerat-trojan: False Positive on SSH-2.0-X

### ISSUE THREAD

**Issue by theMiddleBlue** [projectdiscovery/nuclei-templates#9624]
### Nuclei Version:
```
$ nuclei -version
[INF] Nuclei Engine Version: v3.1.10
```

### Template file:
[network/c2/xtremerat-trojan.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/network/c2/xtremerat-trojan.yaml)

I think this part is too inclusive (basically matches every response that includes an `X`) matching, for example, also `SSH-2.0-X`
https://github.com/projectdiscovery/nuclei-templates/blob/f672d53e8f3c132f46806e116264e430e89c23ec/network/c2/xtremerat-trojan.yaml#L27-L31

### Command to reproduce:
nuclei -t network/c2/xtremerat-trojan.yaml -u *target*

*target*: any of the following:
https://www.shodan.io/search?query=%22SSH-2.0-X%22

#### Fix:
Replacing the current matcher with the following, can it be an option?

```yaml
matchers:
  - type: regex
    regex: 
      - "^X$"
```

**Comment by GeorginaReeder** [comment]
Thanks for opening this issue @theMiddleBlue , we'll take a look into it!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

**Comment by theMiddleBlue** [comment]
Thank you, I just joined. :) BTW, if my approach makes sense, I can open a pull request.

**Comment by DhiyaneshGeek** [comment]
Hi @theMiddleBlue , feel free to send the PR 

Our team members will review it and make changes if necessary 

Thanks for joining the discord server 😄
