### ISSUE TITLE
False positive result using: http/misconfiguration/node-express-dev-env.yaml

### ISSUE THREAD

**Issue by Nishantbhagat57** [projectdiscovery/nuclei-templates#9654]
### Nuclei Version:

3.2.5 (Latest)

### Template file:

```http/misconfiguration/node-express-dev-env.yaml```

### According to template these URLs are vulnerable:
https://www.ftp.careem.com/
https://fs05.18tiktok.com/
https://gps.whatsapp.ocularcloud.com/
https://graphql2-staging.virbhumi.com/
https://game.mellocloud.com/
https://home.delsaohabcloud.com/
and more...

![Screenshot 2024-04-28 020812](https://github.com/projectdiscovery/nuclei-templates/assets/64642374/58e8e8f6-762e-4d08-ad8a-0b0056cf6166)
![Screenshot 2024-04-28 020722](https://github.com/projectdiscovery/nuclei-templates/assets/64642374/75b7109b-17bb-4790-9bbf-653713d678a8)

**Comment by DhiyaneshGeek** [comment]
Hi @Nishantbhagat57 , i think it's working intended. not a FP

you can `-debug` to see the result
