### ISSUE TITLE
False positives from file/malware/cerberus-malware.yaml template

### ISSUE THREAD

**Issue by ErikOwen** [projectdiscovery/nuclei-templates#9688]
### Nuclei Version:

nuclei v3.0.3, nuclei-templates  v9.8.5

### Template file:

file/malware/cerberus-malware.yaml

### Command to reproduce:

```bash
echo "cerberus" > index.html
echo index.html | nuclei -t file/malware/cerberus-malware.yaml
```

### Anything else:

This template is matching any file that has the string "cerberus" in it. The nuclei template matching criteria should be more strict so that it does not generate false positives.

**Comment by DhiyaneshGeek** [comment]
Hi @ErikOwen 

This template [file/malware/cerberus-malware.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/file/malware/cerberus-malware.yaml) is based on the [Yara Rules](https://github.com/Yara-Rules/rules/blob/master/malware/RAT_Cerberus.yar) it should match to condition any of them

As a edge case i have updated the template and raised a PR for it [9701](https://github.com/projectdiscovery/nuclei-templates/pull/9701)

Thanks

**Comment by ErikOwen** [comment]
Thank you, @DhiyaneshGeek! 🙏
