### ISSUE TITLE
BIG-IP Next Central Manager Login panel

### ISSUE THREAD

**Issue by EgemenKochisarli** [projectdiscovery/nuclei-templates#9733]
### Template Information:

[](https://clouddocs.f5.com/bigip-next/latest/use_cm/)

### Nuclei Template:

id: f5-next-central-manager

info:
  name: F5 Next Central Manager Login Panel - Detect
  author: EgemenKochisarli
  severity: info
  description: F5 Next Central Manager login panel was detected.
  reference:
    - https://clouddocs.f5.com/bigip-next/latest/use_cm/
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:h:f5:big-ip:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: bigip
    vendor: big-ip_next_central_manager
  tags: panel,fortinet

http:
  - method: GET
    path:
      - "{{BaseURL}}/gui/login"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>BIG-IP Next | Central Manager</title>"

      - type: word
        part: header
        words:
          - "text/html"

      - type: status
        status:
          - 200

**Comment by GeorginaReeder** [comment]
Thanks for your contribution @EgemenKochisarli , we appreciate it!
