### ISSUE TITLE
[netrc] template creating False Negative results

### ISSUE THREAD

**Issue by tess-ss** [projectdiscovery/nuclei-templates#9755]
Hi team,

The following template located here [netrc](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposures/configs/netrc.yaml) creating False Negative results. The following template is `high` severity and I believe should be fixed to make Nuclei scans better for everyone.

Thanks,
@tess

**Comment by pdelteil** [comment]
I think you should give examples of false positives and true positives in order to be fixed.

**Comment by DhiyaneshGeek** [comment]
Hi @pdelteil It is already shared to us , i'm currently working on fixing this 

Thanks
