### ISSUE TITLE
"Docker Registry Listing" template results in Bitbucket false positives.

### ISSUE THREAD

**Issue by EdOverflow** [projectdiscovery/nuclei-templates#98]
The [Docker Registry Listing](https://github.com/projectdiscovery/nuclei-templates/blob/master/files/docker-registry.yaml) template's matcher is too lax resulting in false positives when encountering self-hosted Bitbucket instances. The `/v2/_catalog` endpoint will return a 404 on Bitbucket but the `repositories` string is in the navbar. This results in false positives.

https://github.com/projectdiscovery/nuclei-templates/blob/fb49301edec4fc805f9bc19e6f867b51a9cbdd93/files/docker-registry.yaml#L12-L15

![image](https://user-images.githubusercontent.com/18099289/82736430-08337a00-9d2a-11ea-9598-600d642185c8.png)

I suggest possibly matching the surrounding JSON syntax.

**Comment by bauthard** [comment]
Thank you for pointing this out @EdOverflow, let me update the signature with more strict matching to avoid any false positive.

**Comment by bauthard** [comment]
@EdOverflow multiple checked added in [docker-registry.yaml ](https://github.com/projectdiscovery/nuclei-templates/blob/master/files/docker-registry.yaml) based on information at https://docs.docker.com/registry/spec/api/, also added redirects as `//v2/_catalog` redirects back to `/v2/_catalog`
