### ISSUE TITLE
bring back "bugbounty.yml" file

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei-templates#9814]
Would it be possible to bring back "bugbounty.yml" file? it used to be in `/nuclei-templates/profiles/bugbounty.yml` but now I don't see it anywhere.

edit: is it the same as "recommended.yml"? if it is, then all good. but bugbounty.yml was pretty good at removing a lot of "informative" issues that had severity  for thigns like a pentest (like ssl issues)

**Comment by ritikchaddha** [comment]
Hello @marcelo321, I hope you are doing well. 
Yes, both `bugbounty.yml` and `recommended.yml` are the same profiles.
